### ISSUE TITLE
Full HTSP support (Streaming over HTSP)

### ISSUE THREAD

**Issue by janeczku** [rsiebert/TVHClient#100]
Currently only the meta data / API part of the HTSP protocol is implemented. It would be great if the app supported the actual video streaming part for which HTSP was primarily intended. How about embedding a player object e.g. using the VLC SDK for Android?
https://wiki.videolan.org/LibVLC/

**Comment by rsiebert** [comment]
This would probably require a bit more time and effort implementing the streaming. What would be the killer feature or benefit to it instead of using an external player?

**Comment by MrFly** [comment]
To get a second view for this request: For me it works really perfect (how it is) with the MX Player Pro (and the right decoder lib) as external player. So for me there would be no need to implement this. But I can understand the wish of an all-in-one app, which is "full featured" including video playback. But to call this a "killer" would be much oversized I think :-)

**Comment by janeczku** [comment]
Benefits: 
1. HTSP is a _true streaming_ protocol. HTTP progressive file streaming is not optimized in any way for a reliable video stream. The later works OK in a local network environment but introduces lots of issues when streaming over the internet. Just to give an example: I am streaming 7 mbit/s DVB-S mpeg live streams from a server in Munich to a DSL line in Berlin. This works very reliable over HTSP. HTTP on the other hand has lots of video drop outs.
2. Security. With the all-in-one protocol, only the HTSP port has to be opened on the firewall. I am not comfortable exposing the HTTP part of my TVHeadend server to the public internet.

Are those killer features? Maybe not. I guess it comes down to cost/benefit. For what it's worth, there is already a VLC plugin for HTSP that could be integrated with the SDK player object. So one would probably not really have to code anything HTSP stream related.
See here: https://github.com/BtbN/vlc-htsp-plugin

**Comment by rsiebert** [comment]
Implementing and testing this would be too much effort currently. I just don't have the time to do this. If somebody starts the work and/or creates a PR I will gladly integrate this feature.

**Comment by AlBundy33** [comment]
I know this entry is old but afaik the benefit of htsp would be to use timeshift-feature from tvheadend. 
Hopefully with seekable streams if permanent timeshift is acitvated.
