### ISSUE TITLE
1.7.0 with tvheadend 3.4patch1 error record

### ISSUE THREAD

**Issue by analogtv** [rsiebert/TVHClient#105]
After create a record, you cant reconnect to tvheadend. 3.4
example: tvheadend log.

 Welcomed client software: org.tvheadend.tvhclient (HTSPv8)
starting at 2015-02-15 16:59:00, scheduled for recording by "user"
 org.tvheadend.tvhclient ]: Disconnected

Welcomed client software: org.tvheadend.tvhclient (HTSPv8)
org.tvheadend.tvhclient ]: Write error -- Connection reset by peer
org.tvheadend.tvhclient ]: Disconnected

**Comment by rsiebert** [comment]
Is this issue still a problem? The version 1.7.3 uses the codebase of 1.6.1.

**Comment by analogtv** [comment]
Hi 

Works in 1.7.3 
Thanks

**Comment by PiterEL** [comment]
Wait for realesed version 1.7.3 because i now work on tranclation PL. Take me about 30minutes/.
