### ISSUE TITLE
Bug search bar

### ISSUE THREAD

**Issue by PiterEL** [rsiebert/TVHClient#108]
Please remove bar red under search bar...

![screenshot_2015-02-16-09-20-29](https://cloud.githubusercontent.com/assets/4134018/6208727/7d0e0476-b5bd-11e4-99dd-f732c18e92af.png)

**Comment by rsiebert** [comment]
This is no bug. The android search bar is not as high as the toolbar or actionbar. When the search is active you still see the toolbar underneath.

**Comment by ghost** [comment]
It is bad

**Comment by rsiebert** [comment]
I know it does not look good. I'll look into this. The gmail app searchbar
looks good, so there are solutions to it.

2015-02-18 22:56 GMT+01:00 Piotr Kuchciak notifications@github.com:

**Comment by rsiebert** [comment]
This will be fixed in the 1.7.6 release
