### ISSUE TITLE
Cannot access settings in 1.7.2

### ISSUE THREAD

**Issue by Ansa89** [rsiebert/TVHClient#109]
With version 1.7.2 I cannot access the settings menu because there isn't any button for it (the three vertical dots button isn't displayed).
I have an hardware "settings button", but also using this one doesn't show up nothing.
I also tried putting the phone in landscape mode, but the application seems to not support this mode.

Device: xiaomi mi2
OS: wiui 4.8.29 (android 4.1.1)

PS: with 1.7.3 everything is good since it's based on 1.6.1 codebase.

**Comment by rsiebert** [comment]
In 1.7.2 and before the menu can also be accessed by swiping to the right from the left screen. Thanks for reporting back.

**Comment by Ansa89** [comment]
Isn't supposed to be "left to right" (→) instead of "right to left" (←) ?
I ask this because I tried with the first one (obviously without success).

**Comment by rsiebert** [comment]
Yes left to right is correct. I guess I've mixed it up.

2015-02-16 14:06 GMT+01:00 Ansa89 <notifications@github.com>:
