### ISSUE TITLE
Icon tag not show in version 1.7.3

### ISSUE THREAD

**Issue by PiterEL** [rsiebert/TVHClient#110]
In new version 1.7.3 option icon tags not working. No available icon when i select tags...

**Comment by rsiebert** [comment]
This was already present in 1.6.1 right? The icon with the three horizontal bars prevents currently showing the channel tag.
![image](https://cloud.githubusercontent.com/assets/1406960/6256514/254f8996-b7b9-11e4-91e9-e8a390c50b1d.png)

**Comment by ghost** [comment]
Yes in 1.6.1
when icon tag is not show you should deleted option in menu settings. But in my opiniom show icon tag is very good as 1.6.1

**Comment by ghost** [comment]
Maybe move icon tag to other place on the screen ?

**Comment by ghost** [comment]
For what is avaible option to icon tag in settings ? When this function is not avaible in version 1.7.5....

**Comment by rsiebert** [comment]
Channel tags are not visible in version 1.7.5 due to the actionbar.
For the next version I can show an channel tag icon next to the icon that
opens the menu.

2015-02-21 14:48 GMT+01:00 Piotr Kuchciak notifications@github.com:

**Comment by rsiebert** [comment]
Available in 1.7.6
