### ISSUE TITLE
Feature Request: Default profiles for LAN/WAN

### ISSUE THREAD

**Issue by MrFly** [rsiebert/TVHClient#112]
Hi,

I want to commit a feature request: Please add a simple functionality to switch server profiles. I can imagine about somethinge like a (W)LAN default profile and an other default profile for connecting via inet (WAN).

Currently we have to choose the favorite connection profile always if we leave the house or come back. A automatic switch to the second default profile if leaving a specified WLAN network would be great. If you are interested: exactly this feature is implemented in the app "MPDroid". There you can choose a WLAN network and set the default connection parameters and one other default profile if you are not connected to the specified WLAN network.

This would really be very helpful.

I hope I could explain my wish, so that you can understand what I mean.

Thanks a lot, very great app!

**Comment by rsiebert** [comment]
Hi,
I have added the option to change the server from the navigation / side menu. There is a small array that opens a menu to select a new server. Similar to the google mail account switching. 
Implementing your suggestion would include checking which network is currently active and remember that setting per connection.

Best regards
Robert

**Comment by rsiebert** [comment]
This will be available in the 1.7.6 release

**Comment by MrFly** [comment]
Great! U're the best :+1:

**Comment by rsiebert** [comment]
Available in 1.7.6
