### ISSUE TITLE
OpenVPN - No TVH connect

### ISSUE THREAD

**Issue by BlueCase** [rsiebert/TVHClient#113]
Hi,
I discovered that TVHclient is not able to connect the TVHServer over OpenVPN for Android which use per default a tun interface.
I checked my whole configuration and all works, except the TVHclient connect.

Status of TVHclient:
Connect Timeout 

Hope you could help to fix this issue and thanks for the really great App!

**Comment by rsiebert** [comment]
Other users have reported that this works. See #91.
