### ISSUE TITLE
Android TV support

### ISSUE THREAD

**Issue by filipproch** [rsiebert/TVHClient#127]
Hi I am thinking of Android TV support for this application, are you working on it? Because if not I would like to start with it, or if you are already working, to help with it.

**Comment by rsiebert** [comment]
On what extend do you plan to add support for Android TV? Do you plan to use the leanback library or just add some small changes?

**Comment by filipproch** [comment]
I plan to use the leanback library, so it will be ok with Android TV guidelines

**Comment by rsiebert** [comment]
So you need to rewrite a lot of the UI stuff I guess.

**Comment by filipproch** [comment]
Yes for sure, but I use this application very often and now have Android TV. I will post some UI screenshots / wireframes when I finish the UI/UX design.

**Comment by craigbeat** [comment]
You don't need to do any UI stuff really. If you use the TV Framework, it will handle the UI for you: https://source.android.com/devices/tv/
I've tried it using the example source on the developer site:
https://developer.android.com/training/tv/tif/index.html
They are doing a talk about it at IO next week too. My test was really simple, and just had some channel lists with no EPG data. Perhaps you could use the TVHClient code to get the EPG and channel list, and fire it back to the Live TV app:
https://play.google.com/store/apps/details?id=com.google.android.tv&hl=en

**Comment by filipproch** [comment]
Ah, I missed that, thx, I will look into it

**Comment by filipproch** [comment]
@rsiebert I no longer use tvheadend to stream tv over my house, so I am no longer going to work on this, but I am at least going to share what I have found so far

### Option 1. - using TV Framework
1. the best practice would be to create a new app with packageNameAppendix .androidtv or so, because using TV Framework requires almost no UI / DB storage and the only thing that would be neccessary from normal Android app would be downloading / communication stuff, but the way it works there is a bit different, so reflect it
2. create two services, one for downloading and updating data (I think that maybe JobScheduler would be best choice for this), and TVService, doing the playback / system epg database
3. create a setup activity, TV friendly, where users will fill their credentials / server address, but simplify this (nobody want's to write on TV and these aren't things you can easily say), maybe using network scanning / creating webserver and allowing remote setup, something like this
4. setup activity, TV friendly, allow user to change these settings

Multi tvheadend support, which will also be logical option, will add ton of code to write. Definitely not a thing you to be done in first version, but it would be good to write the app from the beggining with this in mind.

No recording queriing and other such stuff supported (there is no UI for this in TV Framework so far)

### Option 2. - full Android TV app

Can't say whether it would be easier or not, but will allow to make managing recording possible as well as full control over UI and such stuff. Another plus will be that the current app could be extended in such way, only adding UI for TV, no other changes (maybe small) required.

As I stated in beggining, I don't have enough time and no longer using tvheadend, so not going to develop this. If there is someone who is brave enough to do it I wish you good luck and offer my help (PM me, I have explored TV Framework and Android TV a lot). However, it's also possible that I will somewhere in future return to tvheadend and by that time, I could possibly return to this, but not seeing it for now.

**Comment by mihailescu2m** [comment]
Is there any client app that integrates with Live Channels android tv app?

**Comment by filipproch** [comment]
@mihailescu2m well I have somewhere a really alpha version, but as I no longer use tvheadend and don't have it I can't test it and I think it did not work yet, if I will find some time, I may push it during this weekend to androidtv branch

**Comment by tunip** [comment]
I am also interested in a Live Channels integration for Android TV. If you need a tester let me know it.

**Comment by micstar1967** [comment]
I just purchased a Shield Android TV and playing around with different option for live tv. It would be great to install TVH-Client on my Shield. Will that be possible in the near future?

Currently I have a TT Connect USB box for TV and use DVB-Link-Server on Synology DS415+ (DSM 6.0 Beta) 

If you need a tester Let me know ;-)

**Comment by smoothquark** [comment]
Any further news on this? I would love to test out an android TV version.

**Comment by mihailescu2m** [comment]
@smoothquark apparently with latest tvheadend and Aurora TV app on android TV you can have live channels. I haven't tested this out yet tho`, if you get them working please post here...

**Comment by tunip** [comment]
Aurora TV app with Tvheadend (DVB-S2) works on SHIELD TV. I only tested FTA channels, because the manual scanning hangs at a specific frequence.
And refresh rate switching works only in the Aurora TV app, not in the Live Channels app.

**Comment by tunip** [comment]
If you want a working Android TV app for live tv you can try roboTV from pipelka with VDR (with his xvdr-plugin robot tv branch) as backend. This is my new setup.

**Comment by ghost** [comment]
@tunip, looking into VDR, it cannot be run from Synology NAS boxes like tvheadend can.

This is a great library that makes it way easier to hook into AndroidTV's live channels, could speed up development of AndroidTV implementation for TVHClient if anyone's interested
https://github.com/Fleker/ChannelSurfer

**Comment by tunip** [comment]
@serpent666
If your Synology NAS supports docker containers, then VDR can also run inside a container on your NAS. My VDR setup runs fine in a docker environment with a external SAT>IP tuner box.

**Comment by swttt** [comment]
Any news on this? Would love tvh as well. currently running vdr, but would prefer tvh. Easier to configure and doesn't feel as sluggish as vdr.

**Comment by rsiebert** [comment]
I have checked the documentation. The android TV functionality needs a lot of new stuff inside the app. Considering this I just don't see the time and justification for this effort. Patches are still welcome!.
