### ISSUE TITLE
Add the option to create a Current Recording

### ISSUE THREAD

**Issue by Andulien** [rsiebert/TVHClient#135]
Currently there is the option for Timed Recording and Series Recording. However adding a Current Recording, which is setting up a one time recording is missing. I use this on the web interface in times where the EPG is not reaching far enough into the future to show me a movie or episode I want to record and therefore I add it manually to the current recordings as a one off recording.﻿
![addcurrentrecording](https://cloud.githubusercontent.com/assets/12703546/7923352/9b3c47da-08b2-11e5-84e3-f552b037e85f.JPG)

**Comment by rsiebert** [comment]
Should work in the latest 1.8.0 version.

**Comment by Andulien** [comment]
Creating a new Current Recording is working perfect :) 
Deleting works fine as well. 
Editing recording is related to Bug https://github.com/rsiebert/TVHClient/issues/138 

I think this enhancement request can then be closed.
