### ISSUE TITLE
Name field is deleted when editing a Series/Timed Recording

### ISSUE THREAD

**Issue by Andulien** [rsiebert/TVHClient#136]
The Name field is deleted when editing an existing Series/Timed Recording item, as this field is not included in TVHClient.

![namefieldempty](https://cloud.githubusercontent.com/assets/12703546/7923421/2c3f5362-08b3-11e5-93f5-f6443215a3d4.JPG)

**Comment by rsiebert** [comment]
Name field was added in the latest 1.8.0 beta.

**Comment by Andulien** [comment]
I'll test once it showes up in Google Play.

**Comment by Andulien** [comment]
Working now. Can be closed.
