### ISSUE TITLE
Editing/Removing a Timed Recording

### ISSUE THREAD

**Issue by Andulien** [rsiebert/TVHClient#137]
Editing a timed recording will create a new record rather than editing the existing one.

Removing a timed recording does currently not work due to permission problems﻿.

Robert - "There is no edit timer recording API call, so I remove the old one and add the "edited" one. I guess I have to check that the API is at least 21 where the permission fixes were included in the server. Which server version are you using again?﻿"

Current TvHeadend Version: 4.9.95-1.

**Comment by rsiebert** [comment]
Tvheadend version 4.9? Do you mean 3.9.95-1 or 4.1.95-1? If this version is compiled from git, can you write down the hash here? I assume the version does not include certain fixes.

**Comment by Andulien** [comment]
My bad, I meant 4.1.95-1

Version: 4.1.95-1
Architecture: 88f6281
Firmware: 4458 (DSM 5.0-4458) & up
MD5: 9135840d70463303b6434c86a6e36913

http://syno.dierkse.nl/

**Comment by Andulien** [comment]
Just updated to HTS Tvheadend 4.1.150. Problem still persists.

**Comment by rsiebert** [comment]
Hmm, I use 4.1-113 and I can edit a recording. Which values do you enter, does it work when only one value is changed over time? Still an issue with 1.8.0?

**Comment by Andulien** [comment]
Hmm.. Now editing does not work at all anymore. I tried editing time / Channel / Weekdays. I can't save any changes anymore and only get the message:

"Aufnahme konnte nicht entfernt werden. User does not have access."

Saving worked before but created a duplicate entry. Getestet mit der neuest Version 1.8.0.

**Comment by rsiebert** [comment]
I have changed the logic a bit. Because there is not command to actually
edit a timed recording (only delete and add are available) I first removed
it and the readd the changed version. But before adding the changed version
I'll wait for the server confirmation that the recording was removed. Due
to the permission problem this confirmation is not successful, so no adding.

Does the user has access to change the recordings? I think there is a "DVR
All RW" option in the permission page of the server.
Maybe it is related to http://tvheadend.org/issues/2888 ?

Andulien notifications@github.com schrieb am Do., 4. Juni 2015 um
09:17 Uhr:

**Comment by Andulien** [comment]
https://github.com/rsiebert/TVHClient/issues/143 Needs to be fixed before further testing can be conducted.

**Comment by Andulien** [comment]
Yup just checked. Seemed a permission issue.

One more topic tho before this issue can be closed. Once the edit is completed the Timed Recordings should be refreshed. This currently does not seem to happen, which leads to the old timed recording still being seen on screen. This can lead to confusion ;)

**Comment by rsiebert** [comment]
When I edit one the current one will be deleted and a new one added. I can
see this happening in the list of timer recordings.
The information that a recording was deleted and added is also shown at the
bottom. I use version 4.1-163

Andulien notifications@github.com schrieb am So., 7. Juni 2015 um
23:42 Uhr:

**Comment by Andulien** [comment]
Yep, seems to only happen in case of the Bug #150 so this bug here can be closed I think.
