### ISSUE TITLE
Editing a scheduled recording, deletes the Scheduled Recording after saving the change

### ISSUE THREAD

**Issue by Andulien** [rsiebert/TVHClient#138]
With Version 1.8.0 the option to edit a channel on a scheduled recording was removed. Therefore the Bug cannot be tested. In the previous version one could edit the recording, change the channel and then the recording gets deleted upon saving the change.

Robert - "The channel can't be edited for a recording. This was wrong on my side: See https://github.com/tvheadend/tvheadend/blob/master/src/htsp_server.c line 1549. There is no channel that can be set."

**Comment by rsiebert** [comment]
Still an issue with the latest 1.8.0? Some permission stuff that might be related has been changed in the tvheadend server. It works at least here with 4.1-113.

**Comment by Andulien** [comment]
Application crashes now every time when I click the edit button of a scheduled recording.

**Comment by rsiebert** [comment]
Found the issue, new version is coming...

Andulien notifications@github.com schrieb am Do., 4. Juni 2015 um
09:20 Uhr:

**Comment by Andulien** [comment]
As this affects more then just scheduled recording I opened up a new issue to discuss the crash issue:
https://github.com/rsiebert/TVHClient/issues/143

**Comment by rsiebert** [comment]
Ok, just uploaded new version to the beta test channel.

Andulien notifications@github.com schrieb am Do., 4. Juni 2015 um
09:48 Uhr:

**Comment by Andulien** [comment]
Ok, will test once available for download.

**Comment by Andulien** [comment]
Editing a Scheduled recording works now.

One more question, was it intentional that the option to edit the Channel was removed?

**Comment by rsiebert** [comment]
Yes this was intentional, there is no parameter channel that can be set
when updating the scheduled recording via the HTSP API.
See
http://tvheadend.org/projects/tvheadend/wiki/Htsp#updateDvrEntry-Added-in-version-5.
There is no channel that can be changed.

Andulien notifications@github.com schrieb am Do., 4. Juni 2015 um
12:26 Uhr:

**Comment by Andulien** [comment]
Gotcha. Issue can then be closed.
