### ISSUE TITLE
Application crash on Editing any type of recording

### ISSUE THREAD

**Issue by Andulien** [rsiebert/TVHClient#143]
With the newest Version, when clicking the Edit button on any type of recording the application immediately crashes. (Current, Times, Series Recording)

**Comment by Andulien** [comment]
Newest Version fixes Scheduled Recordings.

However the App still crashes when hitting the Edit button for a Timed Recording or Series recording.

**Comment by rsiebert** [comment]
I can't reproduce this here. Can you send a screenshot of the recording in the webinterface, so I can see which fields are set and might cause problems?

**Comment by Andulien** [comment]
I attached 3 Screenshots. 1 & 2 I've tried all of those, each time the app crashed.
Screenshot 3, this recording was setup like Der Bachelor originally, but the yellow marked fields were changed automatically after saving without changing anything.
I am suspecting that it might have to do something with the new time dialer, which does not allow for an Any Time option but that is just my guess.
![crash1](https://cloud.githubusercontent.com/assets/12703546/7985816/e37f1216-0ad3-11e5-80e3-e40b2d467ed4.JPG)
![crash2](https://cloud.githubusercontent.com/assets/12703546/7985815/e37e7f90-0ad3-11e5-9922-f854772619fc.JPG)
![crash3](https://cloud.githubusercontent.com/assets/12703546/7985819/e60efce4-0ad3-11e5-97f6-ee30a549ff48.JPG)

**Comment by Andulien** [comment]
So I think I narrowed it down to the error.
On Timed Recording the error seems to be if you don't have a channel selected, the App crashes. So either there needs to be a check or this error needs to be ignored. You are allowed on the Web interface to add a Timed Recording without a Channel set.

I just tested this on Series Recording and the error seems to also happen due to there being no channel. In addition to that it might also be related to the Any time. But for sure the channel topic.
I edit a working entry within the app, select Alle Sender, then save, then try to edit again and the app crashes.

**Comment by rsiebert** [comment]
Thanks for the information.I have uploaded a new version.
- when setting the start time for a series recording to 0:00 then Any time
  will be assumed.
- For timer recordings. A channel is mandatory according to the HTSP API.
  But when no channel is set in the webinterface, no channel will be shown in
  the app. But the app checks that a channel is selected before the edited
  timer recording will be saved.

Andulien notifications@github.com schrieb am Do., 4. Juni 2015 17:50:

**Comment by Andulien** [comment]
Editing does not crash the App anymore. Issue can be closed.
