### ISSUE TITLE
Series/Timed Recoding - All Channels fix

### ISSUE THREAD

**Issue by Andulien** [rsiebert/TVHClient#150]
When "Alle Sender" is set then it should also be set as that automatically when clicking the edit button.

Currently:
1. Setup a new Series / Timed recording with "Alle Sender"
2. Save.
3. Open up the series again and hit edit.
4. The Channel option is set back to "Kein Sender" - this should be "Alle Sender" as set before.

This is probably something that comes from the latest change.

**Comment by rsiebert** [comment]
I have changed the logic for the series recording.
But for timer recording setting all channels should not be possible by the webinterface. Or will it recording the defined show at the same time on all channels at once? This is not supported by the API and is probably a bug in the webinterface. I have filed a ticket http://tvheadend.org/issues/2924

**Comment by Andulien** [comment]
Ok, I will test the Series portion once available.

As for Timed Recordings, yes it should not be possible. However currently it is not being prevented that the Channel field is left empty. When editing this type of recording then in TVH, it properly asks for a channel to be set, and then deletes the recording without creating the new one. This happens only in this type of case. Else the Timed recording editing works fine.

**Comment by rsiebert** [comment]
I can reproduce this here. This seems to be an error in the server. When a
channel was previously set and I change it the edited recording shows up. I
see if I can create a workaround.

Andulien notifications@github.com schrieb am Mo., 8. Juni 2015 um
11:58 Uhr:

**Comment by Andulien** [comment]
New logic is working perfect.
