### ISSUE TITLE
Crash when selecting a channel for manual record entry

### ISSUE THREAD

**Issue by TobiasEckl** [rsiebert/TVHClient#152]
While adding a "manual" schedule entry (not via EPG) the app keeps crashing at channel selection

TVHClient v 1.8.0
Samsung Note 4 (SM-N910F)
Stock 5.0.1

No Problems on Samsung Galaxy S2 (GT-I9100)
Stock 4.1.2

**Comment by rsiebert** [comment]
Thanks for spotting this!
Fixed in https://github.com/rsiebert/TVHClient/commit/2d093b20ab50d51e89b8a52899dc8169e1f29a97
