### ISSUE TITLE
set recording profile in record dialog

### ISSUE THREAD

**Issue by nihilistaX** [rsiebert/TVHClient#159]
It would be pretty nice to have the possibility to set recording profile in record dialog.
I have some different profiles for recording to different folders, for example profile "sports" records to folder named "sports", so i don't have to search much and have my recordings well sorted on my server. Maybe its possible?

**Comment by rsiebert** [comment]
This is possible, but it will be added in a later version.

**Comment by rsiebert** [comment]
This will be added in the version 1.8.6

**Comment by nihilistaX** [comment]
Thx, great news!

**Comment by nihilistaX** [comment]
Tested it in beta 1.8.6, but its not really what i meant. Would it be possible to add something like dropdown menu to normal record dialog (not manual record)?
Now i have to set recording, goto recordings tab, edit that with setting profile...or set a manual recording (not very comfortable).
And i found that all recordings i set in web interface (if i try to edit) didn't show the right profile, all set to default profile(that profile selected in app settings). Just cosmetic as recordings has correct profiles on web interface and if i don't save them nothing would be changed.But seems that it is not loaded from server.
Thx anyway.

**Comment by nihilistaX** [comment]
Seems that editing profile in scheduled recording didn't work. After setting another profile, on server (and in recording setting) stays at the profile that set in app settings. Maybe thats new issue with latest tvh builds, i remember if i wrote last comment above it works.

**Comment by nihilistaX** [comment]
Ok, today an update arrives, but now there is no possibility to set recording profiles anymore. Only with manual recordings its possible, editing scheduled recordings shows no possibility to set profile.
I have the paid version, so that couldn't be the problem.

**Comment by ghost** [comment]
Now i update PL translation

**Comment by nihilistaX** [comment]
But would that help with access to recording profiles ;-) ?

**Comment by rsiebert** [comment]
Hi,

I tried editing the profile here in the edit recording screen, it didn't
change in the webinterface. I also checked the htsp API.
I also tried updating the profile in series or timer rec.  Did this work
for you? Then I can reactivate this.

Best regards
Robert

nihilistaX notifications@github.com schrieb am Mi., 13. Jan. 2016 um
13:05 Uhr:

**Comment by nihilistaX** [comment]
Ich versuche es mal ausnahmsweise auf deutsch ;-) 
In der Beta hatte ich es ausprobiert,ein nachträgliches Ändern des Profils wurde nicht auf den Server übertragen,seit der neuen version die heute automatisch installiert wurde kann ich das Profil wie gesagt nicht mehr auswählen. Schön wäre ja eine Profilauswahl direkt im Auswahlscreen bei Click auf "Aufnehmen" oder im Fenster als Dropdown-Menü o.ä. Gibt es denn eine neue Beta die ich noch nicht habe und die ich testen könnte?
Ich habe übrigens immer die neuesten unstable-builds von TVH auf dem Server,vielleicht hat sich ja da etwas geändert?  
Vielen dank,
Mfg
Nils

**Comment by rsiebert** [comment]
I have added a new menu to allow specifying a different profile before
adding a recording. It is available via long-press on an item in the
channel list or program list screen

nihilistaX notifications@github.com schrieb am Mi., 13. Jan. 2016 um
15:49 Uhr:

**Comment by nihilistaX** [comment]
OK, that works now, thx.

**Comment by rsiebert** [comment]
I have released the version 1.8.6 to the market.
