### ISSUE TITLE
Series - Set Any Time issue

### ISSUE THREAD

**Issue by Andulien** [rsiebert/TVHClient#162]
So the way Series Start/End Time is setup is that if it see's a Series with 'Any' / no time set, it will put it in as 00:00 in the App. 
However when creating a new Series in the App, trying to set the time to 00:00 or 'Any', does not work. The app automatically sets the Start After, Start Before time to 23:45 and 00:15 instead of 'Any'. see also the attached Screenshot. Also in the App options you only find StartTime and no EndTime (StartAfter, StartBefore)

![series-timeerror](https://cloud.githubusercontent.com/assets/12703546/8266557/70304c04-1734-11e5-880f-b642949fe516.JPG)

**Comment by rsiebert** [comment]
I ran also into this issue. I guess I need to add a separate checkbox or something to enable or disable setting a time.

**Comment by rsiebert** [comment]
The next version corrects that. I have added the stop time and also a checkbox to disable setting any time at all.

**Comment by rsiebert** [comment]
Added in https://github.com/rsiebert/TVHClient/commit/39f62973149551f0f8b38f26f056212469dc0fe4

**Comment by Andulien** [comment]
Perfect :) Seems to all work now. Just tested it.
