### ISSUE TITLE
Addition to f-droid.org

### ISSUE THREAD

**Issue by B5r1oJ0A9G** [rsiebert/TVHClient#163]
How about adding TVHClient to https://f-droid.org/ ?

**Comment by rsiebert** [comment]
If I add the version there then you can't get the extra features. Afaik it does not support google billing stuff.

**Comment by rsiebert** [comment]
I hope the answer is ok. :-)

**Comment by Mannshoch** [comment]
Workaround, replace the billing tool with a bitcoin address
