### ISSUE TITLE
MAC Address is not valid?

### ISSUE THREAD

**Issue by lwis** [rsiebert/TVHClient#164]
Hi,

Since the 1.8 update I'm seeing wol_address_invalid when I try to connect (I don't use the WOL functionality, so I don't have a MAC address set)

**Comment by rsiebert** [comment]
If a mac address was not provided in a connection, the menu to allow wake on lan should have been invisible. This was not the case. The next version corrects that.

**Comment by lwis** [comment]
Thanks Robert!
