### ISSUE TITLE
WOL in main menu?

### ISSUE THREAD

**Issue by mehldutt** [rsiebert/TVHClient#168]
Would be nice to wake my HTPC without having to enter settings/connections

**Comment by rsiebert** [comment]
This could be added to the menu in the status screen? When the server is sleeping the status screen but be shown first.

**Comment by mehldutt** [comment]
Or even an option for automatic WOL when TVHClient is started?

**Comment by mehldutt** [comment]
Status screen sounds like good place to add a WOL button.

**Comment by mehldutt** [comment]
Sounds good.

By the way: This is a wounderfull APP.

Thank you so much

Gary

Gesendet über Yahoo Mail für Android

Von:"Robert Siebert" notifications@github.com
Datum:So., 28. Juni 2015 um 22:28
Betreff:Re: [TVHClient] WOL in main menu? (#168)

This could be added to the menu in the status screen? When the server is sleeping the status screen but be shown first.

**Comment by rsiebert** [comment]
Added in 409ad025d684032e564ad3d6ca1f7cdb254c1b0e
