### ISSUE TITLE
Authenticate for stream

### ISSUE THREAD

**Issue by gkovacsp** [rsiebert/TVHClient#175]
It seems the TVHclient authenticates correctly to get the html interface, but it does not authenticate to receive the stream, it requires the server to have all access enabled for streams.

As a result it is impossible to tell from the tvheadend web interface who is playing the actual stream.

![client-missing](https://cloud.githubusercontent.com/assets/1654787/10096085/1cc584ee-636f-11e5-920c-a98094d4747f.png)

**Comment by gkovacsp** [comment]
When the stream is watched from VLC's tvheadend plugin the authentication is done properly and the stream's owner is shown.

![vlc](https://cloud.githubusercontent.com/assets/1654787/10096131/73b729e2-636f-11e5-8d5f-76cdc4741f35.png)

**Comment by rsiebert** [comment]
Added in c4609b20
