### ISSUE TITLE
Publish as Amazon FireTV App in Amazon Store

### ISSUE THREAD

**Issue by lrohrmann** [rsiebert/TVHClient#178]
Would it be possible to publish these app via Amazon Store to direct install it on the FireTV Box/Stick? This would be a great solution to bring Live TV to the Box. I think several people would buy this in the FireTv Store.

**Comment by rsiebert** [comment]
This is currently not intended. It would require implementing the billing SDK from amazon. I don't think there are so many users on this platform that would justify the effort.
