### ISSUE TITLE
Problem with EPG - show for wrong time

### ISSUE THREAD

**Issue by ghost** [rsiebert/TVHClient#193]
Hello Robert. From some time in past i have a problem with show correct EPG on time.
![screenshot_2015-12-17-21-11-41](https://cloud.githubusercontent.com/assets/4134018/11881304/33453146-a506-11e5-808b-fac0ceb64366.png)

Look on my screen. Current time is 21:11 but for some my channels like: TVN Siedem, TVN Style, TVN Turbo show me EPG data for about 14:00 hours. When i play this channel (example by VLC Player) and then stop stream , i have empty EPG. Then i click REFRESH in TVHClient and now EPG is correct and show info about 21:00 hours. 

On PC by web all is ok , and i use on my PC KODI and in KODI also all is ok and correct. Only problem is in TVHClient.

I reinstall my client and nothing changed.

Please help me.

**Comment by AlBundy33** [comment]
Same problem here. I'm running Tvheadend 4.1-1235~gd822a74~jessie. 
![screenshot_2015-12-22-19-21-30](https://cloud.githubusercontent.com/assets/6294586/11962750/8f97c1b8-a8e2-11e5-814f-b55afb9d32d0.png)

**Comment by ghost** [comment]
Hello Robert.
Are you veryfication this problem ?

**Comment by hansp01** [comment]
I have the same issue. running on 4.1-1227~gc1a0705

**Comment by ghost** [comment]
Robert pleas help us.

**Comment by rsiebert** [comment]
I have updated my tvheadend server version to the one from today (28.12.2015) and the EPG shows up fine. I guess this was some issue in the server. Please update your server and check if the issue remains.

**Comment by AlBundy33** [comment]
I'm already using the latest version (HTS Tvheadend 4.1-1257~g6975129~jessie) and still have the problem. 

After a restart of tvheadend server tvhclient shows the correct entries but some hours later they are out of sync. 

This is issue occurs only in all-channels-view - the epg-view seems to be fine.

**Comment by ghost** [comment]
I also has still this problem and i update my TVHeadend to version: HTS Tvheadend 4.1-1257~g6975129

**Comment by AlBundy33** [comment]
I think there is a problem while getting the time and/or epg data. 

For example current values for "Das Erste HD":
Tvheadend EPG-Overview: 
Sportschau live : Ski-Weltcup
Start Time: Montag28.12.201513:00:00
End Time: Montag28.12.201515:00:00
Duration: 120 min

TVHClient all channels:
Tatort: Benutzt 01:10 -  02:43

TVHClient epg:
No program information available 
That "correct" because details in all channels view showing
Tagesschau 04:43 - 04:45
as last entry. 

Sometimes TVHClient shows also a wrong channel count (5 instead of 1204).
It's just the displayed count - the list contains all channels.

**Comment by AlBundy33** [comment]
I've cleand cache and data of tvhclient and reco figured my connection. 
But tvhclient still shows the wrong entries. 

Is there a way to check the response of tvheadend?

**Comment by AlBundy33** [comment]
Tuning into a channel uodates the epg in tvhclient. 

I have two devices and both showed the same wrong dsts. 
E. G. Pro7 Iron Man 3 from this night. 
Then I've started the playback of this channel and now both devices showing How I met your mother as currently running program.

**Comment by rsiebert** [comment]
I have also encountered this issue now on my device. I'll look into this.

**Comment by AlBundy33** [comment]
Seems to work now.

**Comment by rsiebert** [comment]
Thanks for the information!
