### ISSUE TITLE
Feature-request: configurable select-behavior in all-channels-view

### ISSUE THREAD

**Issue by AlBundy33** [rsiebert/TVHClient#194]
Currently selecting an entry in all-channels-view opens the program for this channel. 

It would be nice to configure the behavior to decide between open programm and watch channel. 

Btw. watch channel is missing in the long-press-menu.

**Comment by rsiebert** [comment]
How can the list of programs be shown when the setting to play a channel is active?
The play menu is available when a channel is long pressed in the channel list view. Or do you mean a different screen?

**Comment by AlBundy33** [comment]
I just want an option to directly start the playback in all-channels-view. 
Maybe something like clicking on the channel name/logo starts the playback and clicking on the show selects the channel and displays all other shows. 

Al

Btw. merry-xmas. ;-)

**Comment by rsiebert** [comment]
I have added an option to start playback when the channel icon is clicked.

**Comment by ghost** [comment]
But when you will release new version and please correct problem with show
epg...

Pozdrawiam
Piotr Kuchciak

Wysłane z Samsung Galaxy S6
29 gru 2015 12:03 PM "Robert Siebert" notifications@github.com napisał(a):

**Comment by rsiebert** [comment]
New version has been released in the beta channel

**Comment by ghost** [comment]
Ok thanks. Please update my translation from PR

**Comment by AlBundy33** [comment]
What means beta-channel? 
Can you provide an apk?

**Comment by rsiebert** [comment]
If you are a member of the google+ tvhclient group then you should get the
beta versions of the app via the play store.

AlBundy33 notifications@github.com schrieb am Mi., 30. Dez. 2015 um
14:54 Uhr:

**Comment by AlBundy33** [comment]
Unfortunately I'm not (I don't use google+). 
Can you provide an apk for download?

**Comment by AlBundy33** [comment]
Or do you have an idea when the new version will be released?

**Comment by AlBundy33** [comment]
Clicking the icons is a little tricky. 

It would be nice to click somewhere in the left-area to start playback.

**Comment by AlBundy33** [comment]
And it seems that only the icons are working. 
Clicking on a channelname (channel has no logo) does not start playback.

**Comment by AlBundy33** [comment]
Recordings-view should have this feature too.

**Comment by rsiebert** [comment]
The newly released version 1.8.6 contains this in the channel and recording views.

**Comment by AlBundy33** [comment]
But clicking under the logo or clicking on the channel name (channels without logo) does not work.

**Comment by AlBundy33** [comment]
Push. ;-)
