### ISSUE TITLE
Feature-Request: Floating Window

### ISSUE THREAD

**Issue by Ragamuffin85** [rsiebert/TVHClient#195]
It would be great if the "Floating Window" feature - as used by youtube - would me made available.
So the currently tuned-in program will be shown minimized/floating in the lower right corner of the screen an the EPG/Config etc. is shown fullscreen in the background.

P.S. The appended Screenshot is used for complentness

![screenshot_2015-12-25-20-37-26](https://cloud.githubusercontent.com/assets/843933/12004222/fd9244a6-ab47-11e5-9958-1c36c70df5ee.png)

**Comment by rsiebert** [comment]
TVHClient uses an external player. Afaik the floating video window is only possible when an internal player is used which is currently not on the todo list.
