### ISSUE TITLE
Feature-Request: show future programs in all-channels-view 

### ISSUE THREAD

**Issue by AlBundy33** [rsiebert/TVHClient#198]
Currently all-channels-view shows the current running program. 

It would be nice to show future programs in list overview by changing the time. 
E.g. to show what's starting at 20:15

**Comment by rsiebert** [comment]
In the all channels view the next program is shown below the progress bar. It shows 'Next: <name of show>'. Did you activate this feature in the settings?

**Comment by AlBundy33** [comment]
Yes - I've activated the setting but I want to see the programs in future. 

Like the clock-Button or swiping right in epg-view.

**Comment by rsiebert** [comment]
Hmm, like a screen that shows what's running at prime time or at other times. I'll consider that.

**Comment by AlBundy33** [comment]
A thought more of an addition to the current all channels view to swipe through the time.
E.g. swiping to change the display time so that i can see the next shows.  And maybe an option to configure default times (now, prime time etc.).
