### ISSUE TITLE
A recently watched channel list would be nice... 

### ISSUE THREAD

**Issue by AlBundy33** [rsiebert/TVHClient#199]
... to switch between last used channels. 
The list should be quick accessible to switch fast between channels (maybe new icon in front or after the search-icon)..

An option to remove elements or clear the complete list would be nice too. 

Count of elements should be  configurable. 
Last watched channel should also be the first element in list.

**Comment by rsiebert** [comment]
I'll close this request. This feature will not be added. If more people request such a feature (you can ask this in G+) then I'll think about it again.
