### ISSUE TITLE
Is it possible to clear the search history? 

### ISSUE THREAD

**Issue by AlBundy33** [rsiebert/TVHClient#200]
Maybe this functions would be nice:
- swipe to remove elements from list
- option to clear complete list
- option to disable complete history

**Comment by rsiebert** [comment]
This feature is available in the settings -> advanced settings. Maybe I move this into the regular settings.

**Comment by AlBundy33** [comment]
Hidden feature. :-) 

But wiping out elements from the list would be really nice. 
Or at least a symbol after each entry to remove it.
