### ISSUE TITLE
Configurable displayed time

### ISSUE THREAD

**Issue by AlBundy33** [rsiebert/TVHClient#201]
All-channels-view view shows currently the total time of the current running program. 
It would be nice to choose between
- total time
- elapsed time
- remaining time

Maybe by click on the displayed time or by configuration.

**Comment by rsiebert** [comment]
Thanks for the suggestion. But I'll keep the total time so that users see how long a show is. The elapsed and remaining times can be derived from the progressbar.

**Comment by AlBundy33** [comment]
But if a show is already running I usually don't care about the total time - in this cases the remaning time is more helpful (at least in my oppinion) because I can see how long I have to wait for the next show.

I think the total time is more useful for shows not started yet.

**Comment by AlBundy33** [comment]
Push. ;-)
