### ISSUE TITLE
A brief documentation how to setup the build environment would be nice

### ISSUE THREAD

**Issue by AlBundy33** [rsiebert/TVHClient#204]
E. g.  what IDE and tools are needed, how to setup/import the project etc. 

Something like in this project: https://github.com/NineWorlds/serenity-android/blob/master/README.md

**Comment by benkibbey** [comment]
I agree. Using Eclipse for TVHCllient with gradle build requirements for dependencies makes things especially difficult.

**Comment by rsiebert** [comment]
I have added some information hwo to install and build the project. Please inform me if there are gaps or incorrect information.
