### ISSUE TITLE
Download of recordings not working

### ISSUE THREAD

**Issue by hannesHuebi** [rsiebert/TVHClient#211]
I purchased the option to download full recordings to the android device. The download starts and then disapears after a second. Are there any dependencies i need to install in addition or isthis a bug?

If there is a need for a log file. i can upload attach that, but i don't know where to look for that.

Wit best regards,

**Comment by rsiebert** [comment]
The download function uses the android internal download functionality. Each android device provides an app called download or similar. Can you check if the download is visible there?

**Comment by hannesHuebi** [comment]
Yes it is visible there. It says insufficient space left. the recording itself is about 1gb. i have left about 5gb. if i download them from the webfrontend i can download them. i will test if this problems also occures for smaller recordings tomorrow.

is there a way to choose a diffrent downloadmanager like the firefix or chrome downloadmanager?

**Comment by rsiebert** [comment]
Any news on the download issue? Does the download app show any stuff?

**Comment by hannesHuebi** [comment]
No. Although I have freed up a lot of disk space and tried to download a small file it was not working. I can download the file from the http webpage of the tvh server. But then it asks me which downloadmanager to choose of. In the Download-Manager application there is also no name of the file given.
![img_20160311_083849](https://cloud.githubusercontent.com/assets/12280308/13696446/b66c40bc-e766-11e5-934f-5837c92afb3d.JPG)

**Comment by rsiebert** [comment]
I have added a new version 1.9.0 to the beta channel. I have added the missing authentication to the download stuff. I hope it works now for you?

**Comment by hannesHuebi** [comment]
I have just tested the beta. Unfortunately it is not better. The problem is still there. Is there maybe a problem with any rights for writing on the sd card or is there any other configuration which i have missed. I am using the app on a lonovo a7600-f tablet.

**Comment by hannesHuebi** [comment]
I have just looked up the rights of the app. As far as i can see the app has no rights for writing reading or modifying content of thesd card.
![screenshot_2016-03-13-21-37-14](https://cloud.githubusercontent.com/assets/12280308/13731217/0f79d40e-e964-11e5-811c-d3eb1b8dc6aa.png)
I am not familiar with the android sdk but maybe adding "android.permission.WRITE_EXTERNAL_STORAGE" in the AndroidManifest.xml would solve the issue

**Comment by rsiebert** [comment]
I have added a new version in the beta channel. It allows downloading to the external storage. Please check if this works for you. I have tested it on the emulator and it was successfully downloading a recording.

**Comment by hannesHuebi** [comment]
Thanks. I have tested the new Beta. At first it was not working. But i tried to unset the settingsoption download to external drive. The same problem occured again. Then I set the option to true again and then it worked. I don't know why the application doesn't recognize the settings at first. But now it works. Many thanks for the help and the patches.

With best regards,

Hannes
