### ISSUE TITLE
Chromecast support

### ISSUE THREAD

**Issue by ghost** [rsiebert/TVHClient#217]
Hi 

I have created an android app for streaming tv from my tvheadend server to my chromecast using Googles reference app. It works very good. But its primitive, I can only change channels. 

I would be very nice to have that feature in TVHCLIENT. Can we expect chromecast support in the for tvheadend in the future?

I used this profile: /stream/channel/uid?profile=webtv-vp8-vorbis-webm , It was the only profile who worked. 

Thanks Anders

**Comment by rsiebert** [comment]
I plan to add this in the future. I only have a RPi as a server, so testing this is very limited. Can you share the code of the app? Did your app use Google CastCompanionLibrary?

**Comment by ghost** [comment]
Send me a private message to aglarsson@gmail.com, then I can give you an url to my tvheadend server, for testing. Just a random channel.  I have a fast fiber connection, and with transcoding it is not mush data. Yes, I did use "CastCompanionLibrary",  and the reference player "CastVideos-android".  I have not checked in my code, sorry. CastVideos uses a rest service to load urls for casting. I only replaced this rest server with a simple php script who reads from my tvheadend server and som miner look and feel. Then my channels popt up in the CastVideo App.

**Comment by rsiebert** [comment]
Here are the commits for the chromecast support.

**Comment by ghost** [comment]
Hi Robert

Nice Job, I hope It will be worth it and many people will buy your app. I
did :)  I tryed the app you attached in this mail but there was no
chromecast Icon. I activated the cast support in settings, but no icon. I
will try to reinstall the app. Maybe then.

Thanks again!

// Anders

2016-03-13 20:36 GMT+01:00 Robert Siebert notifications@github.com:

> Closed #217 https://github.com/rsiebert/TVHClient/issues/217.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/rsiebert/TVHClient/issues/217#event-587938095.

## 

Vänligen Anders Larsson

**Comment by rsiebert** [comment]
Hi Anders,

Is the app unlocked? Using the emulator (with an unlocked app) and
connecting to your server I can see the cast icon.
Maybe sending a debug log to me shows some infos.

Best regards
Robert

Anders Larsson notifications@github.com schrieb am So., 13. März 2016 um
20:43 Uhr:

**Comment by ghost** [comment]
Hi 

It works now, pairing took some time. 

Thanks 
// Anders

**Comment by ghost** [comment]
Hi Robert

I had an Ide about the casting part.

It would be nice to have a zapping view, where you easily could change
channel then you cast to the TV. Like a remote control.  What do you think
about that? Is it out of your plan for TVHCLIENT?

Did you create a fork on the Castapp?  mayby I can try something.

I also saw that I could cast recordings, I struggled with that for a long
time in my TVCast App, I did not got it to work.  Super nice!

// Anders

2016-03-13 21:20 GMT+01:00 Robert Siebert notifications@github.com:

> Hi Anders,
> 
> Is the app unlocked? Using the emulator (with an unlocked app) and
> connecting to your server I can see the cast icon.
> Maybe sending a debug log to me shows some infos.
> 
> Best regards
> Robert
> 
> Anders Larsson notifications@github.com schrieb am So., 13. März 2016 um
> 20:43 Uhr:
> 
> > Hi Robert
> > 
> > Nice Job, I hope It will be worth it and many people will buy your app. I
> > did :) I tryed the app you attached in this mail but there was no
> > chromecast Icon. I activated the cast support in settings, but no icon. I
> > will try to reinstall the app. Maybe then.
> > 
> > Thanks again!
> > 
> > // Anders
> > 
> > 2016-03-13 20:36 GMT+01:00 Robert Siebert notifications@github.com:
> > 
> > > Closed #217 https://github.com/rsiebert/TVHClient/issues/217.
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > https://github.com/rsiebert/TVHClient/issues/217#event-587938095.
> > 
> > ## 
> > 
> > Vänligen Anders Larsson
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/rsiebert/TVHClient/issues/217#issuecomment-196033566
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/rsiebert/TVHClient/issues/217#issuecomment-196046121.

## 

Vänligen Anders Larsson
