### ISSUE TITLE
Problem with download file recording

### ISSUE THREAD

**Issue by ghost** [rsiebert/TVHClient#222]
Hi
I found bug after latest beta update with improve/fix download file recording. I use my Samsung Galaxy S6 and this model dont have a slot card microsd (external memory). Only have internal memory. But when i run app i have available option to select download to external memory. Maybe you can implement option to your app to reconized that android device has or not external memory. When dont have external memory option in app should be hidden. Because when my phone dont have external memory but i check it in app and when try download i have a crash app and close app.

**Comment by rsiebert** [comment]
I'll add this to the app.

**Comment by ghost** [comment]
ok when realeased beta version ? to i can test it...

**Comment by rsiebert** [comment]
Does it work for you with the newest version?

**Comment by ghost** [comment]
No still not working. WHen option is select and i try download file , app crashes.

I think that option to check should be hide in devices without external memory or without installed external memory. In my Samsung Galaxy S6 this option is still show... and i can check it.

**Comment by ghost** [comment]
![screenshot_20160321-042809](https://cloud.githubusercontent.com/assets/16692223/13911974/0ba72c44-ef38-11e5-837e-58d862c8a7e7.png)
![screenshot_20160321-042130](https://cloud.githubusercontent.com/assets/16692223/13911975/0e8f39ba-ef38-11e5-803b-de1b111e7131.png)

It is for Samsung Galaxy S6 which has no external SD card slot.

**Comment by rsiebert** [comment]
Did you try the version I send you yesterday per mail? And please send the crash report to me. Just click rapport in the dialog.

**Comment by ghost** [comment]
Yes i test you version which you send me. I send you crash raport yesterday... because on your version i have no button raport.

**Comment by rsiebert** [comment]
Reported as woring per mail.
