### ISSUE TITLE
Feature request: search recordings (like search EPG)

### ISSUE THREAD

**Issue by thomazz-nl** [rsiebert/TVHClient#225]
Hi there,

I was under the impression the full version would have this, but to my surprise it hasn't yet. Perhaps it can be added to a future version?

Any Tvheadend user with a more serious amount of recordings will encounter the issue of endless scrolling, looking for that one title to play. I think search by program title would suffice.

Thanks for taking it in consideration.

Kind regards,

Thomas

**Comment by rsiebert** [comment]
Added in https://github.com/rsiebert/TVHClient/commit/e9e26d86d0ddfcbec4e6ca45a9e848518f5d2268
