### ISSUE TITLE
Feature request: limit epg search by selected channel

### ISSUE THREAD

**Issue by thomazz-nl** [rsiebert/TVHClient#227]
When a certain channel is selected in the "channels" view, the programs for that channel are listed. When performing an epg search from that view, only results for the selected channel should be listed. Right now it performs a global EPG search across all channels just like in other views.

**Comment by rsiebert** [comment]
This feature is already available when using a smartphone. I guess you are using a tablet? In this case on the left a channel is always selected and on the right the programs are listed for that channel.
The question is then where can a user make a search over all channels? Shall he always go to the EPG screen?

**Comment by thomazz-nl** [comment]
Hi Robert, thanks for your response. I'm actually on a smartphone (Nexus 5), however in landscape mode (if that makes any difference).

I've just checked again, but to no avail. Either I'm missing your point or the other way around :p. I'll try to provide a step based example:
1. Tap "hamburger".
2. Tap "channels" (channels are listed with the current running program beside it).
3. If I tap the magnifying glass on the current view and enter a search-phrase, it will yield EPG results from all channels (as expected/desired).
4. Tap current running program (for example Discovery's Gold Rush). All upcoming shows on Discovery Channel are listed.
5. If I tap the magnifying glass on the current view and enter a search-phrase (for example "news"), it will yield EPG results from all channels (BBC News at One/CNN Newsroom etc.). This is not desired/expected, here is where I expect to only see programs from Discovery Channel with the word "news" in it (not expecting any results for that, but you get the point :p).

If there's any other way to achieve what I'm trying to do I'm happy to hear from you.

**Comment by rsiebert** [comment]
Thanks for the info! I have found the issue. The stuff is working for older android versions. Since android 4 the search stuff is a bit different and there I missed adding the logic to search a single channel only.

**Comment by thomazz-nl** [comment]
Good job finding the problem! It must be cumbersome to develop the project while keeping compatibility with legacy OS versions. Thanks in advance and good luck!

**Comment by rsiebert** [comment]
Added in https://github.com/rsiebert/TVHClient/commit/e9e26d86d0ddfcbec4e6ca45a9e848518f5d2268
