### ISSUE TITLE
Play downloaded recordings from app

### ISSUE THREAD

**Issue by rsiebert** [rsiebert/TVHClient#228]

**Comment by ghost** [comment]
Maybe also add option to play in live stream recordings file in app ?

**Comment by rsiebert** [comment]
Can you explain that more? I don't understand this sentence.

**Comment by ghost** [comment]
To play recorded file in app tvhclient.
02.04.2016 09:11 "Robert Siebert" notifications@github.com napisał(a):

**Comment by rsiebert** [comment]
No, I will not develop another video player when there are dozens available
like vlc or mxplayer.

An external player will also be used to play downloaded recordings

**Comment by rsiebert** [comment]
Added in 9fb0e39e
