### ISSUE TITLE
Casting - no stream and no new session in server logs

### ISSUE THREAD

**Issue by howels** [rsiebert/TVHClient#229]
[tvhclient_10.04.2016.log.txt](https://github.com/rsiebert/TVHClient/files/211743/tvhclient_10.04.2016.log.txt)

Hi,

I just bought the app cos chromecast would be cool (either that or an Android TV version!).

However, despite seeing the relevant 'webtv-vp8-vorbis-webm' streaming profile on the TVH installation I can't seem to get the stream sent to the chromecast reciever.

I have opened the 'watch TV' window on the admin UI and this stream type is playing ok, but when using the TVHclient app with Google Cast I don't seem to see any stream clients connecting to the server?

Any tips on how to troubleshoot this? Logcat to follow soon...

thanks
Stephen

**Comment by rsiebert** [comment]
The app can't load the required channel information from the web API. The error is "ExternalActionActivity, Error parsing JSON data". As written per mail, please try the new 1.9.1 beta version and report back.

**Comment by howels** [comment]
The new 1.9.1 beta does not fix the issue, the channel loading info is shown on the cast receiver but then the display flips back to showing "TVHclient"

> 11.04.2016 17:04:48: TVHClientApplication, Log started
> 11.04.2016 17:04:48: TVHClientApplication, Application version: 1.9.1 (81)
> 11.04.2016 17:04:48: TVHClientApplication, Android version: 6.0.1(23)
> 11.04.2016 17:04:48: HTSService, Connect to server requested
> 11.04.2016 17:04:48: HTSService, Starting to connect to server
> 11.04.2016 17:04:48: HTSConnection, Connecting to server
> 11.04.2016 17:04:48: HTSConnection, Starting connection thread
> 11.04.2016 17:04:48: HTSConnection, Starting initial async
> 11.04.2016 17:04:48: HTSConnection, Server name 'Tvheadend', version '4.1-1724~g41707e1~trusty', protocol '25'
> 11.04.2016 17:04:48: HTSConnection, User user authenticated true
> 11.04.2016 17:04:48: HTSService, initial sync completed
> 11.04.2016 17:04:48: HTSService, Can't load channel icon, Remote file is missing
> 11.04.2016 17:04:48: HTSService, Can't load channel icon, Remote file is missing
> 11.04.2016 17:04:48: HTSService, Can't load channel icon, Remote file is missing
> 11.04.2016 17:04:48: HTSService, Can't load channel icon, Remote file is missing
> 11.04.2016 17:04:48: HTSService, Can't load channel icon, Remote file is missing
> 11.04.2016 17:04:48: HTSService, Can't load channel icon, Remote file is missing
> 11.04.2016 17:04:48: HTSService, Can't load channel icon, Remote file is missing
> 11.04.2016 17:04:48: HTSService, Can't load channel icon, Remote file is missing
> 11.04.2016 17:04:48: HTSService, Can't load channel icon, Remote file is missing
> 11.04.2016 17:04:49: HTSService, Can't load channel icon, Remote file is missing
> 11.04.2016 17:04:49: HTSService, Can't load channel icon, Remote file is missing
> 11.04.2016 17:04:49: HTSService, Can't load channel icon, Remote file is missing
> 11.04.2016 17:04:49: HTSService, Can't load channel icon, Remote file is missing
> 11.04.2016 17:04:49: HTSService, Can't load channel icon, Remote file is missing
> 11.04.2016 17:04:49: HTSService, Can't load channel icon, Remote file is missing
> 11.04.2016 17:04:49: HTSService, Can't load channel icon, Remote file is missing
> 11.04.2016 17:04:49: HTSService, Can't load channel icon, Remote file is missing
> 11.04.2016 17:04:49: HTSService, Can't load channel icon, Remote file is missing
> 11.04.2016 17:04:49: HTSService, Can't load channel icon, Remote file is missing
> 11.04.2016 17:04:49: MainActivity, CastConsumer onCastAvailabilityChanged, is present true
> 11.04.2016 17:04:50: ProgramListFragment, Scrolling, first item 0, visible items 0, total item 15
> 11.04.2016 17:04:50: ProgramListFragment, Scrolling, first item 0, visible items 4, total item 15
> 11.04.2016 17:05:08: HTSService, Connect to server requested
> 11.04.2016 17:05:15: MainActivity, CastConsumer onApplicationConnected
> 11.04.2016 17:05:15: MainActivity, Selected casting profile is webtv-vp8-vorbis-webm
> 11.04.2016 17:05:20: ProgramListFragment, Scrolling, first item 0, visible items 0, total item 15
> 11.04.2016 17:05:20: ProgramListFragment, Scrolling, first item 0, visible items 4, total item 15
> 11.04.2016 17:05:22: ProgramListFragment, Scrolling, first item 0, visible items 4, total item 15
> 11.04.2016 17:05:23: ExternalActionActivity, Starting to cast channel 'BBC TWO'
> 11.04.2016 17:05:23: ExternalActionActivity, Channel uuid missing, starting loading thread
> 11.04.2016 17:05:23: ExternalActionActivity, ChannelUuidLoaderTask, Connecting to http://192.168.0.200:9981/api/channel/grid?limit=106
> 11.04.2016 17:05:24: ExternalActionActivity, ChannelUuidLoaderTask, JSON data size is 43316
> 11.04.2016 17:05:24: ExternalActionActivity, ChannelUuidLoaderTask, Parsing JSON data
> 11.04.2016 17:05:24: ExternalActionActivity, ChannelUuidLoaderTask, Channel 'BBC TWO' found, uuid is bca32590acdcbb921a7fc1a8907cbffe
> 11.04.2016 17:05:24: ExternalActionActivity, ChannelUuidLoaderTask, Found uuid, starting to cast channel BBC TWO
> 11.04.2016 17:05:24: ExternalActionActivity, Casting starts with the following information:
> 11.04.2016 17:05:24: ExternalActionActivity, Cast title is BBC TWO
> 11.04.2016 17:05:24: ExternalActionActivity, Cast subtitle is 
> 11.04.2016 17:05:24: ExternalActionActivity, Cast icon is http://administrator:password@192.168.0.200:9981/imagecache/42
> 11.04.2016 17:05:24: ExternalActionActivity, Cast url is http://administrator:password@192.168.0.200:9981/stream/channel/bca32590acdcbb921a7fc1a8907cbffe?profile=webtv-vp8-vorbis-webm
> 11.04.2016 17:05:52: ProgramListFragment, Scrolling, first item 0, visible items 4, total item 30
> 11.04.2016 17:05:53: ProgramListFragment, Scrolling, first item 0, visible items 4, total item 30
> 11.04.2016 17:05:53: HTSService, Connect to server requested
> 11.04.2016 17:06:00: MainActivity, CastConsumer onDisconnected

**Comment by rsiebert** [comment]
The casting url is correct. Maybe the profile settings are not correct so that the chromecast can't play the url. Can you check the settings? They should look like [in this picture](https://lh3.googleusercontent.com/-tFgzkqD-1VY/Vwa3jjLSswI/AAAAAAAAB9U/QRakpo6dkgESuFMVTZPjhLKWfkbB76ZWw/w663-h608-p-rw/tvhe.png)

**Comment by howels** [comment]
My settings were defaulting to VP8/Vorbis instead of x264/AAC, which seems correct given that this is a Google product and the container is WebM? Anyhow, the result is the same whether using VP8/vorbis or x264/AAC in webM containers- both fail to playback on the Nexus Player.

I can play both streams in VLC using the URL from the logs, so I guess it's the Nexus Player being fussy. :-(  I'll see if I can try casting the URL with another method and get more info.

Edit, I've verified that my profile settings match https://developers.google.com/cast/docs/media#media-container-formats being a WebM container format with VP8 and Vorbis =< 720p

**Comment by rsiebert** [comment]
Thanks for the information. Please keep me informed if it is working.
Any chance to update your playstore rating? :-)

howels notifications@github.com schrieb am Mi., 13. Apr. 2016 um
17:40 Uhr:

**Comment by howels** [comment]
Updated the review, you've been very helpful so far.  Is there any feedback from the Cast receiver or is it a fire-and-forget mechanism? I've used this Cast receiver with BBC iPlayer so I know that it works with some streams, but I can't figure out what is failing! Is there a way I can fire URLs to the chromecast from  the command line to see what happens? I have a laptop with linux installed.

**Comment by rsiebert** [comment]
According to the documentation from the [google cast library](https://github.com/googlecast/CastCompanionLibrary-android) the cast screen should stay active. So you should see the black screen with the title and pause/stop button at the bottom. If you press back then  the usual tvhclient app should show with some mini controls at the bottom.

You can check if the [chrome cast app](https://github.com/googlecast/CastVideos-chrome) accepts custom urls.

**Comment by rsiebert** [comment]
Any news on this issue?

**Comment by howels** [comment]
No success on the nexus player using 1.9.2(84) although my Sony TV can
receive the stream the nexus player seems to buffer, then fail. I have yet
to see a single frame from tvheadend on the nexus player. I'm running stock
marshmallow with the latest updates but thinking that life might be simpler
if I just installed a chromecast instead.
If there's a way to install the app on the nexus player itself that would
be a workaround, as I dare say that using vlc as a player would eliminate
any chance of codec incompatibility. However I cannot speak as to the
difficulty of mapping controls to use a d-pad instead of touch.
On 17 May 2016 11:42 a.m., "Robert Siebert" notifications@github.com
wrote:

Any news on this issue?

**Comment by rsiebert** [comment]
So I assume right that I can close this issue?

**Comment by howels** [comment]
Unfortunately yes, there is nothing to be done unless you can access a
nexus player.

**Comment by rsiebert** [comment]
Unfortunately I don't have a nexus player.
