### ISSUE TITLE
Add duplicate handling

### ISSUE THREAD

**Issue by AlBundy33** [rsiebert/TVHClient#236]
To avoid duplicate recordings tvheadend seems to offer some settings. 
See http://docs.tvheadend.org/webui/dvr_autorec/

Al

**Comment by rsiebert** [comment]
See [HTSP API](https://tvheadend.org/projects/tvheadend/wiki/Htsp/158) for addAutorecEntry and autorecEntryAdd

optional field dupDetect (Added in version 20)
0 = all
1 = diff episode
2 = diff subtitle
3 = diff description 
4 = once per week 
5 = once per day

**Comment by rsiebert** [comment]
First version added in the commit from 620c6abb to 178918a5

**Comment by AlBundy33** [comment]
According to UI there are more options (all and local).

**Comment by rsiebert** [comment]
Added in 4f914ae0

**Comment by AlBundy33** [comment]
Maybe also mark a planned recording  as rerun (It's also shown in tvheadend).

**Comment by rsiebert** [comment]
The HTSP API does not provide this information. At least I don't see that the sources. Example: https://github.com/tvheadend/tvheadend/blob/master/src/htsp_server.c#L964

**Comment by AlBundy33** [comment]
At least I found it here: https://github.com/tvheadend/tvheadend/blob/master/src/dvr/dvr_db.c
(search for rerun).

**Comment by rsiebert** [comment]
That is the internal stuff which is used by the webinterace and htsp API. The webinterface API support this, but not the htsp API. All htsp related stuff is in the htsp_server.c file.

**Comment by rsiebert** [comment]
Closing because the HTSP API does not support the mark as rerun.
