### ISSUE TITLE
Is it possible to start watching while recording? 

### ISSUE THREAD

**Issue by AlBundy33** [rsiebert/TVHClient#239]
It would be nice to watch a currently running recording from beginning.

**Comment by rsiebert** [comment]
That is possible. In the schedules recording screen you can start playing those recordings that are currently being recorded (rec icon visible)

**Comment by AlBundy33** [comment]
This seems to be an hidden feature. :-) 
In scheduled recordings there is no play button inthe upper menu (edit, stop, erc.). 
Start playback by clicking on the cannelicon does also not work. 

Only when I press long on the recording I get a menu with the option to start playback. :-) 

Maybe you can add the two missing options mentioned above.

**Comment by AlBundy33** [comment]
Additionally to the already mentioned features it would be nice to start playback of a running recording in channelview by clicking on the record-icon.

**Comment by AlBundy33** [comment]
Thank you :)

**Comment by rsiebert** [comment]
Added in 71ddb0a2
