### ISSUE TITLE
Show warning when disk runs out of space 

### ISSUE THREAD

**Issue by AlBundy33** [rsiebert/TVHClient#240]
To avoid problems with recordings. 

Limit should be configurable.

**Comment by rsiebert** [comment]
This is more a feature that should be put in the server. The app does not know how big a recording will be. Other than that this is not a core feature af the app and will cluter the options with stuff that only a very few people might need. Or do you mean downloading a recording to the android device?

**Comment by AlBundy33** [comment]
No -  I mean really the disk on the server. 
In tvhclient the status shows the free space. 
It would be nice to see an information after start of tvhclient if free space is less than x% or xMB.

**Comment by rsiebert** [comment]
Every user has a different understanding when disk space runs low. So there would be another setting that only a handful of users will use. And what would be the default setting? You could ask in the google group if someone is also interested in this.

**Comment by AlBundy33** [comment]
Then maybe 0 would be a good default (=disabled) - so every user can choose it's personal value. 
I've opend the request because I'm running tvheadend on a raspberry pi with a 32GB microSD card and with such a limited capacity the volume runs very fast out of space. 

Now I've attached an older 320GB USB HDD for recordings - this should be enough for some time but it would be nice to get an information in tvhclient if the disk runs out of space again. 

Do you get notification of closed issues? 
If not please have a look at #239

**Comment by rsiebert** [comment]
Nope no notifications on closed issues. But I've seen it anyway

**Comment by AlBundy33** [comment]
Good to know. But why is #239 still closed?  :-)

**Comment by rsiebert** [comment]
Closing this issue because the feature request will not be added.
As a note: I also run tvheadend on a raspberry pi. The pi is connected to a NAS with 3TB.
You could install a cronjob on the pi that sends you a mail if space is running low.
