### ISSUE TITLE
Make channel list more compact

### ISSUE THREAD

**Issue by AlBundy33** [rsiebert/TVHClient#242]
It would be nice to see more channels in channel list (see screenshot) 
Therefore following changes would be nice:
- make the gaps to the separator lines some pixels smaller
- instead of displaying time and duration in a separate line show one the value at the end of the line with the title
- because there is not enough space for time and duration it should show the time by default and switch to total time, past time and remaining time on click

Or move the total, past remaining time field below the channel logo and the start/end-time at the end of the row with the title. 
Currently the free space below the logo seems a little bit wasted. 

In my opinion the text "Danach" ist not really necessary. 

![screenshot_2016-06-09-23-41-48](https://cloud.githubusercontent.com/assets/6294586/15947503/15e73cc8-2e9c-11e6-8f38-03f1a9c35ad1.png)

**Comment by rsiebert** [comment]
I follow the material design guidelines. If you check https://material.google.com/components/lists.html#lists-specs and scroll down to the three line item with avatars example (almost at the end) you see the following specs:
- Primary text font: Roboto Regular 16sp
- Secondary text font: Roboto Regular 14sp
- Tile height: 88dp
- Left avatar padding: 16dp
- Left text padding: 72dp
- Text padding, top: 16dp
- Text padding, bottom: 20dp

So the gaps dimensions are ok I would say and no text or whatsoever shall be shown below the icons. 

Just some thoughts / questions regarding the time and duration. 
- What would be the benefit for the majority of users except seeing two more channels in the list?
- What shall be done if the title is very long, crop it to show the time? 
- Clicking to switch time/duration. Would the _majority of the users really need_ this feature? Is it intuitive without explanation? Shall the time/duration selection be saved when the app is closed?

**Comment by AlBundy33** [comment]
> What would be the benefit for the majority of users except seeing two more channels in the list?

Just a better overview of more channels. In my opinion it looks like there's a lot of wasted space. And only seeing 5 channels on a 10" display seems to be improvable. 

> What shall be done if the title is very long, crop it to show the time?

The same as in the current overview if a title is too long. 
Maybe move the times and duration at the end of the line with the channel name. 
Or remove the line with the channel name and show the channel name on top of the right pane.
Or merge the time/duration and line together?
20:00 -  20:15 =======------- 15 Min

> Clicking to switch time/duration. Would the majority of the users really need this feature? 

Because a lot of apps,  TVs and receivers displaying one of past/remaining/total time or allow to switch between the values there are should be enough users how want different values. 
I'd like to see the remaining time in most cases and sometimes the past time. 
I know that this is currently displayed in a bar but sometimes numbers are better to read especially if you have short and long shows in a view. 

> Is it intuitive without explanation? 

I think so because other apps support this too (e.g. MX Player) 
If users find this feature by accident I thing they'll figure out what the values mean. 

> Shall the time/duration selection be saved when the app is closed?

Yes.

**Comment by rsiebert** [comment]
Added (and currently untested) in https://github.com/rsiebert/TVHClient/commit/e072076e32466d12cea82e16a4b389b23041c87c.

**Comment by AlBundy33** [comment]
I can't find the new settings on my sony xperia z2 (10" tablet).

**Comment by rsiebert** [comment]
I reverted the commit because I was not satisfied with the look. Only the progress bar and the next program can be hidden. I add something later.
