### ISSUE TITLE
Android N: cannot connect to TVH server

### ISSUE THREAD

**Issue by ghost** [rsiebert/TVHClient#246]
The latest version of TVHeadend (1.9.3) running on Android N does no longer connect to the TVH Server, status says "Timed out while connecting to server".  The server is available on the network,
and I can open the webpage at port 9981 on the device itself just fine.
tcpdump on the server shows no incoming connections on ports 9981 or 9982.

**Comment by rsiebert** [comment]
Does the app have all the required permissions? Version 1.9.2 was able to connect to the server?

**Comment by ghost** [comment]
The only permission I can give is to access internal memory.
I remember 1.9.2 working fine on Android N (the last preview for the Nexus 9, no change with the newest N preview).
I usually run git-head versions of  TVHeadend; I've reverted the TVH server back to a git revision from first week of May, no change.

**Comment by ghost** [comment]
Do you have an apk of 1.9.2 somewhere for me to download and test maybe?

**Comment by ghost** [comment]
Alright, it's not TVClient related, but base Android seems to be unable to resolve the hostname of the server, if used by TVHClient (firefox and Chromoum still can resolve it for some reason). If I enter the IP address instead of the server name, it works again.
I'm closing this now since a workaround is available.

**Comment by ghost** [comment]
Here's the log, see the "no route to host" messages:

16.06.2016 11:19:02: TVHClientApplication, Log started
16.06.2016 11:19:02: TVHClientApplication, Application version: 1.9.3 (86)
16.06.2016 11:19:02: TVHClientApplication, Android version: N(24)
16.06.2016 11:19:13: HTSService, Connect to server requested
16.06.2016 11:19:13: HTSService, Starting to connect to server
16.06.2016 11:19:13: HTSConnection, Connecting to server
16.06.2016 11:19:13: HTSConnection, Starting connection thread
16.06.2016 11:19:13: HTSConnection, Can't read message, No route to host
16.06.2016 11:19:13: HTSConnection, Can't close connection, null
16.06.2016 11:19:18: HTSConnection, Timeout, connection still pending
16.06.2016 11:19:18: HTSConnection, Can't close connection, null
16.06.2016 11:19:18: HTSService, No connection to perform GET_DVR_CONFIG
16.06.2016 11:19:18: HTSService, No connection to perform GET_DISC_SPACE
16.06.2016 11:19:41: HTSService, Connect to server requested
16.06.2016 11:19:41: HTSService, Starting to connect to server
16.06.2016 11:19:41: HTSConnection, Connecting to server
16.06.2016 11:19:41: HTSConnection, Starting connection thread
16.06.2016 11:19:41: HTSConnection, Can't read message, No route to host
16.06.2016 11:19:41: HTSConnection, Can't close connection, null
16.06.2016 11:19:46: HTSConnection, Timeout, connection still pending
16.06.2016 11:19:46: HTSConnection, Can't close connection, null
16.06.2016 11:19:49: HTSService, Connect to server requested
16.06.2016 11:19:49: HTSService, Starting to connect to server
16.06.2016 11:19:49: HTSConnection, Connecting to server
16.06.2016 11:19:49: HTSConnection, Starting connection thread
16.06.2016 11:19:49: HTSConnection, Can't read message, No route to host
16.06.2016 11:19:49: HTSConnection, Can't close connection, null
16.06.2016 11:19:54: HTSConnection, Timeout, connection still pending
16.06.2016 11:19:54: HTSConnection, Can't close connection, null
16.06.2016 11:19:54: HTSService, No connection to perform GET_DVR_CONFIG
16.06.2016 11:19:54: HTSService, No connection to perform GET_DISC_SPACE
16.06.2016 11:22:18: HTSService, Connect to server requested
16.06.2016 11:22:18: HTSService, Starting to connect to server
16.06.2016 11:22:18: HTSConnection, Connecting to server
16.06.2016 11:22:18: HTSConnection, Starting connection thread
16.06.2016 11:22:19: HTSConnection, Can't read message, No route to host
16.06.2016 11:22:19: HTSConnection, Can't close connection, null
16.06.2016 11:22:23: HTSConnection, Timeout, connection still pending
16.06.2016 11:22:23: HTSConnection, Can't close connection, null
16.06.2016 11:22:23: HTSService, No connection to perform GET_DVR_CONFIG
16.06.2016 11:22:23: HTSService, No connection to perform GET_DISC_SPACE
16.06.2016 11:30:35: HTSService, Connect to server requested
16.06.2016 11:30:35: HTSService, Starting to connect to server
16.06.2016 11:30:35: HTSConnection, Connecting to server
16.06.2016 11:30:40: HTSConnection, Starting connection thread
16.06.2016 11:30:40: HTSConnection, Can't read message, No route to host
16.06.2016 11:30:40: HTSConnection, Can't close connection, null
16.06.2016 11:30:45: HTSConnection, Timeout, connection still pending
16.06.2016 11:30:45: HTSConnection, Can't close connection, null
16.06.2016 11:31:19: HTSService, Connect to server requested
16.06.2016 11:31:19: HTSService, Closing existing connection and clearing all data
16.06.2016 11:31:19: HTSConnection, Can't close connection, null
16.06.2016 11:31:19: HTSService, Starting to connect to server
16.06.2016 11:31:19: HTSConnection, Connecting to server
16.06.2016 11:31:19: HTSConnection, Starting connection thread
16.06.2016 11:31:19: HTSConnection, Can't read message, No route to host
16.06.2016 11:31:19: HTSConnection, Can't close connection, null
16.06.2016 11:31:19: HTSService, Connect to server requested
16.06.2016 11:31:19: HTSService, Starting to connect to server
16.06.2016 11:31:19: HTSConnection, Connecting to server
16.06.2016 11:31:19: HTSConnection, Starting connection thread
16.06.2016 11:31:19: HTSConnection, Can't read message, No route to host
16.06.2016 11:31:19: HTSConnection, Can't close connection, null
16.06.2016 11:31:24: HTSConnection, Timeout, connection still pending
16.06.2016 11:31:24: HTSConnection, Can't close connection, null
16.06.2016 11:31:24: HTSService, No connection to perform GET_DVR_CONFIG
16.06.2016 11:31:24: HTSService, No connection to perform GET_DISC_SPACE
16.06.2016 11:31:24: HTSConnection, Timeout, connection still pending
16.06.2016 11:31:24: HTSConnection, Can't close connection, null
16.06.2016 11:40:36: HTSService, Connect to server requested
16.06.2016 11:40:36: HTSService, Closing existing connection and clearing all data
16.06.2016 11:40:36: HTSConnection, Can't close connection, null
16.06.2016 11:40:36: HTSService, Starting to connect to server
16.06.2016 11:40:36: HTSConnection, Connecting to server
16.06.2016 11:40:37: HTSConnection, Starting connection thread
16.06.2016 11:40:37: HTSConnection, Can't read message, No route to host
16.06.2016 11:40:37: HTSConnection, Can't close connection, null
16.06.2016 11:40:42: HTSConnection, Timeout, connection still pending
16.06.2016 11:40:42: HTSConnection, Can't close connection, null
16.06.2016 11:40:42: HTSService, No connection to perform GET_DVR_CONFIG
16.06.2016 11:40:42: HTSService, No connection to perform GET_DISC_SPACE
16.06.2016 11:40:49: HTSService, Connect to server requested
16.06.2016 11:40:49: HTSService, Starting to connect to server
16.06.2016 11:40:49: HTSConnection, Connecting to server
16.06.2016 11:40:49: HTSConnection, Starting connection thread
16.06.2016 11:40:49: HTSConnection, Can't read message, No route to host
16.06.2016 11:40:49: HTSConnection, Can't close connection, null
16.06.2016 11:40:54: HTSConnection, Timeout, connection still pending
16.06.2016 11:40:54: HTSConnection, Can't close connection, null

**Comment by ghost** [comment]
Could this be an issue with IPv6 support in tvhclient?  My home router does offer ipv6 addresses to all clients in the local network, but nslookup returns completely bogus addresses.  Ping6 to the TVheadend server results in a bogus unreachable address, mirroring the error code in the log.  It seems that at least firefox, chrome and bubbleupnp then fall back to ipv4 which offers correct addresses.

**Comment by rsiebert** [comment]
Ipv6 is disabled in the app.

mlauss notifications@github.com schrieb am Fr., 17. Juni 2016, 09:58:

**Comment by ghost** [comment]
Hm strange then.  I have the same issue on a Nexus 5 with Android 6.0.1.  Using ip address
directly works, hostname doesn't.

**Comment by rsiebert** [comment]
Seems to be some network config issue on your side? I also have Android
6.0.1 and I can use hostnames or IP addresses. Both work.
Tvhclient uses some android classes to resolve hostnames to ip addresses.

mlauss notifications@github.com schrieb am Fr., 17. Juni 2016, 10:25:

**Comment by rsiebert** [comment]
Any news on this?

**Comment by ghost** [comment]
Sorry, no. The issue remains. And only TVHclient suffers, firefox, chrome, bubbleupnp, vlc all can resolve local hostnames and connect to them just fine.

I'll guess I'll just close this since I'm the only one affected by it.

**Comment by hurzl** [comment]
Sorry I had set the wrong port, not 9982

**Comment by rsiebert** [comment]
Hi,

The app does not use any location services, so this permission issue is not
related to tvhclient. These two permission things allow an app to access
approximate / fine locations. See
https://developer.android.com/reference/android/Manifest.permission.html

If a hostname is specified in the connection then some android internals
will try to resolve this to a hostname. See
https://developer.android.com/reference/java/net/InetSocketAddress.html#InetSocketAddress%28java.lang.String,%20int%29
Resolving the hostname works here on Android 6.0.1 on my devices.

Do you use any proxies or other stuff other then connecting directly via
WLAN to the internet via the default router?

Best regards
Robert

hurzl notifications@github.com schrieb am Di., 6. Sep. 2016 um 10:05 Uhr:
