### ISSUE TITLE
Group recorded episodes

### ISSUE THREAD

**Issue by AlBundy33** [rsiebert/TVHClient#252]
Is it possible to group done recordings by "recording profile"? 

For example: I have three episode recordings
- Doctor Who
- Scorpion
- Marvels Agents of Shield

All done recordings are ordered by recoding time. 
It would be nice to have a group for each series in done recordings to have a better overview. :-) 

Maybe an option to mark a recording as watched would be nice.

**Comment by ManOki** [comment]
There are directories (i.e. subdirectory for auto recording or recording profiles) which are also supported by [Kodi](
https://forum.kodi.tv/showthread.php?tid=293283) (and Yatse).

Would be nice if TVHClient also support them.

**Comment by rsiebert** [comment]
Sorry, no time for this
