### ISSUE TITLE
Option to select https for the streaming port

### ISSUE THREAD

**Issue by UrsLedermann** [rsiebert/TVHClient#253]
We have modified our TVHeadend to provide the streams over https. Unfortunatley, in TVHClient the url is fixed to http, so we can't use this client at the moment.
It would be nice if you could add an option on the settings page to choose https for the streaming port 9981, although the port doesn't need to be fixed to 443.
I've had a look at the code but I'm not a programmer. What I've seen, this mainly needs to be modified in the ExternalActionActivity.java lines 92, 159, 317, but there needs to be done additional work on the settings page (SettingsManageConnectionFragment.java, Connection.java, DatabaseHelper.java, preferences_add_connection.xml, (strings.xml)) and the UI.
I'm also looking at the code of TVHeadend server, but this looks more complex.
I hope, you accept this feature request, although tvheadend is not able to provide https streams out of the box.

**Comment by rsiebert** [comment]
Sounds interesting. But if you have modified your tvheadend version, can't you just create a patch or pull request?

**Comment by rsiebert** [comment]
If tvheadend is not able to provide https streams out of the box then I see no need to implement this feature right now. But patches are welcome.
