### ISSUE TITLE
Chromecast

### ISSUE THREAD

**Issue by mbw2001** [rsiebert/TVHClient#254]
Hey,

I can't seem to get ChromeCast streaming to work. I'm selecting the default "webtv-vp8-vorbis-webm" profile as the app suggests, but i just receive a "Failed to load media" error.

I dont't see any attempt to connect in the tvheadend log, so it seems to be failing before even attempting to connect to the tvheadend server.

Any ideas as to what might be wrong?

// Michael

**Comment by rsiebert** [comment]
You can enable debug log in the tvhclient app, start the casting procedure again and then send the log to me. You'll find the debig and mailing stuff in the settings -> advanced settings.
Some users reported that the default webtv-vp8-vorbis-webm doesn't work, did you try the settings according to [this picture](https://plus.google.com/photos/photo/110086400786728768007/6270901352525902594?icm=false&sqid=110795645894468189728&ssid=974c18f8-32e7-400e-9307-730fe781e4ec)?

**Comment by mbw2001** [comment]
I'll try to enable the debug log later today. However I can't see the picture you are linking.

**Comment by rsiebert** [comment]
See this image ![profile settings](https://cloud.githubusercontent.com/assets/1406960/16765142/a9d9fc72-4832-11e6-8490-34d843fe6c98.png)

**Comment by rsiebert** [comment]
Additional question, is the server strong enough to transcode the video in readtime? a raspberry will not do it.

**Comment by rsiebert** [comment]
Closing due to no feedback.
