### ISSUE TITLE
Add manual recording name and profile

### ISSUE THREAD

**Issue by virtualdj** [rsiebert/TVHClient#256]
Hi, is it possible to add/edit the name (and possibly also the profile) of a manual recording in TVHClient? 
This would be an useful feature to differentiate recording without using the TVHeadend web UI.

**Comment by rsiebert** [comment]
This is already possible. With the unlocked version of the app you can edit the title, name and the used profile of a manual recording. Only editing the name and details of a profile is not possible because the API does not support this.

**Comment by virtualdj** [comment]
I'm using the unlocked version of the app but I cannot edit the title/name/profile of a manual recording.
This is the screen I get:

![screenshot_2016-09-01-17-29-57](https://cloud.githubusercontent.com/assets/3251704/18173480/04dc70d2-706a-11e6-897f-5bf02daee94a.png)

The Server API version is 19.

**Comment by rsiebert** [comment]
I checked the code, you need at least server API 21 to support editing title, subtitle and descriptions in a recording. Please update your server.

**Comment by virtualdj** [comment]
OK, thanks!
I supposed so but as the web UI allowed me to change name I thought it would provide the same function via API, but that's not the case.
