### ISSUE TITLE
Program detail titles are truncated/ellipsized

### ISSUE THREAD

**Issue by hurzl** [rsiebert/TVHClient#257]
So you don't get the complete title anywhere?

**Comment by rsiebert** [comment]
Is the title also truncated in the webinterface?

**Comment by hurzl** [comment]
No, why should it?

**Comment by hurzl** [comment]
![screen](https://cloud.githubusercontent.com/assets/628746/18342793/d06d35a6-75b0-11e6-85e9-46db57fbdf24.png)
Problem is that the title is a Toolbar widget which is single line

in https://github.com/rsiebert/TVHClient/blob/develop/app/src/main/res/layout/program_details_layout.xml

**Comment by rsiebert** [comment]
Added in https://github.com/rsiebert/TVHClient/commit/fc746a4e550841b99c649cb207fd7c7c6a98e4d2 and https://github.com/rsiebert/TVHClient/commit/4b9d3f628d765b3d2197a9ba9410a99bfb0c7f3a
