### ISSUE TITLE
Linebreaks missing in program details 

### ISSUE THREAD

**Issue by hurzl** [rsiebert/TVHClient#258]
In description

**Comment by rsiebert** [comment]
Do you have an example screenshot?
The text for the program derails is taken from the server.

**Comment by hurzl** [comment]
there should be some line separating character?

![tvhscreen](https://cloud.githubusercontent.com/assets/628746/18314875/381fd02e-7515-11e6-86b5-3b4ff9146dd0.png)

**Comment by hurzl** [comment]
I must say it's the same in tvheadend's html interface

![scr](https://cloud.githubusercontent.com/assets/628746/18315047/d057b1a4-7515-11e6-8354-b06f77138ae4.png)

maybe something happens here: https://tvheadend.org/issues/3968

**Comment by rsiebert** [comment]
I'll close the issue because tvheadend and tvhclient is not the problem. Afaik the description is extracted from the tv signal. The provider sends the description like this.

**Comment by hurzl** [comment]
It can't be the signal, as vdr understands the line breaks.

**Comment by rsiebert** [comment]
Please open a ticket in the tvheadend bug tracker. The server should be able to split the strings correctly.
