### ISSUE TITLE
Scrollbars in TV program 

### ISSUE THREAD

**Issue by hurzl** [rsiebert/TVHClient#259]
I think the additional Scrollbar in the channel (left) column is not necessary and confusing

**Comment by rsiebert** [comment]
Screenshot please. I don't see any scrollbars on my tablet and smartphone. 
Also the app and android version would be nice

**Comment by hurzl** [comment]
2 scrollbars. 
cm13/android 6.0.1
same thing on a 5.1 phone and 5.1.1 tablet

on 5.1 it doesn't matter because they don't work as scrollbars anyway ;-}

![scrol](https://cloud.githubusercontent.com/assets/628746/18428632/587b24a0-78cf-11e6-9ec1-aba33ad1c4ce.png)

**Comment by rsiebert** [comment]
Interesting, I also have CM13 on a phone and a tablet with CM12.1. I don't see any permanent scrollbars on these devices and also not in the emulators. I see only scrollbars when I scroll, then they dissapear after a few seconds.

According to https://developer.android.com/reference/android/view/View.html#setVerticalScrollBarEnabled%28boolean%29 the scrollbar is not drawn by default.

**Comment by hurzl** [comment]
Of course they disappear

**Comment by rsiebert** [comment]
Removed the left scrollbar in https://github.com/rsiebert/TVHClient/commit/454639c8b1d56937d81d983055a7ac1a0e4b0b35
