### ISSUE TITLE
Station field has random genre background

### ISSUE THREAD

**Issue by hurzl** [rsiebert/TVHClient#260]
even if genre bg is set to off for station field.

**Comment by rsiebert** [comment]
Please add a screenshot. When genre colors are off I see only a white or black background.
Also the app and android version would be nice

**Comment by hurzl** [comment]
latest app from playstore, android 6.0.1 (cm13)

![col](https://cloud.githubusercontent.com/assets/628746/18428676/99ab029c-78cf-11e6-89f6-fc40d27780d4.png)

**Comment by rsiebert** [comment]
Fixed in https://github.com/rsiebert/TVHClient/commit/2184fc07a7be25e4ae64c575fff69d41d5c35be0 and https://github.com/rsiebert/TVHClient/commit/02a492ed27d06654469221aa198d1c5e34b410b8
