### ISSUE TITLE
Dialogue to choose download-location

### ISSUE THREAD

**Issue by Black-Fry** [rsiebert/TVHClient#262]
Hi there, would be a good idea to let the user choose the direction-folder where downloaded files shall be stored on the mobile device. While my internal storage runs out of disk-space, my external storage (sd-card) is totally free.
Unfortunately I cannot download recorded files from my tvh-server because I cannot ( / did not find the right place to) choose another download directory.

Besides, extra-ordinary good job! Michael

**Comment by rsiebert** [comment]
I need to check if Android 6 allows an app writing to the sd card. Additionally the location should be set in the settings instead of a dialog popping up everytime one wants to download a recording?

**Comment by Black-Fry** [comment]
Yeah, this is an either-/or-matter. Putting it into the app-settings comes along with the need to store app-data locally on the device. Well, storing login-data for the server connection makes that necessary anyway.
I guess, dealing with a central option "save downloaded files to:" could solve my issue best and should do for others as Well.

Am 13. September 2016 15:55:34 MESZ, schrieb Robert Siebert notifications@github.com:

> I need to check if Android 6 allows an app writing to the sd card.
> Additionally the location should be set in the settings instead of a
> dialog popping up everytime one wants to download a recording?
> 
> ## 
> 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/rsiebert/TVHClient/issues/262#issuecomment-246689006

## 

Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by rsiebert** [comment]
Added in https://github.com/rsiebert/TVHClient/commit/1cf1765dd02c038f537c9f9ae78bb67be9d9ef72 and other commits.
