### ISSUE TITLE
[Feature Request] Show artwork/poster (EPG image) in detailed programinfo

### ISSUE THREAD

**Issue by tunip** [rsiebert/TVHClient#264]
Show artwork/poster in detailed programinfo if you have a XMLTV source where <icon src> is available.

XMLTV example:
`
<programme start="20160726090000 +0200" stop="20160726090500 +0200" channel="Das Erste HD">
<title lang="de">Tagesschau</title>
<desc lang="de">Die beste Adresse um an tagesaktuelle Nachrichten und Information zu kommen. An 365 Tagen im Jahr rund um die Uhr aktualisiert bietet tagesschau.de die wichtigsten Nachrichten des Tages und zusätzliche Informationen in Text, Bild, Audio und Video, sowie umfassende Berichte und Hintergründe zu aktuellen Themen</desc>
<category lang="en">News/Currentaffairs</category>
<icon src="http://images.rtv.de/images/stories/EPG/large/5bdb302653eaa427faa8d0c296934817c0781afa.jpg" />
</programme>`

Tvheadend API example (after XMLTV import):
`
{"eventId":71,"episodeId":72,"channelName":"Das Erste HD","channelUuid":"92f1befd0643cc505d32f61d7df52f42","channelNumber":"1","channelIcon":"imagecache/220","start":1469534400,"stop":1469535000,"title":"Tagesschau","description":"Die beste Adresse um an tagesaktuelle Nachrichten und Information zu kommen. An 365 Tagen im Jahr rund um die Uhr aktualisiert bietet tagesschau.de die wichtigsten Nachrichten des Tages und zusätzliche Informationen in Text, Bild, Audio und Video, sowie umfassende Berichte und Hintergründe zu aktuellen Themen","widescreen":1,"image":"http://images.rtv.de/images/stories/EPG/large/5bdb302653eaa427faa8d0c296934817c0781afa.jpg","genre":[32],"nextEventId":73}
`

(https://tvheadend.org/issues/3108)

**Comment by rsiebert** [comment]
Interessant. :-)
The app uses the HTSP API. In https://tvheadend.org/projects/tvheadend/wiki/Htsp under eventAdd there seems to be an image flag. "URL to a still capture from the episode". I'll check this.

**Comment by rsiebert** [comment]
Added first version in https://github.com/rsiebert/TVHClient/commit/b17fc0c496b308ec9639eb64800ea434bdc05146

**Comment by tunip** [comment]
Tested a lot of evnets and all images are loaded :+1: 

![cebuz5y](https://cloud.githubusercontent.com/assets/11404472/19076378/d865b25e-8a48-11e6-84e3-0f8df06bb80c.jpg)

**Comment by rsiebert** [comment]
Reported as working. Available in the unlocked version and if enabled in the settings.
