### ISSUE TITLE
show status of subscribtions and connections

### ISSUE THREAD

**Issue by CWempe** [rsiebert/TVHClient#268]
It would be great if there was an option to show current connections and subscriptiuons inside the app.

Just like inside the WebIf.
Status | Subscribtions
Status | Connactioens

Being able to kill/remove a running connection would be awsome, too.

**Comment by cz172638** [comment]
i would extend this for stream status, it is usefull when dancing on roof to install new dish :)

**Comment by rsiebert** [comment]
I checked the htsp API (https://tvheadend.org/projects/tvheadend/wiki/Htsp). The server does not provide support for showing the status of other connections and subscriptions. Only the own subscription information is provided when active. If this is the case then a video is running or something similar and the status screen cant be seen.
