### ISSUE TITLE
Program table not staying up to date

### ISSUE THREAD

**Issue by hurzl** [rsiebert/TVHClient#272]
While the table is open it should update its time position

**Comment by rsiebert** [comment]
The red vertical line in the EPG is updating itself to avoid updating the entire view every minute. I'll check if I can update the view every x minutes.

**Comment by rsiebert** [comment]
Added in https://github.com/rsiebert/TVHClient/commit/f1eab35df6c0d61484deb5f53b6932f5b1c11457. The program guide screen will be refreshed every 15 minutes when the user is on the first screen.
