### ISSUE TITLE
Not enough search results shown

### ISSUE THREAD

**Issue by rsiebert** [rsiebert/TVHClient#277]
Reported by a user: "On TVH there are about 9000 entries, but clicking search goes only through about 470 and stops. Did try searching for few titles far in the EPG and indeed these could not be found (but are readily available in Web EPG search)."

**Comment by NotCommonUser** [comment]
Can confirm that with latest version of TVHClient (1.9.7 (94)) and tvheadend as of Dec 18 the issue exists.

**Comment by Juppstein** [comment]
Same problem here with tvhclient latest version on Android and tvheadend backend 4.0.8~trusty. Interesting thing happened to me several times: if you dont find something, scroll down manually to the show until it shows on screen. Then the next search will find that show and all iterations. Strange stuff.

**Comment by rsiebert** [comment]
To speed up the display of the search results only the cached data in the app was searched. This issue will be resolved in version 2.0.0 when all epg data is cached in a database.

**Comment by lwis** [comment]
I'm still having some issues around searching within the app where no results are shown, despite a full sync.
