### ISSUE TITLE
Support for android TV

### ISSUE THREAD

**Issue by jayllon** [rsiebert/TVHClient#278]
As I can read here https://developer.android.com/training/tv/tif/tvinput.html , android TV could see tvh contents as tv channels, making the integration into the systems much more interesting. Thanks!

**Comment by rsiebert** [comment]
I thought of adding android TV to the app but due to limited time and the lack of hardware I dropped the idea and focused on the core functionality. There is already a project out there (https://github.com/kiall/android-tvheadend).

**Comment by jayllon** [comment]
I'll give it a try.
Thank you!!

**Comment by rsiebert** [comment]
Closing because another project does the job fine.
