### ISSUE TITLE
Search for channel

### ISSUE THREAD

**Issue by AlBundy33** [rsiebert/TVHClient#279]
Currently the search seems to work only for programs. 
It would be nice to search for  channels by name.

**Comment by rsiebert** [comment]
What would be the desired soutput in the search result dialog?
Only list the channels that were found, so the search function works like a filter for the channel list screen?

**Comment by AlBundy33** [comment]
I think a list of the filtered channels (maybe with the currently running program) would be nice.

**Comment by rsiebert** [comment]
Channels can be searched now in the channel list.

**Comment by rsiebert** [comment]
When starting a search on the channel list in the 2.0.0 version the channel name, program title and subtitle are searched. I hope this is ok for now. I plan to add something like advanced search later on.
