### ISSUE TITLE
My tablet forgets the default player

### ISSUE THREAD

**Issue by AlBundy33** [rsiebert/TVHClient#280]
I'm using plex to to stream my videos and tvhclient to stream tv. 
If I start playing content in one app I'm asked to select the default player. 
In my case I choose mx player and use always for this content. 

After I switch back to the other app I get this questions again and set set the same answer the next time I switch the app I have too choose again. 

Long story short: I always have to select my default player when switching between plex and tvhclient. 

Is this an issue with tvhclient, plex, android or maybe just my tablet? 

Al

**Comment by rsiebert** [comment]
This looks like an tablet or android specific issue. The apps itself are not involved in this.
