### ISSUE TITLE
Casting to chromecast not working

### ISSUE THREAD

**Issue by Kledal** [rsiebert/TVHClient#282]
When I try to stream a channel to the chromecast it doesn't work.
Seems to be that the requests it makes are malformed.

See screenshot of server output:
![skaermbillede 2017-01-03 00 28 59](https://cloud.githubusercontent.com/assets/5391726/21597488/c1e7b7e4-d14b-11e6-91e1-63970b2710b8.png)

Could maybe be something in the PlayActivity.java file.

Sadly i just paid for the Chromecast support, but it doesn't work..

**Comment by rsiebert** [comment]
Maybe it is related to https://github.com/rsiebert/TVHClient/issues/276 where the webroot information is missing in the casting url.

**Comment by rsiebert** [comment]
This is related to #274. So I close this issue.
