### ISSUE TITLE
Add "Removed Recordings" into Menu

### ISSUE THREAD

**Issue by Andulien** [rsiebert/TVHClient#283]
TvHeadend has since some time a new Tab under Digital Video Recording named "Removed Recordings". Would be great if you can add this into the app menu at some point as this splits up better the deleted recordings between those who failed and those who have simply been deleted or moved to a different folder thus de-cluttering the folder a bit ;) 

I'm currently using TvHeadend 4.1.2389

Thanks and keep up the great work.

**Comment by Andulien** [comment]
![unbenannt](https://cloud.githubusercontent.com/assets/12703546/26193160/a1c920fa-3bb4-11e7-9367-5dd407cf1a9d.PNG)

Any News on this feature? I attached here a small screenshot to shortly show how its in TvHeadend 4.1.2437

**Comment by rsiebert** [comment]
I have split the failed and removed recordings into two separate menu items.
Added in 0af3c797 and 44481cc
