### ISSUE TITLE
Fire OS Sibling of TVHClient?

### ISSUE THREAD

**Issue by doe1097** [rsiebert/TVHClient#288]
Hi Robert!
I own two Amazon FireTVs and wonder if it's possible to adapt Your TVHClient and make it run with [FireOS](https://developer.amazon.com/android-fireos) (an Amazon fork of Android 5.1). So, the idea would be to use Your great work as the backbone and modify the GUI for use with AndroidTV.

At the moment I'm using Kodi to access the TVH server, but the Kodi-Team failed in case of the android version for 'Krypton' and it seems that there is no Android dev for future versions.

Looking forward to Your thoughts on this!

EDIT: Just as a small "_thinkpoint_" - maybe it would make sense to meet the [AndroidTV Design](https://developer.android.com/design/tv/index.html) requirements first and the adopt the App to [FireOS](https://developer.amazon.com/android-fireos). I'm sorry, that I'm not a Android dev and hence can't give better input yet :-/

**Comment by rsiebert** [comment]
There is an Android TV app out there (https://github.com/kiall/android-tvheadend). Does this work? I currently have no plans to add the Android TV design. The leanback design incudes a completely new set of UI elements. This would be a major rewrite of the UI part of the app.

**Comment by doe1097** [comment]
Hey Robert,
Thanks for your answer. I already got in touch with kiall, but his App makes use of the [Android TV Input Framework ](https://source.android.com/devices/tv/)and thus won't Support vanilla Android or any other Android based derivates.

**Comment by rsiebert** [comment]
Closing issue because a fire os sibling will not be created
