### ISSUE TITLE
EPG shouldn't go back to actual time after some seconds 

### ISSUE THREAD

**Issue by grothauu** [rsiebert/TVHClient#290]
If I scroll forward and look at an entry e.g. 3 days in future and I go back to EPG after a while tvhclient always jumps back to the actual day and  time. Then I have to scroll three days forward again to continue at the previous program entry. Would be nice if there was a separate button to jump back to actual date or alternative a setting for a variablr timeout before tvhc automatically jumps back to the actual to time.

**Comment by rsiebert** [comment]
Added in e9bf12a
