### ISSUE TITLE
Channel groups gone

### ISSUE THREAD

**Issue by alturismo** [rsiebert/TVHClient#291]
when switching to the dark theme the group choice is gone, completely gone (butten away),
only a complete reset (clear data) will bring the button back, only changing back to light theme doesnt help.
it stays in the last chosen channel group ...

client phone here, galaxy s7 on android 7.0

see attached screenshots

![screenshot_20170303-080511](https://cloud.githubusercontent.com/assets/8406490/23541561/8c18cb3c-ffe8-11e6-9d3b-b2db212cd490.png)
![screenshot_20170303-080335](https://cloud.githubusercontent.com/assets/8406490/23541562/8c2fdae8-ffe8-11e6-9e34-a6e01464369a.png)

**Comment by rsiebert** [comment]
I checked this on my devices. I only see the group choice menu in drop down list when I select the "three dot"menu item. This works in the light and dark theme. Is the menu entry available in the dropdown list?

**Comment by alturismo** [comment]
ohh yes it is, 3 dot, filter, then there are the groups ...

just not the main button but usable, thanks for the info.

**Comment by rsiebert** [comment]
Closing issue. The group menu item is in the drop down list behind the menu with the "three dots".
