### ISSUE TITLE
Show Subtitle for EPG entries

### ISSUE THREAD

**Issue by LoopinFool** [rsiebert/TVHClient#292]
Currently, both Scheduled and Completed recordings have an entry for the "Subtitle" field and even display it in the item previews.
However, all guide entries show the "Series information" field instead. This is both inconsistent and inconvenient.

This is all using Schedules Direct guide data in the USA.

Android Version 1.9.8 (95)

**Comment by rsiebert** [comment]
Subtitles are now used in the epg
