### ISSUE TITLE
Language support

### ISSUE THREAD

**Issue by tonypottera24** [rsiebert/TVHClient#295]
Sorry that i didn't find any place i can contribute my translation.

**Comment by rsiebert** [comment]
Which language do you want to support?
You can update any translation or add new ones.

You can translate the arrays.xml, strings.xml and plurals.xml from https://github.com/rsiebert/TVHClient/tree/develop/app/src/main/res/values into your languge and create a pull request or attach or mail them

**Comment by rsiebert** [comment]
Any news regarding the translations?

**Comment by rsiebert** [comment]
Closing due to missing feedback.
