### ISSUE TITLE
Accessing server from public IP address

### ISSUE THREAD

**Issue by greekislandlover** [rsiebert/TVHClient#300]
Using my android phone I can log on to my server by putting the local IP address, user name and password and all works OK. However, I'd like to be able to log on from outside my local network with cellular connection. I have set it up the same as local, but with my public IP address and wifi switched off to ensure cell connection. I get "Access denied" then "Can't connect to server". I really like the app so getting it to work outside my local network would be great! Thanks

OK - now working. I hadn't set up a firewall rule in my router.

**Comment by rsiebert** [comment]
Issue solved.
