### ISSUE TITLE
IPv6 support, Android N, dual stack server, Connection timeout

### ISSUE THREAD

**Issue by mark-royds** [rsiebert/TVHClient#304]
I see from another post that IPv6 is disabled in the app.

I have tvheadend running on a server with dual stack configuration (IPv4 and IPv6 addresses).  Both addresses are registered in DNS (A and AAAA RRs for tvh.domain.name)

I've just upgraded to a Galaxy S8 which has Android N and the TVHClient app will not connect to the server if I use the dns name (Status = Connection timeout).  If I use the IPv4 address the app connects fine.

Is it possible that the TVHClient app is doing a DNS lookup, getting the IPv6 address and then falling over because IPv6 support is not enabled?

Using he.net tools I can successfully ping6 the server.

**Comment by CWempe** [comment]
duplicate with https://github.com/rsiebert/TVHClient/issues/323 ?

**Comment by mark-royds** [comment]
Yes #323 is a the same issue.

**Comment by rsiebert** [comment]
Closing this issue due to duplicate of #323
