### ISSUE TITLE
Cannot use "Timeshift" function of tvheadend server using TVHClient on Android 6

### ISSUE THREAD

**Issue by matej86** [rsiebert/TVHClient#305]
I am not able to use the timeshift feature of the Tvheadend server using the TVHClient. It is very sad, since the timeshift feature is very useful: pause live tv show, fast rewind, fast forward, commercial skipping, etc...

Please, is it possible to make the client compatible with the timeshift feature of the server?

**Comment by AlBundy33** [comment]
+1

**Comment by rsiebert** [comment]
This requires adding an internal player to the app based in the exoplayer libraries. This is on the list for version 2.0.0 onwards.

**Comment by kmorrow429** [comment]
Hi. Just wondering if this has been implemented yet? I see the option in the settings to enable timeshift, but I can only pause. No rewind/fast forward.

**Comment by rsiebert** [comment]
This is not yet working except that the setting is present. This will be
added later.

Am Do., 7. Feb. 2019, 01:09 hat kmorrow429 <notifications@github.com>
geschrieben:

**Comment by paulsavo1** [comment]
Hi mate any update re this

**Comment by rsiebert** [comment]
No news from my side. I was busy porting the app to kotlin and fixing issues. But it's not forgotten.

**Comment by ctrlbrk42** [comment]
The timeshift option is present in settings but it is greyed out for me. Pixel 3XL, tvheadend 4.2, latest tvhclient

Server is configured with a 4gb ram timeshift setting in the GUI config

What am I doing wrong?

Thank you

**Comment by matej86** [comment]
Any news about the timeshift function? :) it would be grate to have it available

**Comment by rsiebert** [comment]
I have stopped developing the app. Only deprecation warnings or bumping the target api will be done.
