### ISSUE TITLE
Enhancement of Search function on EPG

### ISSUE THREAD

**Issue by fdstk** [rsiebert/TVHClient#308]
It would be great, if the search function in EPG does not only filter by the title of a TV program, but also provides an option to search for subtitles and/or descriptions.

This would allow to search for a specific movie genre in the EPG, which are often tagged as "Action", "Thriller", etc. in the subtitles.

**Comment by rsiebert** [comment]
Sorry no time

**Comment by rsiebert** [comment]
I have stopped developing the app. Only deprecation warnings or bumping the target api will be done.
