### ISSUE TITLE
Implement HTST streaming to allow for timeshifting

### ISSUE THREAD

**Issue by Benoire** [rsiebert/TVHClient#309]
HTST streaming is required for timeshifting.  Not sure if it is in the paid version but timeshifting is an integral part of a PVR system and having this available would be valuable for those implementing Android TV systems to replace Linux/Windows based HTPCs.

**Comment by AlBundy33** [comment]
+1

**Comment by xi784** [comment]
if it is helpful take a look on kialls android-htsp library, maybe you can work together.
[https://github.com/kiall/android-htsp](https://github.com/kiall/android-htsp)

greetings
