### ISSUE TITLE
Chromecast Support / Chromecast App

### ISSUE THREAD

**Issue by p0wl** [rsiebert/TVHClient#31]
Hi, thanks for your great App.

I would love to see Chromecast Support. I'm thinking about the following setup:

Raspberry PI as tvheadend server, ChromeCast as Streaming Client. 

As far as I've understand chromecast, you would an Android Device inbetween, because Chromecast Apps differ from Android Apps (its hard to find documentation about "pure" Chromecast Apps).

Would love to help, and I've found the https://github.com/rsiebert/TVHClient/pull/22#issuecomment-44158212 and https://github.com/1stsetup/TVHClient/tree/Cast of @1stsetup, but as I've never developed for Android, it might need some time till I can contribute some useful code.

So this is more of a feature request, instead of a valuable contribution :D

**Comment by rsiebert** [comment]
Did anyone have success getting tvheadend and chromecast running? When I use the CastHelloVideo example and load a custom url like http://server:9981/stream/channelid/647796853?ticket=...&profile=webtv-vp8-vorbis-webm nothing happens on the chromecast. It just says media error in the log. Also passing this url within the TVHClient app does not work. So how do I get Chromecast running with Live TV or recordings?

**Comment by rsiebert** [comment]
I'll close this issue because implementing this is possible. But making this work is depends on the server. It must be powerful enough to transcode the stream.
