### ISSUE TITLE
Do not depend anymore on Google Play Services / Publish on f-droid.org

### ISSUE THREAD

**Issue by mbocquet** [rsiebert/TVHClient#311]
Please

- [ ] Make a release which doesn't depend on Google Play Services framework for alternative ROM users : CyanogenMod / LineageOS without Google Apps.
- [ ] publish it on https://f-droid.org/

**Comment by rsiebert** [comment]
This can only be done for the version that does not provide the additional features.
The Chromecast stuff and the inapp billing to purchase the unlocked version requires google.

Additonally how many users are actually using f-droid? Are there statistics available to decide if its worth the effort? I also use LinageOS but with google apps.

**Comment by mbocquet** [comment]
Periodically, after wiping my phone to a fresh CyanogenMod / LineageOS ROM, I try not to install Google Apps. Last time I survived one day. This time, I try to extend my record !
I'm surely not the only one.
Your App have greater UX compared to TVHGuide (present on f-droid).
For now, as I didn't installed Google Apps, I use TVHGuide. If your app weren't depending on Google Play Service I would run it. For now I can't install it on my device.

I don't know how many peole are using f-droid. I forwarded this question on their IRC...

**Comment by rsiebert** [comment]
Just being curious: Why only one day, whats so bad about google play store when using the nano package?
As an alternative you could always take the source code from github and compile your own apk with android studio.

**Comment by mbocquet** [comment]
Only one day cause after that, I absolutely need to run some "Google Play Services" dependant Apps available only from Google Play Store :'( with a Google account.
What's so bad is that these Apps still need "Google"

**Comment by rsiebert** [comment]
Closing the issue. 
The google play services are required for the in app billing and the chromecast stuff. Maintaining an extra app version for a minority of users (statistics would be useful) is currently not in the scope.

**Comment by jluttine** [comment]
I suppose the right solution would then be that someone creates a fork with the proper fixes and publishes it on F-Droid. I suppose the name should change then? LibreTVHClient or whatever. I'd be interested in that F-Droid package but I'm not able to do the fixes because I'm not familiar with Android programming at all.
