### ISSUE TITLE
Simple editing of channels would be nice

### ISSUE THREAD

**Issue by AlBundy33** [rsiebert/TVHClient#312]
Like numbers and tags. 
Maybe ordering instead of editing numbers. 

Editing channels on an android device in the webinterface is very hard....

**Comment by rsiebert** [comment]
The HTSP protocol does not support editing / modifying channels or tags. See https://tvheadend.org/projects/tvheadend/wiki/Htsp 
Implementing something that would override the provided server information in the app would be a larger task and probably low prio.

**Comment by AlBundy33** [comment]
Overriding the tags and numbers in tvhclient and handle them only there is not necessary. 

My idea was to have a better interface to configure the tags and numbers. ;-) 

So if this is not possible we can close this entry.

**Comment by rsiebert** [comment]
Closing issue because the HTSP interface does not provide these features.
