### ISSUE TITLE
Compatibility with Android TV devices?

### ISSUE THREAD

**Issue by Benoire** [rsiebert/TVHClient#318]
Is the app compatible with the Android TV boxes such as Mi Box?  I realise I can use Kodi in these situations but I'd prefer to simply have a TV front end as I can use other apps for movies etc.

Having the TVHClient act as a simple front end with FFW/RW/Pause/Play etc. all via a large interface and good performance would be fab!

**Comment by rsiebert** [comment]
This app is primarily developed for smartphones and tablets. It can run on TVs but the app android-tvheadend (https://github.com/kiall/android-tvheadend) is probably a better choice.
