### ISSUE TITLE
Username and password visible in url? 

### ISSUE THREAD

**Issue by AlBundy33** [rsiebert/TVHClient#320]
If I start a live-tv-stream from tvhclient i can open the properties in mx player and see http://user:pass@rpi...

Maybe it would be a good idea to remove this information?

**Comment by rsiebert** [comment]
You can try an pass this information to the player manually. If authentication is enabled, then the player should not be able to play the video. I'll check that here.

**Comment by AlBundy33** [comment]
The original url looks like this
http://tvh:XXXXXX@rpi:9981/stream/channelid/1836504206?ticket=C340E55F2B94982F4EBE6FBAE3F39AAA86FE06E8&profile=htsp

But I can start the stream (at least in MX Player) also with this url
http://rpi:9981/stream/channelid/1836504206?ticket=C340E55F2B94982F4EBE6FBAE3F39AAA86FE06E8&profile=htsp

**Comment by rsiebert** [comment]
The streaming uses only the url with the ticket
