### ISSUE TITLE
Is it possible to warn user if diskspace is low? 

### ISSUE THREAD

**Issue by AlBundy33** [rsiebert/TVHClient#321]
Tvheadend shows "Storage space" free/used/total

Is it possible to show a popup in tvhclient if free space is below a value (fix or percentage)?

I have some autorecordings and from time to time some recordings are not done because of a full disk.

I'm using TVHClient very often and so it would be nice if tvhclient would warn me if disk runs out of space.

**Comment by AlBundy33** [comment]
Btw I'm not sure which filesystem is shown in tvheadend web-interface.
Of course the check should warn if a recording folder runs out of space.

**Comment by AlBundy33** [comment]
I think tvheadend shows already the correct file system because my tvheadend server runs on a raspberry pi with a 32 GB SD card and an attached 320 GB usb hdd for recordings. 

Tvheadend already shows the information from my usb hdd.
So this information should be checked to warn the user from TVHClient.

**Comment by rsiebert** [comment]
There will be a setting in the advanced settings to define a threshold. When the free space is below the value then a notification will be shown
