### ISSUE TITLE
Issues with IPv6?

### ISSUE THREAD

**Issue by AlBundy33** [rsiebert/TVHClient#323]
I've setup a new fritzbox which has support for IPv6.

If I connect to tvheadend over http://rpi:9981 I can see the webinterface.
But If I try to cennect with TVHClient rpi:9982 I don't get a response.

If I change hostname with ip in TVHClient I can watch TV.

So maybe this is an issue with IPv6 as described in #56?

**Comment by rsiebert** [comment]
Currently ipv6 is not enabled in the app. The android framework tries to find the ip v4 address from the hostname. I'll add this feature later on.

**Comment by MarkusH1975** [comment]
Hi, 
I have similar problem.
Since I enabled IPv6 support on my fritzbox.
TVHclient gets only timeouts.

**Comment by CWempe** [comment]
Me too.

I would like IPv6 support or the ability to disable IPv6 in the app.

And maybe a better error description (and better log entry) to see why the connection does not work.

**Comment by mark-royds** [comment]
Another vote for this enhancement here

**Comment by rsiebert** [comment]
The new beta converts the hostname to an ip address at least for playback and casting by calling 
`InetAddress.getByName(connection.getHostname()).getHostAddress();`
I will add this to the regular connection attempt.

**Comment by CWempe** [comment]
Any news about this?

This issue seems to be still active with version *2.2.15 (174)* (5c13e91b).

**Comment by rsiebert** [comment]
Can you try the version [2.2.16-176](https://drive.google.com/open?id=1TuRbAdhAfIp8_tpfqT4CXpYBs2XHRIJ8). I have added basic support for using ipv6.

**Comment by MarkusH1975** [comment]
@rsiebert 
This version seems to be buggy.
There is no error message any more when trying to connect to IPV6, but it does not work.

When updating the app to this version, the old program database is still there but no playback can be started. Even the Play button is missing.

After a clean install (old app uninstalled) there is no error message, but no program list is shown.

**Comment by rsiebert** [comment]
Can you send me a debug log?

Am Mo., 12. Aug. 2019 um 11:03 Uhr schrieb Markus H. <
notifications@github.com>:

**Comment by MarkusH1975** [comment]
see E-Mail

**Comment by rsiebert** [comment]
the connection fails because a scope id is required. this is an information so that the OS knows what interface to bind it. this is not yet implemented. I have to add a selection in the connection settings. usually the network interface is wlan0 or the wifi interface of the phone.

**Comment by MarkusH1975** [comment]
Is this only needed in IPv6? means IPv4 has nothing similar ?

**Comment by rsiebert** [comment]
Please check the version [2.2.21-182](https://drive.google.com/open?id=1gbqi6XbnxPrOfAky19RwvVoRldspMyOX). I have removed the check for the scope id. Maybe this resolves the issue. If not then I need to look further.

**Comment by rsiebert** [comment]
The latest beta [2.4.6-233](https://drive.google.com/file/d/1dOKWmUNzB0JYRCWdnT1Oej7tA1Q4_o4F/view?usp=sharing) contains a fix for ipv6. This issue is probably the same as #524.
