### ISSUE TITLE
Channellist, recordings and epg not available if network was not available during tvhclient start

### ISSUE THREAD

**Issue by AlBundy33** [rsiebert/TVHClient#327]
This happens in my environment if my device looses wifi-connection while watching streams.

Here are the steps to reproduce it. 

- Disable wifi
- Start TVHClient 
- Now you should see the status page with the informative, that the network is not available 
- now enable wifi
- after some seconds the status page will refresh and show the usual statistics

But if you now try to switch to the channel list you'll see that only the status page is available.

**Comment by rsiebert** [comment]
Obsolete due to the newer version
