### ISSUE TITLE
Probleme mit vlc

### ISSUE THREAD

**Issue by dask2** [rsiebert/TVHClient#328]
Hallo, ich bin total happy mit der App. Seit ca einer Woche habe ich allerdings das merkwürdig Problem, dass das live-Bild mit vlc nicht mehr abgespielt wird. 
Habe deine App re-installiert, cache gelöscht, Daten gelöscht. Kein Erfolg.
Vlc re-installiert,Cache gelöscht,Daten gelöscht. 
Kein Erfolg. 
Habe einen anderen TVheaden-Client installiert und vlc spielt wieder gewohnt das live-Bild.
Auch unter kodi auf dem S5neo komme ich an das live Bild ran.

Mhm, nun weiss ich nicht, wo ich weitersuchen kann.
Vlc schliesse ich theoretisch aus, da es mit einer anderen App alles korrekt macht.
Deine App funktioniert ja an sich auch, erst bei der Übergabe an vlc scheint erwas niht zu klappen...
Fällt dir noch was ein?

vielen Dank schon mal im Voraus, 
Andreas

**Comment by callagg2** [comment]
Yes, same problem here. VLC is not playing the streams from your app.
But if I copy the stream addresses from TVH server and paste them into VLC, it plays the streams fine.

It's weird because your app is definitely connecting to the TVH server, showing that I have 127 channels, even showing the different programs on those channels, so the problem is not between the app and the server - its definitely between the app & VLC.

**Comment by dask2** [comment]
i've find a workaround:
don't start the stream by tipping on the broadcast  logo (even you selected this in the options).
tip on the epg an than go on 'play'.... now vlc starts streamin.

sorry about my english

**Comment by callagg2** [comment]
Strange that solution doesn't work for me.
But I too found a workaround - using SPMC (https://play.google.com/store/apps/details?id=com.semperpax.spmc16)

So, when I'm in the list of "All Channels" (EPG)
Select one Channel - then at the top right select "Play" and "open with" SPMC
There is a few seconds delay, but it plays fine :-)

So definitely something that VLC is doing!!

**Comment by callagg2** [comment]
Just to add, 
that MX Player (https://play.google.com/store/apps/details?id=com.mxtech.videoplayer.ad) behaves the same as VLC, it does NOT play the stream
but
BSPlayer Free (https://play.google.com/store/apps/details?id=com.bsplayer.bspandroid.free) plays it fine

**Comment by dask2** [comment]
... and today vlc made an update for android an it works again...
