### ISSUE TITLE
Bugs Bugs Bugs

### ISSUE THREAD

**Issue by hurzl** [rsiebert/TVHClient#332]
- Geplante Aufnahmen letzte zuoberst sortiert

- Programmübersicht nicht als Startansicht wählbar

- In der Übersicht Sender farbig (Genre)

- Zwei gleiche Aufnahmeicons in Sendungdetails

- Warum Neustart beim Akualisieren?

- Löschen geplanter Aufnahme "verwerfen vs. abbrechen"? Geht nicht zurück zur Liste

- Übersicht scrollt nicht synchron

- FATAL EXCEPTION: main  
```
                                                                         Process: org.tvheadend.tvhclient, PID: 22759
                                                                         java.lang.NullPointerException: Attempt to invoke virtual method 'boolean org.tvheadend.tvhclient.model.Recording.isScheduled()' on a null object reference
                                                                             at org.tvheadend.tvhclient.fragments.recordings.ScheduledRecordingListFragment$2.run(ScheduledRecordingListFragment.java:82)
```

**Comment by rsiebert** [comment]
Those bugs are not related to any app version in the play store right? 
Looks like that you install the app from HEAD.
The app is still under development, so expect bugs

**Comment by hurzl** [comment]
Nun erscheint beim Start "Änderungshistorie" und das wars

**Comment by rsiebert** [comment]
Closing this issue because the reported bugs are due to work in progress.
They will be addressed during the ongoing development
