### ISSUE TITLE
new server version and pvr access are broken (only informational)

### ISSUE THREAD

**Issue by TMHBOFH** [rsiebert/TVHClient#339]
Hi,

with [this](https://github.com/tvheadend/tvheadend/commit/d5eaa4ca6bae63ab98281ae39ef3f3106bb62896) modifications on server code the web access for pvr are broken.

You can fix this with the following settings.

![2018-03-14 22_24_40-tvheadend](https://user-images.githubusercontent.com/12548049/37432131-a7ba5776-27d7-11e8-8f5b-545bc64186f0.png)

**Comment by rsiebert** [comment]
Streaming with an external player uses now the getTicket method which does not require http authentication. Downloading still uses this but will be changed too.
