### ISSUE TITLE
No more VLC

### ISSUE THREAD

**Issue by kopi23** [rsiebert/TVHClient#340]
Hello, for quite a while now I can't play the channels in VLC because after clicking play, I just can select the Google Photos App as player. VLC is no longer listed as an option although it's still installed and I regularly use it to stream videos from other sources. Back then I was able to watch HD channels with VLC, with the Google Photos App, just the SD streams seem to work. I already tried wiping the data of the app and configuring it from scratch but no luck. Thanks for your help.

**Comment by rsiebert** [comment]
This should be fine with the 2.0.0 version.
