### ISSUE TITLE
Support translation

### ISSUE THREAD

**Issue by ghost** [rsiebert/TVHClient#341]
Hi
We support app with translation. I think that good solution will be implement translation to https://lokalise.co

It is good web page to support translation and more projects use this solution...
What do you think about it ?

**Comment by rsiebert** [comment]
This service is not free (https://lokalise.co/pricing)
Who is going to pay 40$ per month?

**Comment by ghost** [comment]
maybe other service... it is only example...

**Comment by rsiebert** [comment]
I have not found a free service. So I am closing this issue for now.
