### ISSUE TITLE
Hide duplicates option for Scheduled Recordings

### ISSUE THREAD

**Issue by LoopinFool** [rsiebert/TVHClient#344]
Recent versions of TVHeadend will skip duplicates, as defined by the recording options. But, those recordings are still listed - just tagged as duplicates. For a while, the TVH web interface has had an indication of which recordings are duplicates. In very recent versions, the web interface defaults to hiding duplicates and provides a toggle button to show/hide them.

It would be very nice if the "Scheduled Recordings" page in TVHClient would at least indicate when an entry is a duplicate (which won't be recorded), or perhaps have an option to show/hide duplicates. That option could either be an on-screen toggle button or hidden in the settings as a default. My personal preference is to only see what _will be_ recorded - which is now the default for TVHeadend's "Upcoming / Current Recordings" web interface.

**Comment by rsiebert** [comment]
This was added to the new version. The server must sort this. At least API version 32 afaik and up is required.
