### ISSUE TITLE
Chromecast requests Icon URL from tvheadend server

### ISSUE THREAD

**Issue by pmfrost** [rsiebert/TVHClient#345]
When casting, the TVHeadend server logs (a few times):

2018-06-16 11:35:56.972 http: 192.168.1.121: HTTP/1.1 GET /https://&lt;logoservername&gt;/tv7/logos/BBC%20Two%20HD.png -- 404

This should be requested directly from the host in the URL, not from &lt;tvheadendserver&gt;/&lt;fullurl&gt;

**Comment by rsiebert** [comment]
Can you provide an example? You mean the icon url should not be something like http://<hostname>/tvh/imagecache/187 but different?

**Comment by pmfrost** [comment]
In CastChannelActivity, the Icon url is always appended to the baseUrl:
https://github.com/rsiebert/TVHClient/blob/c584eedaa4a79c1f13f51b47936f93bfe2cddffb/app/src/main/java/org/tvheadend/tvhclient/features/streaming/external/CastChannelActivity.java#L79

That's fine if it's a relative path, like "/imagecache/187", but it can also be "https://example.com/channel.png" resulting in iconUrl = "https://tvh/https://example.com/channel.png"

downloadIconFromFileUrl does it correctly in EpgSyncTask, checking if the icon URL startsWith("http") and fetching it directly if it does, instead of from the HTSP server:
https://github.com/rsiebert/TVHClient/blob/c584eedaa4a79c1f13f51b47936f93bfe2cddffb/app/src/main/java/org/tvheadend/tvhclient/data/service/EpgSyncTask.java#L928
