### ISSUE TITLE
Not working with Tvheadend 4.2.4

### ISSUE THREAD

**Issue by xswqaz** [rsiebert/TVHClient#346]
It works stop with Tvheadend 4.2.4
Failed to connect tvh server (Access denied)
Other clients like kodi , TvhClient(iOS) are no problem, so I think only TVHClient problem

**Comment by TheBeardedLlama** [comment]
I can confirm I'm also running latest TVH and I'm getting access denied message

**Comment by xswqaz** [comment]
It's very weird
No problem within local network, Not working with internet host

**Comment by rsiebert** [comment]
Hmm, was there a change in the server from this version onwards? No changes were made in the app.

**Comment by xswqaz** [comment]
4.2.6-15~g88ae077-dirty is OK
4.2.4-dmo1~bpo9+1 is NG

**Comment by rsiebert** [comment]
Are the ports 9981 and 9982 accessible from the internet?

**Comment by xswqaz** [comment]
No problem with other client like kodi or windows tvh
Port is opened

**Comment by rsiebert** [comment]
Afaik Kodi and the iOS app access the server via http at Port 9981. My app uses this port only for streaming. For communication the app requires port 9982.

**Comment by xswqaz** [comment]
Kodi HTSP client use port 9981,9982 as well
https://forum.kodi.tv/showthread.php?tid=270385

**Comment by francoism90** [comment]
Could you guys try this: https://wiki.archlinux.org/index.php/Tvheadend#Unable_to_authenticate.2Fplay_stream

It did fix it for me and now it's working on the tvheadend git version.

**Comment by CWempe** [comment]
I am not effected by this issue, because I am ruinning an older version.

But reading the work around from francoism90's link:

    Change this to Both plain and digest to allow browsers/players that don't support the digest protocol.

TVHClient should `support the digest protocol` to fix this issue for everyone, right?

**Comment by xswqaz** [comment]
As CWempe said,
It was success to connect if digest auth off
Digest auth is on default setting

**Comment by lcseh** [comment]
Can someone please explain where exactly this needs to be altered? I'm too having issues using TVHClient with TVH 4.3

**Comment by rsiebert** [comment]
I need a test account on someones server to check if digest auth is working.
This is now only used when downloading recordings. Streaming with an external player app uses the getTicket method. No authentication in the url is required anymore.

**Comment by rsiebert** [comment]
The new beta version of the app uses the htsp method getTicket. This replaces authentication.
