### ISSUE TITLE
Edit timer directly before it is activated

### ISSUE THREAD

**Issue by CWempe** [rsiebert/TVHClient#347]
It would be very nice if you could add a timer and edit it directly without saving the timer first.

This is usefull when you want to record for example a soccer game wich starts after the broadcast is set to start.

Now I have to select the show like "champions league final" (20:15h) and set/activate the timer.
Then I have to navigate to my timers, find the right timer and change the times to the real kick off time (20:45h).
This is especially painfull if the program already started but there is still time left before the kick off.

The app [dreamDROID](https://play.google.com/store/apps/details?id=net.reichholf.dreamdroid&hl=de]) for example offers two options when a show is selected.
`set timer` and `edit timer`.
The later option opens the timer and lets the uder change everything directly before the timer is saved/activated.

**Comment by rsiebert** [comment]
Added a separate menu item for this feature

**Comment by rsiebert** [comment]
This will be available in the new 2.0.0 version

**Comment by CWempe** [comment]
Just installed the beta.
Seems to be exactly what I wished for. 😄 

Thanks.
