### ISSUE TITLE
spanish lang updated

### ISSUE THREAD

**Issue by wiormax** [rsiebert/TVHClient#350]
Hi @rsiebert i have values-sp updated actual file is just 10% of translation also some few strings are missing how i can send you file you dont reply yet my email.

thanks

regards

**Comment by rsiebert** [comment]
Hi,

Sorry for the late reply.
You can send the file to me per mail or you can create a pull request on
GitHub.
As you like.
Thanks for translating!

Best regards
Robert

wynasoft1 <notifications@github.com> schrieb am Di., 7. Aug. 2018, 23:57:

**Comment by wiormax** [comment]
Hi here is the file can you please tell me what is the strings of these sentences because are missing in translation

Thanks


Customize the user interface
Date and time format
Show progress bar
Show program subtitle

Enviado desde mi HTC

----- Mensaje de respuesta -----
De: "Robert Siebert" <notifications@github.com>
Para: "rsiebert/TVHClient" <TVHClient@noreply.github.com>
CC: "wynasoft1" <wyna89@hotmail.com>, "Author" <author@noreply.github.com>
Asunto: [rsiebert/TVHClient] spanish lang updated (#350)
Fecha: mar., ago. 7, 2018 5:09 P. M.

Hi,

Sorry for the late reply.
You can send the file to me per mail or you can create a pull request on
GitHub.
As you like.
Thanks for translating!

Best regards
Robert

wynasoft1 <notifications@github.com> schrieb am Di., 7. Aug. 2018, 23:57:

**Comment by rsiebert** [comment]
Hi, 
unfortunately I did not get any xml file. Can you resend it?

These missing strings in the english file you requested:
`<string name="pref_customize_user_interface">Customize the user interface</string>`
`<string name="pref_date_time_format">Date and time format</string>`
`<string name="pref_show_progressbar">Show progressbar</string>`
`<string name="pref_show_program_subtitle">Show program subtitle</string>`

**Comment by wiormax** [comment]
here you are also in your email you can find it.

thanks

regards

[tvhclientstrings.zip](https://github.com/rsiebert/TVHClient/files/2319939/tvhclientstrings.zip)

**Comment by rsiebert** [comment]
Thank you very much for the translation.
