### ISSUE TITLE
How to build/test?

### ISSUE THREAD

**Issue by francoism90** [rsiebert/TVHClient#352]
Hi @rsiebert,

I really would like to test v2.0.0, it seems a lot of stuff have been changed and fixed. :)

For some reason I'm unable to build on Linux and Windows because of libs missing.
Are the build instructions still up-to-date, any tips?

Thanks!

**Comment by rsiebert** [comment]
It should be enough to clone the repository and open the project with Android studio. Gradle should then get all required dependencies. Can you tell me which libs are missing?

**Comment by francoism90** [comment]
@rsiebert Sorry, will provide more info when I'm back on my Windows PC.

**Comment by francoism90** [comment]
@rsiebert Thanks for releasing a beta version. Hope you can keep building beta's. :)
I'll close this issue for now.

**Comment by francoism90** [comment]
@rsiebert Nevermind, turns out Android Studio doesn't like the special char. in my username. On Linux it builds fine. :)

On first usage I had to remove the previous version. I'm able to test and debug the app if you want.

**Comment by rsiebert** [comment]
Wow, I have never seen such an error. What Android Studio version are you
using and does the location to the app sources and sdk contain spaces or
special characters?

My gradle files are located at C:/Users/rsiebert/.gradle
The sdks are located under C:\Programs\android-sdk.
Maybe this could be an issue.

Am So., 30. Sep. 2018 um 21:07 Uhr schrieb François M. <
notifications@github.com>:

**Comment by francoism90** [comment]
@rsiebert Please read my edited comment. :)

**Comment by rsiebert** [comment]
Oh I guess missed your last comment. Glad to hear it is solved.

**Comment by rsiebert** [comment]
Please go ahead and report any issues you find in the app.

**Comment by hurzl** [comment]
I get the error "This version of Android Studio cannot open this project, please retry with Android Studio 3.4 or newer."
Is that true? If yes, is it really necessary?
The message is gone if I use 'com.android.tools.build:gradle:3.3.2' instead of 3.4.0-rc02

**Comment by hurzl** [comment]
Going back to 1.9.12 anyway, which works much better

**Comment by rsiebert** [comment]
You can downgrade Gradle if you want to use Android studio 3.3. But you figured it out already. Why should version 1.9.x be better? Anything missing?

**Comment by hurzl** [comment]
It's much faster and in 2.x I found no real progress
