### ISSUE TITLE
Beta: channels are not ordered correctly 

### ISSUE THREAD

**Issue by AlBundy33** [rsiebert/TVHClient#353]
In settings it set that channels should be ordered by number but this doesn't seem to work in the current beta.

**Comment by AlBundy33** [comment]
It seems that channel numbers are ordered alphabetically instead of numeric.
e.g. 1,10,11...,2,20,21...

**Comment by gitjose32** [comment]
I tested that the issue affects only to the beta version. The non beta orders the channels by the server number correctly

**Comment by AlBundy33** [comment]
Seems to be fixed with latest beta
