### ISSUE TITLE
2.0.0 crash after connect

### ISSUE THREAD

**Issue by TopperBG** [rsiebert/TVHClient#355]
Couldn't connect to any of my (few) tvh servers.
After login and **_Loading data from server app_** and **_Init_** closes w/o any message.
Data and cache are cleared after upgrade.
TVHs shows on console:

> 2018-09-17 12:33:03.162 htsp: Outside IP: Welcomed client software: TVHClient (HTSPv31)
> 2018-09-17 12:33:03.326 htsp: Outside IP [ TVHClient ]: Identified as user 'Admin'
> 2018-09-17 12:33:03.326 htsp: Outside IP [ Admin | TVHClient ]: Privileges updated
> 2018-09-17 12:33:05.930 htsp: Outside IP [ Admin | TVHClient ]: Disconnected

The phone is Huawei P8, Android 6.0, EMUI 4.0.3
App with granted all permision (storage required) and excluded from Power managment so can leave working at background.
BTW all my TVHs are reachable by IP address not by hostname ?

**Comment by TopperBG** [comment]
The phone is Huawei P8, Android 6.0, EMUI 4.0.3
BTW all my TVH are reachable only by IP address not by host name ?

**Comment by rsiebert** [comment]
Please test the updated beta version. It hopefully resolves the issue

**Comment by TopperBG** [comment]
Yes, now it works.
Thank you!
