### ISSUE TITLE
Problems with program overview

### ISSUE THREAD

**Issue by AlBundy33** [rsiebert/TVHClient#357]
Sometimes if I select a channel the program title vanishes and comes back if I select the channel again.
Just have a lock at servus tv in my screenshots. 

Also the current running program is displayed twice on left and right side. 

And if I scroll through the channel ist it stucks sometimes - feels like there is something reloaded. 
This wasn't an issue with the latest stable version.

![screenshot_20180920-230520](https://user-images.githubusercontent.com/6294586/45848588-5e6b4100-bd2f-11e8-910e-04317c9bcc92.png)
![screenshot_20180920-230530](https://user-images.githubusercontent.com/6294586/45848604-688d3f80-bd2f-11e8-9013-8aeaa6a7377b.png)

**Comment by rsiebert** [comment]
Are these issues still present?

**Comment by AlBundy33** [comment]
Yes - have a look at the screenshot. 

I've clicked multiple time on the channels on the left side and now RTL is dhowing only the subtile and "Der Lehrer" is vanished. 

Also have a look at ZDF - left Info shows that the following program is "Die Zeit" but right you'll see the correct following program.

![screenshot_20181002-201813](https://user-images.githubusercontent.com/6294586/46368373-5771f600-c680-11e8-8e3e-feb9f93ee737.png)

**Comment by AlBundy33** [comment]
Next program on the left side seems fine now but there still is a issue on the right side (but only on some chamnels).

Just have a look at the screenshots from. Tvhclient and tvheadend. 

![screenshot_20181004-175219](https://user-images.githubusercontent.com/6294586/46486693-9a59d800-c7fe-11e8-9c26-8bfc3882f212.png)
![screenshot_20181004-175210](https://user-images.githubusercontent.com/6294586/46486694-9a59d800-c7fe-11e8-9096-acb59de95afe.png)

I can reproduce the issue with the vanishing title like this:
Open tvhclient (fsvorites are selected by default)
Select some channels on the left side
Scroll down to the last channel
Select the last channel

In my case now the program title on the lrft side of the last channel vanishes. 
If not you can select other channels and at some point the title vanishes.

**Comment by AlBundy33** [comment]
@rsiebert this issue is labeled with question but for me this looks more like a bug.

**Comment by rsiebert** [comment]
There is no special logic to show stuff on the last channel. So I assume this is somehow related to the framework below and the used recycler view. I could also not reproduce this on my phone. Closing for now
