### ISSUE TITLE
Fetch http and htsp profiles from the server

### ISSUE THREAD

**Issue by rsiebert** [rsiebert/TVHClient#361]

**Comment by rsiebert** [comment]
This seems to be a server issue because the server sends all profiles to the app. 
An option would be to always provide the default recording profile and the htsp, matroska and pass Playback profiles.

**Comment by DragonQ** [comment]
Do you know if there is an existing Tvheadend bug for this? Presumably certain profiles aren't being exposed to this app. If not, I can make one based on the info in #351.

This is the last big hurdle for me permanently switching to Tvheadend so I'm definitely keen to help get it sorted! :)

**Comment by rsiebert** [comment]
Please open a bug for tvheadend. Maybe they know what is going on.

**Comment by rsiebert** [comment]
If the server somehow does not provide the default profiles htsp, matroska and pass then they will be added manually by the app.

**Comment by DragonQ** [comment]
OK so I opened a Tvheadend bug and got a very useful response:

https://tvheadend.org/issues/5258

In summary, there are two separate profile lists: one that contains HTSP profiles and one that contains HTTP profiles (which include MPEG-TS Spawn profiles like the one I am trying to use). To get the HTTP profiles, you need to call:

HTSP "api" method -> path "profile/list", args empty -> response is list

**Comment by rsiebert** [comment]
This would mean to implement a second way to retrieve data from the server. Currently all is done using the htsp protocol. Can be done for profiles only I guess.

**Comment by ljalves** [comment]
No need to implement that - you can do http requests using htsp "api" message: https://tvheadend.org/projects/tvheadend/wiki/Htsp#api-Added-in-version-24

**Comment by ljalves** [comment]
By the way, as far as I know TVHClient can only do HTTP streaming (because it uses an external player) right?
If that is true my suggestion would be to remove any htsp profile from the "get profiles" function as they are unusable on http streaming.

**Comment by rsiebert** [comment]
The new version 2.0.0 will have an internal player that uses htsp. So maybe
in the future the external player will be obsolete.

Luis Alves <notifications@github.com> schrieb am Mi., 17. Okt. 2018, 01:48:

**Comment by rsiebert** [comment]
Thanks for the hint with the htsp api. I'll use that.

**Comment by DragonQ** [comment]
FYI, I built from master the other day and was able to select and successfully use HTTP profiles. Thanks a lot!

**Comment by DragonQ** [comment]
Hi, I tried the latest version from the Play Store today (2.2.5) and it still doesn't include this feature. My dev build from 29/10/2018 does include this feature. When will it appear in an officially supported release?

**Comment by rsiebert** [comment]
The latest sources are on the develop branch, there the http profile
fetching is included.
But your server API version must be 26 or higher to support http profiles.
Otherwise it is disabled.

Am Do., 4. Apr. 2019 um 20:16 Uhr schrieb DragonQ <notifications@github.com

**Comment by DragonQ** [comment]
> The latest sources are on the develop branch, there the http profile fetching is included. But your server API version must be 26 or higher to support http profiles. Otherwise it is disabled. Am Do., 4. Apr. 2019 um 20:16 Uhr schrieb DragonQ <notifications@github.com

OK thanks. My server API version is 34. I guess I'm just a bit confused because the feature is tagged as "2.0.0", so I assumed version 2.2.5 from the Play Store would include this feature. Am I misunderstanding this?
