### ISSUE TITLE
Add OSD in internal player

### ISSUE THREAD

**Issue by rsiebert** [rsiebert/TVHClient#366]

**Comment by francoism90** [comment]
The internal player doesn't seem to work, it tries to start the stream, but stops after 2 secs.

**Comment by rsiebert** [comment]
Can you send me the debug log please?

François M. <notifications@github.com> schrieb am Sa., 6. Okt. 2018, 20:40:

**Comment by francoism90** [comment]
@rsiebert Don't think you need the debug log anymore. :+1: 
Let me know if you need help/info.

**Comment by rsiebert** [comment]
This has been implemented a while ago.
The internal player can be minimized to continue browsing the app or doing something else.
