### ISSUE TITLE
Introduce and update certain overlay texts

### ISSUE THREAD

**Issue by rsiebert** [rsiebert/TVHClient#369]
* Change cast overlay text
* Add overlay text for certain features that might need a hint

**Comment by francoism90** [comment]
Does this include the permission dialogs (storage access, etc.)? :)

**Comment by rsiebert** [comment]
This dialog will popup when the user wants to download something for the first time or when he wants to change the directory in the settings.

**Comment by francoism90** [comment]
@rsiebert I'm getting this question on every first install: Lineage OS 15.1

**Comment by rsiebert** [comment]
Closing issue. This will not be done.
