### ISSUE TITLE
Beta: program list is not updated after restart

### ISSUE THREAD

**Issue by AlBundy33** [rsiebert/TVHClient#374]
Kabel 1 was the last channel I've watched before I went to bed.
After I have restarted TVHClient today I see the current programs in the channel list (left) but the old programs on the right side. 

![screenshot_20181003-112707](https://user-images.githubusercontent.com/6294586/46402307-aca11c80-c6ff-11e8-80d0-b2294fa1ba2d.png)

**Comment by rsiebert** [comment]
Thanks for finding this issue.
This should be fine with the latest beta that was just released.
