### ISSUE TITLE
Wrong aspect ratio with internal player (especially 16:9 SD channels)

### ISSUE THREAD

**Issue by dkonerma** [rsiebert/TVHClient#376]
Hi Robert,

when watching especially 16:9 SD channels with TVHguide's internal player, the aspect ratio is often wrong. I believe it's 5:4 or 4:3.

I'm testing with transcoded streams... and according to mediainfo the stream delievered by tvh is looking fine, e.g.

Width                                    : 720
Width                                    : 720 pixels
Original width                           : 480
Original width                           : 480 pixels
Height                                   : 576
Height                                   : 576 pixels
Original height                          : 384
Original height                          : 384 pixels
Sampled_Width                            : 480
Sampled_Height                           : 384
Pixel aspect ratio                       : 1.455
Display aspect ratio                     : 1.818
Display aspect ratio                     : 16:9

I mapped a test channel to your test account on my server, so feel to replicate the issue from your side. I will send you access details via E-Mail.

Cheers
Dietmar.

**Comment by dkonerma** [comment]
Additional info: streaming the same service to e.g. VLC or even Google Photos (!) works fine showing the correct AR. So this indeed seems to be an issue of the internal player.

**Comment by dkonerma** [comment]
Looks like any video is displayed wiith forced pixel aspect ratio 1.0, which leads to distortion for "anamorphic" videos.

**Comment by rsiebert** [comment]
Does the internal player show the videos with the correct aspect ratio when the version 2.0.0-123 is used?

**Comment by dkonerma** [comment]
Hi Robert,

No, still the same. You should see the issue on my server, channel 10.

Dietmar

Am So., 18. Nov. 2018, 23:18 hat Robert Siebert <notifications@github.com>
geschrieben:

**Comment by rsiebert** [comment]
The internal player (which uses the exoplayer library) reports the SD channel with width 900, height 720, pixel aspect ratio 1.0

**Comment by dkonerma** [comment]
@Robert, thanks for looking into this.

Indeed, that's weird. External players play the channels fine with the correct ar and the mediainfo result I posted above ("Pixel aspect ratio : 1.455") is from the very same test chhannel.

Maybe there is a difference http vs htsp? Are you able to grab the stream via htsp and check with mediainfo on that grabbed stream? If it shows 1.0, then exoplayer is right and this would be a TVH issue to be reported there.

Cheers 
Dietmar

**Comment by rsiebert** [comment]
I grabbed the steam via htsp as the internal player uses only htsp. There
the mediainfo shows a ratio of 1.0. The SD channel plays a 5:4 (900:720)
ratio.

**Comment by rsiebert** [comment]
The internal player provides now a button to select from a list of aspect ratios

**Comment by dkonerma** [comment]
Hi Robert,

the new button to select the aspect ratio behaves somehow weird here. :)

When I see the distorted picture for a channel, I select the button and see "16:9" selected.  Hmm... 16:9 would be correct, so I tap again on the already selected radio button. And now the apect ratio gets corrected. ;-)

Also I need to do this every time I select that channel. 
Currently I use an external player, since this is too annoying. Every external player I tested works as expected btw.

Cheers
Dietmar.

**Comment by frasty** [comment]
I can still confirm this is an open issue. With internal player every SD channel plays with a forced 4:3 aspect ratio whereas most of them are actually 16:9. 
To me it would be much better to force internal player playing a default 16:9 for SD channels, until the right aspect ratio for every channel get sorted out, at least.

**Comment by rsiebert** [comment]
Hi, the internal player which uses Google's exoplayer library sets the
aspect ratio depending on the media information which is inside the video
stream. For SD channels the aspect ratio seems to be always 4:3. Therefore
I had to add the button to correct this. I don't know if this can be
corrected on the server side

frasty <notifications@github.com> schrieb am Sa., 20. Apr. 2019, 09:24:

**Comment by frasty** [comment]
Thank you, but I don't get why external players correctly play SD streams, maybe they stream from a different source or it is an exoplayer library problem?
I clearly don't have the whole picture, anyway this is the program output I get from mplayer playing an SD channel and as you can see Movie-Aspect is 1.82:1:
```
[goo@darkgoo ~]$ mplayer -dumpstream "http://192.168.9.238:9981/stream/channelid/691542199?ticket=976FAE9F8D8D17C37B54BC31274B303C64B3FFF1&profile=pass" 
MPlayer 1.4-8 (C) 2000-2019 MPlayer Team

libavformat version 58.20.100 (external)
Mismatching header version 58.12.100
TS file format detected.
VIDEO H264(pid=44) AUDIO MPA(pid=192) NO SUBS (yet)!  PROGRAM N. 16924
Stream not seekable!
FPS seems to be: 25.000000
==========================================================================
Opening video decoder: [ffmpeg] FFmpeg's libavcodec codec family
libavcodec version 58.35.100 (external)
Mismatching header version 58.18.100
Selected video codec: [ffh264] vfm: ffmpeg (FFmpeg H.264)
==========================================================================
==========================================================================
Requested audio codec family [mpg123] (afm=mpg123) not available.
Enable it at compilation.
Opening audio decoder: [ffmpeg] FFmpeg/libavcodec audio decoders
AUDIO: 48000 Hz, 2 ch, floatle, 192.0 kbit/6.25% (ratio: 24000->384000)
Selected audio codec: [ffmp2float] afm: ffmpeg (FFmpeg MPEG layer-1 and layer-2 audio)
==========================================================================
AO: [pulse] 48000Hz 2ch floatle (4 bytes per sample)
Starting playback...
[h264 @ 0x7f6829f633c0]Missing reference picture, default is 65512
[h264 @ 0x7f6829f633c0]Missing reference picture, default is 65512
[h264 @ 0x7f6829f633c0]mmco: unref short failure
[h264 @ 0x7f6829f633c0]mmco: unref short failure
**Movie-Aspect is 1.82:1** - prescaling to correct movie aspect.
VO: [vdpau] 720x576 => 1048x576 Planar YV12 
A:39513.3 V:39514.2 A-V: -0.883 ct: -0.004   4/  4 ??% ??% ??,?% 0 0 2%                                                                                                                                                                     
[h264 @ 0x7f6829f633c0]mmco: unref short failure
A:39520.2 V:39520.5 A-V: -0.317 ct: -0.628 160/160 11%  1%  5.4% 0 0 3%
```
