### ISSUE TITLE
Implement Android Backup/Restore functionality

### ISSUE THREAD

**Issue by virtualdj** [rsiebert/TVHClient#381]
I installed TVHClient into a new smartphone using my account but TVHClient didn't restore my settings.
Can you add the standard backup/restore API to TVHClient so if you change device or reinstall you didn't have to create the connection and set the options all the times?

**Comment by rsiebert** [comment]
When using Android 6 and up (API version 23) auto backup is enabled by default. Do you have a device not using Android 6 or later?

**Comment by virtualdj** [comment]
Thanks for your answer. Mmm, my old device was using Android 4.4.4 while the new has 8.1 so I suspect the old version didn't save the settings.
