### ISSUE TITLE
Beta: unable to Chromecast

### ISSUE THREAD

**Issue by francoism90** [rsiebert/TVHClient#382]
I have build the latest TVHClient (today), but I'm unable to cast/enable additional features (this worked before - have bought it).

Thanks.

**Comment by rsiebert** [comment]
What happens when you press the buy button in the unlocker screen? 
Or are all features already enabled but casting does not work?
Did you select a proper casting profile?

**Comment by francoism90** [comment]
It shows me a list of all additional features - already bough full version on Play Store.
I did select the correct profile (custom: cast) - worked fine in last version I've tested.

**Comment by francoism90** [comment]
Hmm, seems the unlocker doesn't work.

**Comment by rsiebert** [comment]
When you compile the app from the sources yourself it is not signed with my
key. Google treats this tvhclient as a different app.
You need to install the version from the play store for the unlocker to
work.

Am Di., 16. Okt. 2018 um 22:10 Uhr schrieb François M. <
notifications@github.com>:

**Comment by francoism90** [comment]
@rsiebert Hmm, it did work previously without the signed key (remember I did send you that video?)

**Comment by rsiebert** [comment]
Ah ok. What does the log or adb output say? The last working version was 114? Afaik no changes were done in the casting logic that affects Playback.

**Comment by francoism90** [comment]
Switched to the Play Store beta and still it is not visible. Really weird, it worked perfectly in the last beta.

**Comment by francoism90** [comment]
@rsiebert Sorry for all the noise, it was the Chromecast causing the issue. After restarting the device, I'm able to cast again!
