### ISSUE TITLE
Add option share or copy stream URL to clipboard

### ISSUE THREAD

**Issue by dkonerma** [rsiebert/TVHClient#386]
Maybe some nice enhancement, also for trouble-shooting: an Option to share or copy the Stream URL (which is e.g. also passed to for casting) to the clipboard (or even offer the standard sharing options). This could be easily added to the corresponding contect menues.

The  URLs containing the auth ticket are valid for 5 minutes. Enough to send and use it somewhere else, e.g. in a browser.

Cheers
Dietmar.

**Comment by francoism90** [comment]
It seems to be possible to increase the auth ticket from the general settings.
Another solution would be to generate a stream url with basic-auth:
`http(s)://<user>:<pass>@<ip>:9981/stream/channelnumber/<channel-number>?profile=<stream-profile>`

**Comment by rsiebert** [comment]
basic auth was used in the past. Many tvheadend servers have changed the auth mechanism to digest which where this url format will not work.

**Comment by dkonerma** [comment]
The "Stream URL" I was talking about could exactly the same, that is transmitted to Cast devices... if everything is setup for casting, then that URL should be perfectly fine to directly request a stream.

**Comment by rsiebert** [comment]
I will add a setting that if enabled will always copy the stream URL to the
clipboard when the user presses play. So the popup menu will not become too
cluttered.

Am Mo., 14. Jan. 2019, 16:08 hat dkonerma <notifications@github.com>
geschrieben:

**Comment by rsiebert** [comment]
Added in the 2.0.0-140 beta
