### ISSUE TITLE
Recording /Timeshift Option

### ISSUE THREAD

**Issue by dankec2000** [rsiebert/TVHClient#387]
First, let me congratulate you for a great product.
Now the question:
Am I missing an option form Record / TIme Shift management via Android?

I'm having Tvheadend installed on Synology NAS and would like an option for Recording and Timeshift of desired Show. Are you planning to add this?

**Comment by rsiebert** [comment]
Hi, recording a desired show is already working for a long time. Does your user have the rights to record shows? By timeshift management you mean stopping, skipping forward and backward during playback? This is a player feature. VLC can pause and resume. The internal player will have this in the near future.

**Comment by dankec2000** [comment]
Thanks, I found recording. There was a problem with my acc rights, you were right!
