### ISSUE TITLE
Issue when using connection limits

### ISSUE THREAD

**Issue by ljalves** [rsiebert/TVHClient#388]
TVHClient is using 2x connections to the server - 1 permanent connection for htsp and 1 for the http streaming.

The worst case is when the user is limited to 1 connection to the server - in this case TVHClient doesn't work as it can't start streaming.
If a user has 4 max connections to the server then only 2 TVHClients can be used simultaneously.

A possible solution is to close the htsp connection before playing http streams.

**Comment by rsiebert** [comment]
Is this really a problem keeping two connections to a server?
Usually the server is controlled by the person that uses the app so connection limits are not really an issue?

**Comment by ljalves** [comment]
Not always. The server owner can share it with whoever he wants, and the point of having a config option to limit connections is to control the abuse of upload bandwidth (for example).

I also opened a ticket on tvheadend side asking to add a "stream" connection limit (instead of a global connection limit).

**Comment by ljalves** [comment]
As I said above, things got worked out on tvheadend side.
Usage count has changed since commit https://github.com/tvheadend/tvheadend/commit/ed33294f9cdfe41696e9e95cf81a75510d6f1193

Now only when a streaming connection counts as "slot" usage.

I believe this can be closed...

**Comment by rsiebert** [comment]
Thanks for the update.
