### ISSUE TITLE
HTTP profiles don't get updated

### ISSUE THREAD

**Issue by DragonQ** [rsiebert/TVHClient#389]
Related to #361

Although I can fetch and select an HTTP profile and then use it successfully, I cannot get TVHClient to refresh the list of profiles when they are changed server-side without changing the user I'm connecting as. I've tried:

- Refreshing the connection (using "reconnect")
- Restarting the app
- Restarting Tvheadend service
- Uninstalling and reinstalling the app
- Removing and re-adding the connection

The only way I've found to see newly added (or renamed) HTTP profiles is to add a new user to Tvheadend, add the profiles to that user's credentials, then create a new connection in TVHClient using the new user.

This could well be a Tvheadend bug but I am interested if it can be reproduced. Basically:

- Create a Streaming Profile called "test"
- Allow the * user to use it
- Connect via TVHClient with no credentials and check the profile is in the list of available profiles
- Clone the profile in Tvheadend and call it "test2"
- Reconnect via TVHClient
- The new "test2" profile does not appear, only the old "test" one appears

**Comment by rsiebert** [comment]
The app just receives all available htsp profiles during startup from the server. This is done automatically when calling the enableAsyncMetadata method. After that the http profiles are fetched by calling the http api with profiles/list. When certain profiles are not transmitted then this is likely a server issue.

**Comment by rsiebert** [comment]
Closing because this seems a server issue.
