### ISSUE TITLE
Beta: is it possible to predefine the profiles? 

### ISSUE THREAD

**Issue by AlBundy33** [rsiebert/TVHClient#392]
After each db reset I have to set the profiles for recording to default, internal player to htsp and external player to pass.

In tvheadend pass is marked as default. 

So it would be nice if tvhclient sets the defaults from tvh or maybe tries to find a good initial default.

**Comment by rsiebert** [comment]
Good idea. I will add this.

**Comment by rsiebert** [comment]
Added in latest beta 2.0.0-122
