### ISSUE TITLE
View logs from tvheadend in tvhclient. 

### ISSUE THREAD

**Issue by AlBundy33** [rsiebert/TVHClient#394]
Is it possible to add an rntry to view tvheadend logs in tvhclient? 
Like the logviewer in tvheadend webui.

**Comment by rsiebert** [comment]
You mean the logs from the server or the tvhclients internal log? Getting the logs from the server is not supported by the htsp api.

**Comment by AlBundy33** [comment]
I was talking about the server log because it is also displayed in webui

**Comment by AlBundy33** [comment]
If server logs are not possible tvhclient logs would be nice too (maybe they can help us to find bugs better).

**Comment by rsiebert** [comment]
I'll close this issue. I assume that the vast majority of the users don't want to see the debug logs at all or even within the app.
