### ISSUE TITLE
On HuaweiP10 i dont have a sound

### ISSUE THREAD

**Issue by ghost** [rsiebert/TVHClient#400]
Hi
I have installed TVHClient 2.0.0 (128) and when i use internal player i dont have a sound from my TV

**Comment by ghost** [comment]
Also when i use internal player i can not setup volume for media... no available... and not hear sound from TV stream....

**Comment by rsiebert** [comment]
In the latest beta 2.0.0-129 the sound should be available again. It was primarily missing if ac3 was used.

**Comment by ghost** [comment]
Hi
I test and still is not available. I also can not setup media volume for internal player.

**Comment by rsiebert** [comment]
What sound codec does your stream use? Ac3? Something else? The internal
player (exoplayer) can't decode all codecs. You could change the audio
codec in the tvheadend server.

The hardware volume keys are used to control the sound volume. This is the
same mechanism to control the volume that VLC or mxplayer uses.

Am Di., 25. Dez. 2018, 16:20 hat pepeEL <notifications@github.com>
geschrieben:

**Comment by ghost** [comment]
I use htsp. I use default setting in TVHeadend.

I know that use volume key but when click it change volume ring tone. 

On VLC player sound works ok and volume keys works for media.

**Comment by ghost** [comment]
Hi
Now i download latest beta
Now sound works ok. I hear all :)
Thanks :) Good Job :)
