### ISSUE TITLE
Beta: channels sometimes displayed twice

### ISSUE THREAD

**Issue by AlBundy33** [rsiebert/TVHClient#403]
See screenshot
![screenshot_20190105-172556](https://user-images.githubusercontent.com/6294586/50726550-330a3780-110f-11e9-96cd-0d946787e7d6.png)

**Comment by rsiebert** [comment]
Should be fixed in the last beta 2.0.0-135

**Comment by AlBundy33** [comment]
Currently all channels are displayed once but some programs are displayed twice. 
![screenshot_20190106-011001](https://user-images.githubusercontent.com/6294586/50730552-062a4480-1150-11e9-89fa-630d976c00f3.png)

**Comment by rsiebert** [comment]
Is this still an issue with the 2.0.0-138 version?

**Comment by AlBundy33** [comment]
Seems to be fixed in latest beta.
I think we can close this issue - I'll create a new one if this occurs again.
