### ISSUE TITLE
Beta: after selecting program channellist is overwriten with program info

### ISSUE THREAD

**Issue by AlBundy33** [rsiebert/TVHClient#404]
See screenshot - left side is now showing program details instead of channellist
![screenshot_20190105-172820](https://user-images.githubusercontent.com/6294586/50726572-88dedf80-110f-11e9-8b38-8cafa8cfa1af.png)

**Comment by rsiebert** [comment]
Should be fixed in the last beta 2.0.0-135

**Comment by AlBundy33** [comment]
Seems to work with 135
