### ISSUE TITLE
please make it usable with remote control

### ISSUE THREAD

**Issue by makabar** [rsiebert/TVHClient#405]
Hello there,
not really an issue. almost an feature-request.
i own a android based himedia streaming/settop-box. i use it as mediaplayer in my garage (man-cave). 
i love tvhclient on tablet. but the user experience while using the app with remote control ist a little bit frustrating. i have to switch the remotecontrol in to mouse-mode to change favorite-lists for example.
is there a hope for make tvhclient more usable for remotecontrols?

**Comment by rsiebert** [comment]
Hi, this issue is a very rare usecase. I am sorry but I have to reject this feature request.

**Comment by makabar** [comment]
:-(
