### ISSUE TITLE
wrong channel list order

### ISSUE THREAD

**Issue by jampy** [rsiebert/TVHClient#406]
Since the update that brought the database mechanism, my channel list is displayed in wrong order (seems random).

Alphabetical sort order works, but I'd prefer the order by channel number, which is not respected.

This worked before.

Tvheadend 4.2.1 with 214 channels
TVHClient 2.0.0 (141)
Samsung S7 with german locale

**Comment by rsiebert** [comment]
HI you can change the sorting order in the ui settings. There you can set the sort order by name, channel number or by id (server).

**Comment by rsiebert** [comment]
In the version 2.0.1 new sorting options were added and the order by channel id was fixed.
Does it work now?

**Comment by francoism90** [comment]
@rsiebert It's indeed possible to sort, but the backend sorting option doesn't work anymore. I now have to manual select use channel-order, as @jampy said, this worked fine in previous releases.

Do you need any debug info?

**Comment by rsiebert** [comment]
The server gives every channel am id. But the server sends the channels during sync not in the channel id order but random. Probably in the order how they are shown in the Webinterface. I'll add this sort option in the next version.

**Comment by francoism90** [comment]
@rsiebert With the latest update (yesterday), the app crashes when trying to sort on channel number.
Not a big issue, since you're working on it, but do you need any debug info?

**Comment by rsiebert** [comment]
Thanks for the info.
I have noticed this and will provide a fix.

Am Mo., 28. Jan. 2019, 10:22 hat François M. <notifications@github.com>
geschrieben:

**Comment by rsiebert** [comment]
Version 2.0.3 provides 4 sorting options in ascending or descending order. The "Defined by server" sorts the channels in the order they are send by the server. This should correspond with the order in the webinterface.

**Comment by De-k** [comment]
I still see that (wrong) behavior. ´The list seems to be random if i choose "defined by server". It does not correlate at all with the  "number" column of the tvh webclient (i also use kodi on the same instance of tvh, there the order is correct)

So still not solved in 2.0.3 
Dek

**Comment by rsiebert** [comment]
Can you please send me the debug log? Please do a "reconnect" and then send
me the log so I can see the what the server is sending when.

Am Mo., 28. Jan. 2019, 17:01 hat De-k <notifications@github.com>
geschrieben:

**Comment by De-k** [comment]
Logfile sent via mail

**Comment by rsiebert** [comment]
In the version 2.0.4 the sort option "Channel number" has fixed the problem for many users.

**Comment by sei4eto** [comment]
Hello!
Still channel order issue hasn't been fixed yet! Since the last update 2.0.4 when I try to set channel order to "channel number" - TVH crashes. When I use "defined by server" - channels order seems to be wrong.
Thank you! 
Nokia 6.1 Android 9 TVHeadend server - 4.2.6
P.S. And timeshift doesn't work as well

**Comment by De-k** [comment]
Channel number has fixed it for me in 2.0.4
