### ISSUE TITLE
Playback in external player audio only

### ISSUE THREAD

**Issue by ttcc-gh** [rsiebert/TVHClient#408]
Current version 2.0.2 starts external (VLC, Samsung Player) playback (live tv) with audio only.  Never had this problem with v1. com.dimafon.tvhclient uses external players without problems also.

**Comment by rsiebert** [comment]
There is a setting under advanced settings to copy the playback url to the clipboard. Then you can paste this url in the vlc player. Did you also check the playback profiles?

**Comment by ttcc-gh** [comment]
Thanks for the Hint, I just noticed that im my TVHeadend all profiles are listed twice (same name), only the half of them was enable for the user account I used.
