### ISSUE TITLE
Search inconsistent between views

### ISSUE THREAD

**Issue by lwis** [rsiebert/TVHClient#409]
Channels and Program guide have different search functionality (Channels doesn't work, while Program guide does).

Tested against 2.0.4

**Comment by rsiebert** [comment]
Search in the channel screen searches only if there is a match with the available channel names and the current and next program title or subtitle of a channel. This was done so a user can also search for channels in this screen.
A Search in the epg searches through all programs in the database.
So the different funtionality was intended and is also shown as a hint in the search bar. It either shows "Search channels" or "Search program guide"

**Comment by lwis** [comment]
Ah, ok thanks for explaining. This wasn't very clear for me.
