### ISSUE TITLE
Close background app or the connection to the server

### ISSUE THREAD

**Issue by bbleifuss** [rsiebert/TVHClient#412]
First I want to thank you for this great app.

Starting from version 2.x I have a small problem. In older versions the connection to the server has been closed, when the app was minimized or not running. So my server could go to sleep, if there is no recording or no other connection.
Now the background app is always connected to the server, which keeps the server awake.

Is it possible to also close the background app, when the main app is not running or minimized?
Or is it possible to have a timeout for the background app?

**Comment by rsiebert** [comment]
Is this still an issue? The app should behave now as the 1.9.x version. Please feel free to reopen the issue if it's not yet ok.
