### ISSUE TITLE
EPG showing duplicate entries

### ISSUE THREAD

**Issue by binhex** [rsiebert/TVHClient#413]
Hi so since the switch to version 2.x I'm noticing duplicate entries in the EPG for all channels. I have tried clearing cache and also disconnect and reconnect to try and flush out any old entries but this has not fixed the issue, any advice?

See here for link to screenshot taken on my Huawei P20:-
https://drive.google.com/file/d/1-9OBdEoxbHjIp1pBx0r9n753A8lvKswU/view?usp=drivesdk

**Comment by rsiebert** [comment]
In the advanced settings there is an option at the bottom to clear the database contents, except the connections. This removes all programs, ... and reloads them.

**Comment by binhex** [comment]
Thanks Robert that's got it.
