### ISSUE TITLE
Channel number ordering doesn't handle number 0 properly

### ISSUE THREAD

**Issue by Flole998** [rsiebert/TVHClient#415]
Channel number sorting puts channel number 0 at the beginning, even though 0 should be reserved for "no number". It shouldn't put them at the beginning when ascending sort is selected but put them to the end as those are the unsorted channels.

**Comment by Flole998** [comment]
This can be done in sqlite using  ORDER BY c.display_number == 0, c.display_number

**Comment by rsiebert** [comment]
The changes with the pull requiret do not work. It will not compile.

**Comment by rsiebert** [comment]
This seems to work

`CASE :sortOrder WHEN 6 THEN CASE (c.display_number + 0) WHEN 0 THEN 999999999 ELSE (c.display_number + 0) END END ASC`

**Comment by rsiebert** [comment]
I have added support for the channel number sorting in the newest app version [2.2.22-183](https://drive.google.com/open?id=1SQjGTnmp0_4biSjz-wYOaiZ0BdQCKaQK) Can someone test it?

**Comment by Niklas04** [comment]
I did a quick test and it seems to work :D

**Comment by Curly060** [comment]
> This seems to work
> 
> `CASE :sortOrder WHEN 6 THEN CASE (c.display_number + 0) WHEN 0 THEN 999999999 ELSE (c.display_number + 0) END END ASC`

Yes, this does. 
Unfortunately that's not what's in d95f3aa7fba147469735be176cde692af36ff846

Could you please check again? Thanks!

**Comment by Flole998** [comment]
@rsiebert This did indeed break the functionality, I used one of the betas you posted in one of the other issues and that option is completely broken now. While you actually had the right solution you somehow committed something different.

**Comment by rsiebert** [comment]
I have added the correct fix and pushed it. I'll provide a testversion in the next days

**Comment by rsiebert** [comment]
Here is a new upcoming test version [2.3.0](https://drive.google.com/open?id=1oHT6Tv8UicnsFkvGLAzJHnkWFZ87J7P5). Can you check if it works now?

**Comment by Flole998** [comment]
Works great now, thanks!
