### ISSUE TITLE
TVHClient for users without play store/services

### ISSUE THREAD

**Issue by chri2** [rsiebert/TVHClient#416]
Thanks for the great App. I would've bought the 'extras' version some time ago if there'd be a way to do it without google.

Since my last phone broke, I "downgraded" from an old Sony z3c to an even older Sony Z1 running CarbonROM to get a maintained android system. CarbonROM comes without any Google Services pre-installed and so far I didn't need any.

Even Aquamails registered version does work without Google Services. All other apps come from F-Droid.

I'd really love to use an official build (ready made apk) of TVHClient from F-Droid or from a download page as long as I wouldn't have to install any google software. I'd like to pay for it since I value the work done for this great piece of software.

Is there any chance that TVHClient will become available for users who do not want to be part of the google-is-collecting-your-data-universe (or at least as little as possible)? I' apreciate it immediatly and buy at least three extra versions for my mobile devices.

**Comment by dadosch** [comment]
related: https://github.com/rsiebert/TVHClient/issues/311 https://github.com/rsiebert/TVHClient/issues/163

I've created a fork with a name different from TVHClient from which I removed all google stuff, and that should(TM) be ready to build for f-droid.

* I had to remove ExoPlayer, as it didn't built from source with a current Gradle version.
* Cast support removed
* Billing suport removed

I can see, that there is the possibility to add a donations button to the f-droid entry:
```
We have fields in our metadata for Bitcoin, Litecoin, Flattr and Liberapay donations. Be sure to contact us if there is a change to any of those or if you stop accepting them; if you accept new methods you can contact us about that too.
```

I suggest to add a donation button in favour of @rsiebert .

To get a list:
* ~~Internal player~~
* Add or edit timer recordings
* Fine tune and edit your series recordings
* Fine tune and edit your scheduled recordings
* ~~Search as you type~~ not removed on purpose, but doesn't work for me with my stripped down build
* Notifications
* ~~Google Cast™-enabled, send your Live-TV or recordings to your Chromecast~~
* Download recordings

Is that OK, for you @rsiebert or should all these features on the list be disabled?

We could also use a [build flavour](https://developer.android.com/studio/build/build-variants) in this (official) repo which has the required changes (I think this would be the best solution).

Do you, @rsiebert , the original app author, support the inclusion in f-droid?

**Comment by rsiebert** [comment]
@dadosch Using a build flavour seems reasonable to me. Please provide a pull request so that I can create the release and upload it to f-droid.

I'm not quite sure about the inclusion of a donate button. A very popular app from Germany (Öffi Verbindungen) was temporarily removed from the play store because of a donate button in the app that was released on f-droid. The same app in the play store did not have the donate button.

**Comment by dadosch** [comment]
> I'm not quite sure about the inclusion of a donate button. A very popular app from Germany (Öffi Verbindungen) was temporarily removed from the play store because of a donate button in the app that was released on f-droid. The same app in the play store did not have the donate button.

Sicher? So wie ich das mitbekommen habe, ist Öffi erst aus dem Play Store gefallen und wurde dann Open Source Software, vorher konnte es also ja gar nicht in F-Droid sein... https://www.heise.de/newsticker/meldung/Oeffi-wird-Open-Source-und-landet-auf-F-Droid-4112915.html

(I meant not an donate button in the app, but on the f-droid page.)

I will prepare the PR in the next few days.

**Comment by rsiebert** [comment]
Ah so war das. Na ich möchte nicht aus dem Play Store fallen. :-)

I'm looking forward for the pull request

dadosch <notifications@github.com> schrieb am Mo., 4. März 2019, 16:00:

**Comment by chri2** [comment]
@dadosch Great! Thanks a  lot! 

@rsiebert I donated during the last weeks to at least five projects around android and protecting user data (blog, carbon, afwall, netguard). There are companies out there that base their business modell on protecting the rights of users (search for Puri.sm e.g.) and they seem to be succesfull so far.

I guess you could be part of that movement quiet easily now by agreeing with the offer to integrate the changes of @dadosch in your repository.

BTW: afwall+ e.g. is also on play store with an optional pay version and on fdroid with a donate function. NetGuard also. Both great projects. You could ask their developers if they'd share some experience with you about the return for their work from f-droid and possible problems with google.

Thanks again for that great app!

**Comment by dadosch** [comment]
My changes are here: https://gitlab.com/dadosch/tvhlibreclient

It will be quite some work to avoid duplicate code, so I will start in the next few weeks.

**Comment by chri2** [comment]
Any news here?

**Comment by rsiebert** [comment]
Not yet, I still have some small issues to fix then I can start working on this app flavour

**Comment by github-k8n** [comment]
It's been half a year, any news on this?

**Comment by Spielmops** [comment]
A whole year later: anything new?

Spielmops

**Comment by rsiebert** [comment]
No news here. No time to implement the feature.
