### ISSUE TITLE
[SOLVED] Not showing artwork/poster in program details

### ISSUE THREAD

**Issue by nickiman** [rsiebert/TVHClient#417]
Hi,

Since the latest updates of TVHClient I´ve noted that the images of the programs are not showed in the details.

First, here the details of the setup:

_**Server API version: 33 (Server: Tvheadend 4.3-1391~g852a10a34)
TVHClient version: 2.1.0 (04.02.2019)**_

You can see how the images are showed in broadcast details in Tvheadend:
![broadcast_details](https://user-images.githubusercontent.com/3627902/52917838-325ce780-32f0-11e9-98de-a9ec865a6d28.PNG)

And in TVHClient is showed without the image.
![tvhclient_details](https://user-images.githubusercontent.com/3627902/52917847-4274c700-32f0-11e9-964e-a1871504f4c7.png)

I think this function is correctly enabled in the settings, and the additional features were purchased several years ago.
![enabled_function](https://user-images.githubusercontent.com/3627902/52917856-4dc7f280-32f0-11e9-99d5-eea130f4d108.png)

After several tries I´ve reinstalled the APP in my device from scratch but without success.

This issue is related with this one: #264 and, not sure if #414 also, because this talks about Image Cache in Tvheadend which I don´t have it enabled in my system.

Feel free to ask me anything else to help to troubleshoot this.

Thanks and best regards

**Comment by rsiebert** [comment]
Is this working?

**Comment by nickiman** [comment]
Hi @rsiebert 

Yes, it works in the latest version... But, the picture now is really small IMHO, look:

![imagen](https://user-images.githubusercontent.com/3627902/53703289-a4651e80-3e10-11e9-86c5-03bca9ec9610.png)

What do you think?

**Comment by rsiebert** [comment]
Can you test the link to the app version 2.2.2-156 in #430? It contains a fix for the image with.

**Comment by nickiman** [comment]
> Can you test the link to the app version 2.2.2-156 in #430? It contains a fix for the image with.


I´ve just installed it in my phone, it seems that nothing has changed, look:

![imagen](https://user-images.githubusercontent.com/3627902/53945396-d4871880-40c1-11e9-990c-e2615c1d6b4f.png)

May I have to do anything else in the settings of server/TVHClient? This is the version installed:

![imagen](https://user-images.githubusercontent.com/3627902/53945319-a4d81080-40c1-11e9-9b25-f898df966c49.png)

**Comment by rsiebert** [comment]
Is this working in 2.2.3 as expected?

**Comment by nickiman** [comment]
Hi,
Yes, now pictures are big again...
![imagen](https://user-images.githubusercontent.com/3627902/54548381-15c3d600-49a8-11e9-9d36-1f849c6f4401.png)

So for me It´s fixed. I´ll close this issue.

Thank you!
