### ISSUE TITLE
Programs are displayed twice again

### ISSUE THREAD

**Issue by AlBundy33** [rsiebert/TVHClient#418]
This was reported in #375 and #395 and already fixed but since one of the latest versions this issue occured again. :-(

![screenshot_20190218-230334](https://user-images.githubusercontent.com/6294586/52979017-0e72d200-33d4-11e9-93cc-6feac19529c1.png)

**Comment by rsiebert** [comment]
No changes were done in the last versions regarding this. The app inserts a new program only when the id is new and updates an existing program when the id is the same. So duplicate entries can only occur when the id is different. I still don't know why this happens. Looking into it.

**Comment by Niklas04** [comment]
I have the same problem. Sometimes programs are displayed more than once.
Noticing that the start time, end time or duration is different.
Some of the duplicates seems to be "dummys". If I press "Record" nothing happens.

<img src="https://user-images.githubusercontent.com/33813894/53871275-3e3cef00-3ffc-11e9-8e8c-a4fe2b6d572f.png" width="400">

Even noticed that the programs in the "Program guide" are moved and don't match with the timeline. 
~~Maybe~~ this is an effect of this issue.

<img src="https://user-images.githubusercontent.com/33813894/53871399-7a704f80-3ffc-11e9-8e83-7ec5debe6740.png" width="400">

Using:
LibreELEC 9.0.1
Tvheadend 4.2.7-44

TVHClient-App 2.2.1
Android 9 (tested also with 8.1.0)

Edit: I tested to clear storage of the app. After that, I don't see any duplicates. But I think they will come back.

**Comment by rsiebert** [comment]
Version 2.3.0 will start to remove duplicate programs in the background after one minute

**Comment by rsiebert** [comment]
2.3.1 was just released, so I'll close this issue. 
Please reopen if the problem persists.
