### ISSUE TITLE
"Anfordern von Wiedergabeinformationen vom Server" hangs again

### ISSUE THREAD

**Issue by AlBundy33** [rsiebert/TVHClient#419]
This issue was reported in #393 and occures again since one of the latest version.
If I end a stream st one night and stsrt tvhclient next day evening the first playback always fails. 
Then I have to closet the app (swipe it out of the running app-overview - nit sure how this is called), start tvhclient again and successfully start a stream. 

Btw.: what important Informations are loaded? I'm in my own lan and using an external player.

**Comment by rsiebert** [comment]
The internal player requires a ticket (a bunch of random characters) from the server that is then passed to the external player in the playerback url. The server then accepts the external player as authenticated and delivers the data. Without this the username and password would need to be with the playback url. This only works when basic auth is enabled in the server, not with digest authentication. So getting the ticket is the best solution.

This only occurs when the connection to the server was closed during the night and the app didn't get this somehow. I'll check this.
