### ISSUE TITLE
TVH Client crash TVHeadend server.

### ISSUE THREAD

**Issue by RAJensen** [rsiebert/TVHClient#420]
Hello.

I'm not sure when this issue was applied to TVH Client, but i did get a notice when i was opening TVH Client yesterday (2019-02-21), that it has been updatet.
Unfortunally there is a big issue with the this update.
I first discovered it as i wanted to make a recording. But ir was impossible. I used to just pick up the program in the guide and then press recording and that's was all. 
Last night i wanted to create a recording schedule. But that was not possible. No recording schedule is createt.
Then I tried to make it manually but it was the same result.
Today when i got home and wanted to listen my radio, nothing happend. Strange! I did restart the TVHead server and every thing was fine.
Tonight i'm trying to use the tv guide in TVH Client and then TVHeadend server stop streaming my tv channel?!?
I did a restart and it was running again until I open up the TVH Client then the server went down again.
So for some reason the latest official release by Google Play store simply crashes the TVHeadend server. :-(
Is it possible to roll back that release so the last one working could be released again in Google Play Store? Please...
As i remember it, this is not the first time a new release of TVH Client makes my TVH Server go down.
I'm using TVHeadend server version 4.1-1350 running on RPi 2. There is no other use on the Rpi than TVHeadend Server.

**Comment by RAJensen** [comment]
I found this in log on TVHeadend server web:
019-02-21 19:49:39.795 htsp: 192.168.0.17: Welcomed client software: TVHClient (HTSPv31)

2019-02-21 19:49:39.800 htsp: 192.168.0.17 [ TVHClient ]: Identified as user 'Android'

2019-02-21 19:49:39.800 htsp: 192.168.0.17 [ Android | TVHClient ]: Privileges updated

2019-02-21 19:49:47.532 htsp: 192.168.0.13 [ Xbian_user | Kodi Media Center ]: Write error -- Broken pipe

Thats happends a few seconds after TVH Client has log on and retrived the program guide.

**Comment by rsiebert** [comment]
Version 2.2.0 has just been released. Please check if the issue is solved in this version.

**Comment by RAJensen** [comment]
Hi Robert.

I've just updated TVHClient from google Play to 2.2.1
The problem persist. 5 seconds after TVHClient connects to TVHeadEnd server, the server freeze.
When the test is done Kodi media center is using a stream from server.

Log from server:
2019-03-02 14:06:28.850 htsp: Got connection from 192.168.0.17

2019-03-02 14:06:28.852 htsp: 192.168.0.17: Identified as user 'Android' (unverified)

2019-03-02 14:06:28.852 htsp: 192.168.0.17 [ Android ]: Welcomed client software: TVHClient (HTSPv32)

2019-03-02 14:06:28.872 htsp: 192.168.0.17 [ Android | TVHClient ]: Identified as user 'Android'

2019-03-02 14:06:28.872 htsp: 192.168.0.17 [ Android | TVHClient ]: Privileges updated

2019-03-02 14:06:36.472 htsp: 192.168.0.13 [ Xbian_user | Kodi Media Center ]: Write error -- Broken pipe

**Comment by rsiebert** [comment]
Which server version is used?
Is there a more detailed debug log from the server? Can you also send me
the debug log from the app please?

Am Sa., 2. März 2019 um 14:10 Uhr schrieb RAJensen <notifications@github.com

**Comment by RAJensen** [comment]
Server version: 4.1-1350~gdfae393

You got me into deep water regarding the debug log from TVH server. I tried to change setting for debug level and log but nothing happends after a restart, so I can't provide you with that log. In the Web GUI i did change "debug to syslog" but the message in syslog is the same as i posted last time.

I have did turn on debug in TVHClient and sendt the log after the server went down using the build in "send log".
I hope it can help you.

**Comment by rsiebert** [comment]
The app log was quite informative. The first connection to the server to get all data and so on is ok. Then the app tries to open a second connection to the server to load additional epg data in the background. There the connection cant be established. Maybe your server with api version 25 can't handle multiple connections. I'll create a test app without loading additional data in the background. I'll post it here then.

**Comment by rsiebert** [comment]
Here is a test version.
[2.2.2-153](https://drive.google.com/open?id=1Mxc9GsconZzyoYBZ2lMtMCCS0hVeHUgj)

**Comment by RAJensen** [comment]
I test it and there is still a feeze.
I've got log fron RPi: daemon log, syslog and debug log. 
I'm not sure if they will help you. Would you like to have them on email?

**Comment by RAJensen** [comment]
I don't know about the multible connection.
But in the past i've been running ie. tv-channel on Kodi and used TVHClient at the same time.
So i was watching a tv show and programmed a recording with TVHClient. Sometime i've been using Kodi media center and also connectet my computer to TVHeadEnd sever and TVHClient at the same time.
Just as an test and it was all working. :-)

**Comment by rsiebert** [comment]
Here is another test version that does not use the http api proxy call. Maybe this could be a problem.
[2.2.2-155](https://drive.google.com/open?id=1kaAR6fgpbVyjSsu8ZW94BbyYvcjaWrGd)

**Comment by RAJensen** [comment]
Hi Robert-
Sorry for my late respons. I did't see you have createt a new version.
Yes..!
2.2.2-155 is working again.
No freezes, tv-guide is running and it's able to make recording schedule again.

Thank you very much.

**Comment by rsiebert** [comment]
My strong guess is that this is related to fetch the http profiles via the htsp api proxy call.
I have added a check that this is only done when the server api version is >= 26.
Please try this version which only disables this specific call.
[Version 2.2.2-156](https://drive.google.com/open?id=1Bq0XOCdLMoA6N4A_okXmEJtZKtqUeGu1)

**Comment by RAJensen** [comment]
Hi Robert.
Just done a test with 2.2.2-156 and it seems to work fine.
No freezes, program guide working nice and i'm able to make record schedule and erase it again.
Testet it with Android 8.0 on Huawei Mate 10 Lite.

**Comment by rsiebert** [comment]
Thanks for helping me finding the issue!
