### ISSUE TITLE
Searching epg shows no results when there are plenty of them

### ISSUE THREAD

**Issue by chpasha** [rsiebert/TVHClient#423]
Clean installation of 2.2.0, sync with Backend is complete, channels are showing, epg is there. But the simple search for 'Бавария' brings no results. I've put my laziness aside and copied the tvh database to my PC to check what is inside

`select * from programs where title like '%Бавария%'`

finds 22 results

![image](https://user-images.githubusercontent.com/9569489/53681709-ab474080-3ced-11e9-99b9-295f53a7c7f4.png)

I'm attaching the database, maybe you can reproduce the issue. 
[tvhclient.zip](https://github.com/rsiebert/TVHClient/files/2922058/tvhclient.zip)

**Comment by rsiebert** [comment]
Where did you start the search? From the channel screen or epg?

**Comment by chpasha** [comment]
I tried it from the channels screen, as I always did in the old one. After you question I also tried to search in EPG screen, but it never completes. It either spins forever or I get ANR. I observe same behavior both on real device and on genymotion emulator with android 7.

**Comment by chpasha** [comment]
When going to EPG page - I'm observing multiple Throwing OutOfMemoryError "Failed to allocate a 16396 byte allocation with 15088 free bytes and 14KB until OOM" from org.tvheadend.tvhclient on Emulator

**Comment by rsiebert** [comment]
Maybe I should change the channel screen behaviour back to the old one. Currently only channels and the current and next program are searched for.

**Comment by chpasha** [comment]
Yes, I think it would be better since searching for a broadcast is imo a way more common action than searching for a channel. I think the search should find both channels and epg events on both screens

**Comment by rsiebert** [comment]
The new version 2.2.11 will search for all programs from the channel list. Not only for channels and the current programs.
