### ISSUE TITLE
Timer recordings start/stop times wrong with API 19

### ISSUE THREAD

**Issue by virtualdj** [rsiebert/TVHClient#424]
I have a second old TVHeadend server that I cannot update. TVHClient recently (maybe with the version that changed the UI) displays wrong start/end time for the items on **Timer recordings,** while all the other panels are correct.

Screenshots below:
![tvhclient](https://user-images.githubusercontent.com/3251704/53694304-4521f280-3dad-11e9-9c31-ec3f4aa53c89.png)

Using a more recent version of TVHeadend this does not happen, but TVHClient worked correctly with this TVHeadend version too.

**Comment by rsiebert** [comment]
Is this still an issue with 2.2.2 or 2.2.3?

**Comment by virtualdj** [comment]
No, it is not!
Now with v2.2.3 the issue has been corrected. Thank you very much!
