### ISSUE TITLE
TVHClient crashing TVheadend Server in docker container

### ISSUE THREAD

**Issue by bajoodoo** [rsiebert/TVHClient#426]
I waited now for 5 iterations of the new client software but my problem also still persist that the client seems to be crashing the server right after trying to start a recording. I have to manually restart the server to get access to it again. The last version of 1.9 still works, allows me to start recordings, and also allows me to watch the live program via MX Player.
The docker container version I am using is https://hub.docker.com/r/netzfisch/tvheadend/ on a Raspberry Pi 3b.
I'll be trying to provide some logs soon.

**Comment by bajoodoo** [comment]
The lines right before crashing ie disabling access are...
,2019-03-03 14:16:50.105 [   INFO] subscription: 0067: "epggrab" unsubscribing
2019-03-03 17:21:54.324 [   INFO] htsp: Got connection from 192.168.0.138
2019-03-03 17:21:54.386 [   INFO] htsp: 192.168.0.138: Identified as user 'couchpotato' (unverified)
2019-03-03 17:21:54.387 [   INFO] htsp: 192.168.0.138 [ couchpotato ]: Welcomed client software: TVHClient (HTSPv32)
2019-03-03 17:21:54.493 [   INFO] htsp: 192.168.0.138 [ couchpotato | TVHClient ]: Unauthorized access

After that the servers becomes and stays unresponsive until docker restart TVheadend

**Comment by rsiebert** [comment]
Related to #420

**Comment by rsiebert** [comment]
I have uploaded a test version in ticket #420. Please try it and tell me the outcome.
The issue seems to be related to server version 4.1

**Comment by rsiebert** [comment]
Issue is solved in #420
