### ISSUE TITLE
Channel Tags filter doesn't work properly

### ISSUE THREAD

**Issue by Speederer** [rsiebert/TVHClient#427]
Hi,
The channel filter by tags shows my channel lists properly, but some of them shows more channels than needed.
Here are 2 pictures of them:
![screenshot_2019-03-04-18-09-27-772_org tvheadend tvhclient](https://user-images.githubusercontent.com/10748133/53750349-d4143500-3ea9-11e9-8562-6f29788e7fbc.png)
![screenshot_2019-03-04-18-11-23-739_org tvheadend tvhclient](https://user-images.githubusercontent.com/10748133/53750373-e1c9ba80-3ea9-11e9-9477-008588b214f3.png)

Besides these the radio channels list my all channels (707), but the filtering for other (original) tags works fine, like All, HDTV, SDTV, TV channels.
I am using the 4.2.7-44 TVH server and the latest (2.2.1) version of TVHclient.

Anyway this function works fine with other TVH client android app.

**Comment by rsiebert** [comment]
Is this still an issue?

**Comment by rsiebert** [comment]
Closing due to no reply. Working here properly with three servers and version >= 2.2.14
