### ISSUE TITLE
EPG access messed up

### ISSUE THREAD

**Issue by NotCommonUser** [rsiebert/TVHClient#430]
Steps to recreate
- open EPG
- search for program (results already look bad)
- click on an entry - it is then displayed with no controls to schedule recording.

I have some screenshots of this... But no way to put it here

**Comment by rsiebert** [comment]
This should be fixed in [2.2.2-156](https://drive.google.com/open?id=1Bq0XOCdLMoA6N4A_okXmEJtZKtqUeGu1)

**Comment by rsiebert** [comment]
Closing due to working again
