### ISSUE TITLE
problem downloading recordings

### ISSUE THREAD

**Issue by cafs78** [rsiebert/TVHClient#431]
When i try to download a recording it always gives an error about wrong or missing authentiaction but if i use same user on tvheadend web interface (actually it is super user) i can download recordings without problem

**Comment by rsiebert** [comment]
Which http authentication did you endlessly? Digest only? You need to enable both basic and digest authentication.

**Comment by cafs78** [comment]
Enabling basic and digest solved the issue.

thanks
