### ISSUE TITLE
App closes directly after server connect since v 2.2

### ISSUE THREAD

**Issue by jupe76** [rsiebert/TVHClient#432]
On my android devices the tvhclient app closes directly after server connect.
For me it seems that this happens since upgrading to v 2.2.

Uninstalling and reinstalling tvhclient did not help.

I alternativly tried "another" android tvhclient app (com.dimafon.tvhclient), this still works without issues.

My devices are a pixel 3 with android 9 and a samsung s3 tab with android 8.1, server is tvh 4.3-1781 (arch AUR).

In the server logs I can see a successful connect and directly afterwards a disconnect and broken pipe.
I have the feeling that there is some stale tvhclient database that causes the issues. 
If I uninstall and reinstall tvhclient I would expect that there are no settings and informations left over, but the connect settings and some information about autotimers and channels seems still to be there.
I have verified that the folder android/data/org.tvheadend.tvhclient was properly deleted, so this left over information must be saved somewhere else, but I have no idea where.

Serverlog (first entries are a successfull connect from (com.dimafon.tvhclient):

    Mar 10 11:02:18 vdrtwo tvheadend[3984]: htsp: 192.168.178.40: Identified as user 'tvh' (unverified)
    Mar 10 11:02:18 vdrtwo tvheadend[3984]: htsp: 192.168.178.40 [ tvh ]: Welcomed client software: com.dimafon.tvhclient (HTSPv8)
    Mar 10 11:02:18 vdrtwo tvheadend[3984]: htsp: 192.168.178.40 [ tvh | com.dimafon.tvhclient ]: Identified as user 'tvh'
    Mar 10 11:05:46 vdrtwo tvheadend[3984]: htsp: 192.168.178.40 [ tvh | com.dimafon.tvhclient ]: Disconnected
    Mar 10 11:05:49 vdrtwo tvheadend[3984]: htsp: Got connection from 192.168.178.40
    Mar 10 11:05:49 vdrtwo tvheadend[3984]: htsp: 192.168.178.40: Identified as user 'tvh' (unverified)
    Mar 10 11:05:49 vdrtwo tvheadend[3984]: htsp: 192.168.178.40 [ tvh ]: Welcomed client software: TVHClient (HTSPv32)
    Mar 10 11:05:49 vdrtwo tvheadend[3984]: htsp: 192.168.178.40 [ tvh | TVHClient ]: Identified as user 'tvh'
    Mar 10 11:05:49 vdrtwo tvheadend[3984]: htsp: 192.168.178.40 [ tvh | TVHClient ]: Disconnected
    Mar 10 11:05:49 vdrtwo tvheadend[3984]: htsp: 192.168.178.40 [ tvh | TVHClient ]: Write error -- Broken pipe

How can I help to debug the problem?

**Comment by jupe76** [comment]
Now I have reinstalled a tvhclient v 2.0.0 apk somewhere from the internet (yes I know: it's dangerous) to my pixel 3 and voila: It's working again.
So its definitly the new version that causes the problems for me.

**Comment by rsiebert** [comment]
Did the behaviour change with 2.2.3?

**Comment by jupe76** [comment]
Unfortunally not, it still crashes after connecting to the server.
I've send you a new logfile.

**Comment by rsiebert** [comment]
Unfortunately I can't get enough inform from the log. Is it possible to get a temporary account on your server? Then I can see where it crashes in the app.

**Comment by jupe76** [comment]
I have good news and bad news:
The good is that the crashes are no longer occuring with v 2.2.3 right now.
The funny thing is that they definitly did with v 2.2.3 when it was released (I've sent you a log as proof).
Also with versions < 2.2.0 the problem did not show up.

So I wonder whats the reason that the problem has disappeared silently.
I have to admit that I'm fairly new to tvheadend /kodi. I've used a VDR only system for the last decade(s) and switched to tvh / kodi at the beginning of 2019.
So I'm still experimenting with the settings somewhat.
Something that might affect the crashes I had is that I've changed the epg-provider recently.
I've used tvzon.se (which provides also a german epg) and switched to the probabilly more common "Fertiges DE + AT + CH XML EPG" from deBaschdi / takealug.de recently.

So you can consider this ticket closed.

The bad news is: I've still crashes with v 2.2.3, now they occur when I go into the detailed description of a broadcast (I've already sent you a debuglog yesterday) . I'll watch this issue and maybe open a new issue for it.
