### ISSUE TITLE
Program-Icons are not displayed

### ISSUE THREAD

**Issue by Niklas04** [rsiebert/TVHClient#433]
Having the problem that the program-icons aren't displayed.
The issue occured since one of the last updates

<img src="https://user-images.githubusercontent.com/33813894/54532965-68da6080-4989-11e9-8561-a084dfa1992a.png" width="400">

Using:
LibreELEC 9.0.1
Tvheadend 4.2.7-44

TVHClient-App 2.2.2
Android 9 (tested also with 8.1.0)

**Comment by rsiebert** [comment]
Please try the new version [2.2.4-159](https://drive.google.com/open?id=1_UTjEZualXgx-feeqnjOrTVx20FzkerX) and send me the debug log. Then I can investige whats going on.

**Comment by Niklas04** [comment]
Thanks, I installed version 2.2.4-159.
I cleared the database and pressed 'Reconnect', to force the symbols to download.

[tvhclient_2.2.4_159_22.03.2019.log](https://github.com/rsiebert/TVHClient/files/2998109/tvhclient_2.2.4_159_22.03.2019.log)

**Comment by brimur** [comment]
It may be unrelated but I see this issue also for all non admin users. If I login as a non admin I get no icons in the app but if I login as an admin I get the icons

**Comment by rsiebert** [comment]
Can you try the testversion [2.2.4-160](https://drive.google.com/open?id=13kjcjVF0gLGu8qOs29Pmbi41D7J1K-LM)

**Comment by brimur** [comment]
With 2.2.4-160 installed this is what I see...
The only difference from previous versions is that text now appears instead of the picon.
Also, I had debug enabled on the TVH server and there were no error messages.

![image](https://user-images.githubusercontent.com/8918706/54931297-a05c8600-4f10-11e9-9d4a-0db4006d6433.png)

**Comment by Niklas04** [comment]
With new version 2.2.4-160, I see this:
<img src="https://user-images.githubusercontent.com/33813894/54933160-672a1300-4f1c-11e9-9c68-2365ba42fffc.png" width="400">

@brimur How can I login as Admin?
In the Tvheadend settings, I have the default-"user" ("*") with access to the Web-Interface and admin-permissions. Do I have to set some other settings?
Even a new user with admin permissions and password don't lead to the same result as you posted

**Comment by brimur** [comment]
@Niklas04 My default user (*) is disabled and does not have admin privileges. I created an account called Admin and ticked the Admin checkbox and created a password for that account. I also created a non-admin account, also with a password. I am using server version 4.3-1774

**Comment by rsiebert** [comment]
Is this admin / regular user a permission issue by the server,? Admin is allowed to read the files in the icon path and the regular user not?

If only the channel name is displayed it means that the icon could not be loaded.

**Comment by brimur** [comment]
I think it is a bug and I might have figured it out. You need to grant HTSP rights under Users > access Entries -> Video Recorder tab to access the picons.

![image](https://user-images.githubusercontent.com/8918706/54946750-b37f4e00-4f30-11e9-8aad-4473932ab933.png)


![image](https://user-images.githubusercontent.com/8918706/54946702-9fd3e780-4f30-11e9-991d-0a907635aa89.png)

**Comment by Niklas04** [comment]
I now figured out the problem.
Somehow my Icons got messed up. Don't know how this happened, but I deleted all Icons and replaced them with new ones.
Now the Program-Icons are displayed in TVHClient-App with Admin- and Non-Admin-User (with HTSP rights).

Thank you for your help!
