### ISSUE TITLE
Everything in the UI is justified right.

### ISSUE THREAD

**Issue by binhex** [rsiebert/TVHClient#434]
So since the latest update on Google Play everything in the ui is justified right, please can you take a look at this, screenshot:-

https://drive.google.com/file/d/1Qk4sQESv_yEeaewssPlXuKFh89PKSkh6/view

**Comment by rsiebert** [comment]
Someone else having this problem? I can't reproduce this on my two devices running Android 8.

**Comment by binhex** [comment]
just a bit more detail, as this is obviously not affecting many people (assumed it was):-

App Version:- TVHClient 2.2.3 (158)
Android:- 8.1.0
Phone:- Huawei P20
Screen:- 2244 x 1980

There have been no system updates applied to this phone so im confident its not android/huawei updates that have caused the issue. This definitely started happening on the latest update, prior to that it was fine.

The justification is present in all settings screens, details screen for any show, all *recordings screens, the only screen that does look ok is the program guide screen.

**Comment by binhex** [comment]
ok decided to bite the bullet and clear cache and data for TVHClient, this did the trick!, so bit of a pain but hey it didn't take me too long to reconfigure, not sure what caused it but i am a VERY long time user (purchased your app years ago) of your app so perhaps conflicting configuration over time caused the issue *shrug*, either way i am closing this out as i have a fix.
