### ISSUE TITLE
App on tablet no longer shows split screen

### ISSUE THREAD

**Issue by brimur** [rsiebert/TVHClient#435]
I was having issues playing streams on my tablet so I uninstalled and reinstalled from the Play store and now the tablet interface looks like my phones interface but all the text is left aligned and looks terrible.

**Comment by rsiebert** [comment]
Which version did you use? 2.2.2 or 2.2.3?

**Comment by brimur** [comment]
I am using 2.2.3 (158)

I downloaded the 2.2.2 apk and the same issue is present

**Comment by brimur** [comment]
Actually had to go back to 1.9 to get the split screen back but now my streams won't play again so I'll upgrade back to 2.2.3

**Comment by rsiebert** [comment]
What tablet and screen size do you use? The app uses certain information to determine if split screen shall be used.

**Comment by brimur** [comment]
I have a Huawei T5 with a 1920 x 1200 screen. It split screens on v1 but not on any of the v2 APKs I tried

**Comment by rsiebert** [comment]
Can you try the new version [2.2.4-159](https://drive.google.com/open?id=1_UTjEZualXgx-feeqnjOrTVx20FzkerX)

**Comment by brimur** [comment]
@rsiebert The split screen is back, thanks very much. I have the purchased app on both my phone and my tablet but the channel icons only show on my phone. I went to the app settings on both and cleared the cache and storage and set them both up as if it was a clean install. The icons showed on my phone again straight away but not on the tablet (I'm using picon:// btw). Not a huge deal and I see it is already logged as an issue by someone else. Thanks again for getting that fixed, looks great with the split screen.
