### ISSUE TITLE
App crashes when displaying the detailed description of a broadcast

### ISSUE THREAD

**Issue by jupe76** [rsiebert/TVHClient#436]
This error description applies to version 2.2.3.

The app reproducible crashes here when trying to display the detailed description of a broadcast AND the option "Show program artwork/poster" under settings/user interface is NOT checked.

If the option "Show program artwork/poster" is checked, everything works well, then the detailed description of the broadcast with the poster is shown.

**Comment by rsiebert** [comment]
Can you try the testversion [2.2.4-160](https://drive.google.com/open?id=13kjcjVF0gLGu8qOs29Pmbi41D7J1K-LM)

**Comment by jupe76** [comment]
Have tried 2.2.4-160, it does not really solve the problem for me.
Now you can uncheck the "Show program artwork/poster" option, but the poster will still be shown.
The option now doesn't seem to have any effect anymore.

**Comment by rsiebert** [comment]
The option should be fixed in [2.2.4-161](https://drive.google.com/open?id=1fst8XpoTojFrdw4t3VwaJWt5F4sY0ty7)

**Comment by jupe76** [comment]
Works as expected now, thanks!
