### ISSUE TITLE
No logos on channels 

### ISSUE THREAD

**Issue by paulsavo1** [rsiebert/TVHClient#437]
Hi can someone please help, i have tvh setup on the client but im not getting any channel logs and when i switch to epg view i dont even have a channel name, i have this setup on numerous other apps, web and kodi and dont get this issue

any ideas

thanks

![Screenshot_20190326-152443_TVHClient](https://user-images.githubusercontent.com/11887490/55010582-59d45d80-4fdc-11e9-8347-48b2e6911080.jpg)
![Screenshot_20190326-152455_TVHClient](https://user-images.githubusercontent.com/11887490/55010583-59d45d80-4fdc-11e9-83f4-b5f8ce941cd4.jpg)

**Comment by Brausmith** [comment]
Edit: Ignore the below comment, the icons all of a sudden started to show. Weird.
--------------
Just installed it today, and everything is working great except I have no channel icons. Mine is exactly as the OP images above. I know the icons works because they are coming through on TVHeadEnd GUI and on Android TV.
There is also no setting to toggle icons.

**Comment by paulsavo1** [comment]
mine still not working

**Comment by rsiebert** [comment]
You should be able to see channel names in version [2.2.4-161](https://drive.google.com/open?id=1fst8XpoTojFrdw4t3VwaJWt5F4sY0ty7) in case the icons could not be loaded

**Comment by paulsavo1** [comment]
apologies for ignorance but how do i install the github version, i had been using playstore but it is only version 2.2.3, but when extract the download on github there is no apk file

**Comment by brimur** [comment]
@rsiebert Was thinking the same about the Playstore, when do you think 2.2.4 will be available there?

**Comment by rsiebert** [comment]
I have released the 2.2.4 version to 10% of the user base. Is the version in the link working as expected?

**Comment by paulsavo1** [comment]
i have only got the 2.2.3 and it is not

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by paulsavo1** [comment]
apologies i didn't realise that was a link to download.. yes it now gives names thanks

**Comment by rsiebert** [comment]
This might be a dupliate of #456. Closing this issue
