### ISSUE TITLE
Background playing of audio

### ISSUE THREAD

**Issue by Brausmith** [rsiebert/TVHClient#438]
If possible, I would like to turn off the screen but then still keep the audio playing. And hopefully also without the video data being sent to reduce network traffic.
The reason, I like to listen to news / current affairs shows during my daily car commute.

**Comment by rsiebert** [comment]
This is not possible afaik because the server is responsible for providing the video and audio data for each channel. Or maybe you find a way to create a server profile that only provides audio. Then the player will only play audio. Keeping the audio on can then be the next step.

**Comment by rsiebert** [comment]
Closing because this feature request will not be added.
