### ISSUE TITLE
Search takes very long (2-3 minutes)

### ISSUE THREAD

**Issue by Flole998** [rsiebert/TVHClient#439]
When I'm in the program overview and enter a search query it starts loading and loads for 2-3 minutes. Thats really slow and to be honest I am not using the App due to this at the moment.

**Comment by rsiebert** [comment]
How many programs are in the database? Maybe the querying of the database takes too long. Is this also the case when you search in the program list of a single channel (not the epg)?

**Comment by Flole998** [comment]
There are 74005 Events in the database on 773 Channels. Searching on a single channel is faster.

Maybe it can be improved by not making one search but doing one search per day, so if I search now it first searches for events taking place today, then for tomorrow and so on while already displaying the results it found (and a loading indicator that it is still busy).

I will email you the logs in a few minutes.

**Comment by rsiebert** [comment]
Is the search still taking that long?

**Comment by Flole998** [comment]
I just tried it and it seems to be a little bit better, still takes half a minute and what is really bad is that there is no progress bar shown: The search results page opened and I thought it didnt find anything while it was still searching.

**Comment by rsiebert** [comment]
Here is the upcoming version [2.3.0](https://drive.google.com/open?id=1oHT6Tv8UicnsFkvGLAzJHnkWFZ87J7P5). I have changed some search stuff in the app. Does it improve the speed?

**Comment by Flole998** [comment]
Now I am seeing almost instant results, however that is just the case when the first search completed after about 30 seconds. Is there maybe fetching of more information going on in the background? Can there be some kind of indicator in that case so I know that it is still waiting for something to complete in the background, just like when I do a complete reconnect?

**Comment by rsiebert** [comment]
I will add a loading indicator when the search is active

**Comment by rsiebert** [comment]
Here is a new version [2.3.1-190](https://drive.google.com/open?id=1TYj2ebOW2VxQBoZHbpvD4MHHVQ--wkHs) that contains a loading indicator with other changes.

**Comment by Flole998** [comment]
This is much better, thanks! I guess we can close this now, unless you want to keep it open and further improve the initial load time somehow, no clue why it takes ~30 seconds for the first search after the App is opened. All further searches are instant.

**Comment by rsiebert** [comment]
2.3.1 was just released, so I'll close this issue.
I'll improve the loading stuff over time. I have it on my list.
