### ISSUE TITLE
Sometimes taps are misread

### ISSUE THREAD

**Issue by Flole998** [rsiebert/TVHClient#440]
When I scroll around in my event overview and then tap on an event, sometimes the wrong event details are shown.

**Comment by rsiebert** [comment]
I tried to trigger this issue, but couldn't. I tried scrolling and tapping in the program list and epg. The click handling is Android default stuff. No magic there from me. Was a sync of programs running in the background (blue progress bar at the top) or something else that could help pinpoint the issue?

**Comment by Flole998** [comment]
I have made a video that shows the issue (including my taps). Notice how the channel (aswell as program) is different from the one I tapped on. You can access the video here: https://cloud.flole.de/s/jJyprqAgtfcDiGc

**Comment by Flole998** [comment]
Seems fixed now.

**Comment by Flole998** [comment]
Unfortunately not fixed (or at least broken again).....

Scroll up and down fast and then try to tap on an EPG entry and it will select a wrong entry (above or below the one that was tapped) for some reason.

**Comment by rsiebert** [comment]
This seems to be an issue with the underlying libraries. Was it working ok with the 2.2.21 version?

**Comment by rsiebert** [comment]
Some changes were done in the last beta, are there still issues with that?

**Comment by Flole998** [comment]
No more issues, thanks!
