### ISSUE TITLE
Option to allow rotation of video player regardless of systems settings

### ISSUE THREAD

**Issue by Flole998** [rsiebert/TVHClient#442]
I request an option to make the video player respect my devices orientation even without enabling that system-wide. Ideally there would be an option to force portrait, landscape, sensor or default orientation.

**Comment by rsiebert** [comment]
Do you mean that there should be a setting to always play the video in portrait or landscape mode? Why do you need such a feature? The YouTube app as an example does not have this.

**Comment by Flole998** [comment]
Yes exactly. The YouTube App automatically switches to landscape mode once you use fullscreens, in tvhclient I'm stuck in portrait as I usually have rotation disabled, so I have to turn it on every time and back off afterwards.

**Comment by rsiebert** [comment]
Added in 2.2.7
