### ISSUE TITLE
Option to select multiple recordings for deletion

### ISSUE THREAD

**Issue by Flole998** [rsiebert/TVHClient#444]
When deleting my multiple recordings at the moment it's a lot of selecting/confirming. I'd prefer a long tap to enable multi-select and then short tap on all recordings that are supposed to be selected for deletion.

**Comment by rsiebert** [comment]
Duplicate of #314

**Comment by Flole998** [comment]
When this is added please also add mass-deactivate and mass-activate feature, should be very very similar.

**Comment by rsiebert** [comment]
Currently long pressing on a recording opens a popup menu. How should this be shown when long pressing shall enable multi select?

**Comment by Flole998** [comment]
Seperate buttons at the top for enable/disable selected could be an option.

**Comment by rsiebert** [comment]
Sorry, no time to implement this feaure
