### ISSUE TITLE
Only connect on local network - can't connect via external hostname or IP.

### ISSUE THREAD

**Issue by elParaguayo** [rsiebert/TVHClient#449]
I'm having an issue where I can't connect to my server using a hostname. The hostname works if I connect via Chrome on my phone so it's not a problem with DNS.

I can also connect to my server when using the local IP address but not the external IP. Again, the external IP works from Chrome on my phone.

I don't believe this is a function of the paid version so would appreciate any pointers here.

On a related note, the Status page doesn't show an error connection (even when I deliberately put in the wrong password) so it's not immediately obvious that it hasn't connected.

I'm running TVHClient 2.2.8 (165)  on a Galaxy S8 (Android 9/Pie). TVHeadend is 4.2.6-84.

Let me know if you need anything else to help debug this one (or just tell me if I've missed something obvious!)

**Comment by rsiebert** [comment]
Its probably only a firewall issue. Chrome connects via http port 9981. The app via 9982 and 9981. So both ports need to be open.

**Comment by elParaguayo** [comment]
Thanks. Both ports are already open.

The app has worked previously but has stopped working at some point. I hadn't used it for a while and it autoupdates so I don't know at what point it stopped.

EDIT: Hang on. It's shown as forwarded on my router but if I try checking the port from the command line using the external address it's not connecting. Let me check further!

**Comment by elParaguayo** [comment]
Thanks. Router was at fault. Deleted the port forwarding rule and recreated it. Now working fine.
