### ISSUE TITLE
Update for Player

### ISSUE THREAD

**Issue by ymdaddy** [rsiebert/TVHClient#452]
I'm using it satisfactorily.
I want to be further developed.
Maybe only on the internal player.
1. If you touch the screen while playing, the channel can be switched by selecting a pop-up channel list window.
2.The control panel that appears when you touch the screen while playing, I want to add a button that goes directly to the previous channel and the next channel as a journalist.

thanks a lot

**Comment by rsiebert** [comment]
Sound like a nice feature. I'll see what I can do.

**Comment by rsiebert** [comment]
The next version will include two buttons which allow switching to the previous or next channel

**Comment by rsiebert** [comment]
Please check the version [2.2.21-182](https://drive.google.com/open?id=1gbqi6XbnxPrOfAky19RwvVoRldspMyOX). It contains two buttons in the external player to switch channels.

**Comment by rsiebert** [comment]
The version 2.2.21 is now in the play store and contains the two icons to switch channels
