### ISSUE TITLE
Add "Disable" option to recording list

### ISSUE THREAD

**Issue by Flole998** [rsiebert/TVHClient#455]
I am using many Autorecs, sometimes recordings are scheduled that shouldn't be there so I disable them (deleting them will have them re-added later on so that's not an option). Right now this takes 3 steps: Click on recording, uncheck enabled, click save. It would be easier to long-tap and then select deactivate (or activate if it's already deactivated), especially when I do that to multiple recordings.

**Comment by Flole998** [comment]
This seems to be still missing in the "Scheduled Recordings" list? It's there on the series recording menu for me though.

**Comment by Flole998** [comment]
It's still missing in the "Scheduled Recordings"-Screen

**Comment by rsiebert** [comment]
Need to add this to the series recording screen too

**Comment by rsiebert** [comment]
The disabled option is now available in the latest version 2.2.17

**Comment by Flole998** [comment]
When I try to disable a recording from the "Scheduled Recordings" I am getting "DVR Entry not found" on every recording.

**Comment by rsiebert** [comment]
Thanks for the PR!
