### ISSUE TITLE
URL encoding broken for '+' for TVHClient logo filename

### ISSUE THREAD

**Issue by binhex** [rsiebert/TVHClient#456]
URL encoding for logo's does not work with TVHClient when logo filename has a URL encoded '+'

For example in TVHeadend web ui the 'User Icon' path is auto generated to be as follows (generated from the 'Name'):-

file:///data/logos/ITV2%20%2b1.png

Kodi is able to pick this up and display the logo so i know the filename and path are both correct, however TVHClient does not correctly decode %2b to be '+' and thus cannot find the logo.

This seems to be a problem only with '+', as TVHClient seems to be able to handle '&' (encoded as %26) and ' ' (encoded as %20) with no issues, for instance the following DOES display just fine in Kodi and TVHClient:-

file:///data/logos/Create%20%26%20Craft.png # which is 'Create & Craft.png'

**Comment by rsiebert** [comment]
Can you try this version? [2.2.12-169](https://drive.google.com/open?id=1wfPdWh8ILyLStpuuLYqVnIjU7RmSbUSh)

**Comment by binhex** [comment]
I tried it but I'm afraid it didn't fix the issue

**Comment by rsiebert** [comment]
I have replaced the image loading library from picasso to glide. Maybe this fixes the issue.
Here is another app version to test: [2.2.12-170](https://drive.google.com/open?id=1lNkY2hfsUkIksr1MiRYSFLZLVoyIeOPj)

**Comment by binhex** [comment]
Sorry still no improvement. To confirm I am performing a complete wipe of the tvhclient database and all channel icons when testing.

**Comment by rsiebert** [comment]
Another version. If this does not work, please send me the debug log [2.2.12-171](https://drive.google.com/open?id=1XoCjNPsMkL84aVckuaCLNuAsg0hkrLig)

**Comment by binhex** [comment]
Nope, still no fix im afraid, i also noticed the loading animation (line zooming left to right at the top of the screen) now takes a lot longer to complete with the above version, so whatever you did has slowed it down quite a bit.

debug log file here:-
https://drive.google.com/file/d/0B7tYr73nR4FzNURvT2E5aDdzbXFWT2dMb0FNNXcwNVp5MGc4/view?usp=sharing

screenshot of tvhclient showing issue here:- 
https://drive.google.com/file/d/0B7tYr73nR4FzeVdpeE5ETEtIeWprMzNhLWQ5djdTVV9BQXZz/view?usp=sharing

**Comment by binhex** [comment]
Thought it might be worth you seeing the config on the TVHeadend side too, snipet screenshot, note the URL encoded filename:-

![image](https://user-images.githubusercontent.com/1121837/58192455-b2606800-7cb8-11e9-9366-d79920c98173.png)

**Comment by binhex** [comment]
sorry, i think i found the issue, it was the filename, for some reason kodi seems to be able to interpret the filename from '-' to '+' and thus the logo showed fine so i didnt check the filename, after a lot of poking around i realised my rookie mistake, renamed the files and voila tvhclient picked it up no problems, even with the URL encoding. 

so im closing this off, sorry for wasting your time.
