### ISSUE TITLE
Playback and recording: Profiles. All options keep clearing back to defaults.

### ISSUE THREAD

**Issue by bensherlock96** [rsiebert/TVHClient#460]
I have the paid upgrade version. Version 2.2.14.  When setting the playback profiles for external players and Cast these keep getting cleared back to the defaults of "pass" and "none" when returning to this settings screen. On rare occasions I have managed to chromecast where the settings stick long enough. But only rarely. 

A second issue seems to be that the Settings option on the slideout menu only takes you to the settings screen when clicking on it from first starting the app. 

Otherwise looking great. Happy to provide more info - testing etc. Just let me know what you need.

**Comment by rsiebert** [comment]
Thanks for the info. Please send me the debug log. You can enable it from the advanced settings.
