### ISSUE TITLE
Can't compile

### ISSUE THREAD

**Issue by myraspxbmc** [rsiebert/TVHClient#461]
I there, i'am trying to compile but have error:
build failed	3 m 1 s 200 ms
Run build	3 m 0 s 940 ms
Load build	886 ms
Run init scripts	875 ms
Evaluate settings	8 ms
Configure build	635 ms
Calculate task graph	1 s 903 ms
Run tasks	2 m 57 s 505 ms
null	
/home/myrasp/StudioProjects/TVHClient	
htsp/src/main/java	
org/tvheadend/htsp/HtspMessage.java	
uses unchecked or unsafe operations.	
null	
/home/myrasp/StudioProjects/TVHClient	
app/src/main/java	
org/tvheadend/tvhclient/ui/features/dvr/recordings/RecordingDetailsFragment.kt	
Type mismatch: inferred type is FragmentActivity? but Activity was expected	
Type mismatch: inferred type is Recording? but Recording was expected	
org/tvheadend/tvhclient/ui/features/dvr/recordings/RecordingListFragment.kt	

Please when you have time take a look...
Thanks

**Comment by rsiebert** [comment]
Please do a pull to get the latest changes. It should work then.

**Comment by myraspxbmc** [comment]
Sorry for late replay I will try... Thanks

**Comment by rsiebert** [comment]
Closing the issue because the latest pushed sources compile. Additionally the latest commits on GitHub do not represent the latest version as on my laptop.
