### ISSUE TITLE
Where are the channel tags?

### ISSUE THREAD

**Issue by MrGlasspoole** [rsiebert/TVHClient#464]
I must be blind.
In TVH i have SAT, DVB-T, and Radio. But all i see in TVHClient is "All channels".

Also if i but a channel in the search i get no results.

**Comment by rsiebert** [comment]
You mean you see no channel tag names?
You want to search for a channel in the channel list? This was changed a few versions back so that only programs are searched. I think I will add a separate search channels menu item

**Comment by MrGlasspoole** [comment]
Yes i don't see channel tag names or i don't know where to find them.

I guess the normal behavior is to tap "All channels" and they should show up?

**Comment by rsiebert** [comment]
Did you check the permissions in the Servers Webinterface that your user can see the channel tags?

**Comment by MrGlasspoole** [comment]
Permissions seem not to be the problem because in [dream Player for TVHeadend](https://play.google.com/store/apps/details?id=de.cyberdream.tvh.player&hl=en) it works.

**Comment by rsiebert** [comment]
You can try to enable the debug log, clear the database and reconnect. Then send me the log please.
 Then I can see if channel icons are received.

**Comment by rsiebert** [comment]
Can you try the version [2.2.16-176](https://drive.google.com/open?id=1TuRbAdhAfIp8_tpfqT4CXpYBs2XHRIJ8). The issue with the missing channel tag names should be fixed there.

**Comment by MrGlasspoole** [comment]
Now nothing works anymore.
Cleared cache, did uninstall and install the latest from PlayStore again.
I get "connection failed" and "authentication failed".

In what directory is the log?
Cant find a directory org.tvheadend.tvhclient

**Comment by rsiebert** [comment]
Which app version did you use? 2.2.19 from the play store?
Did you enter the correct server url like "http://hostname:port" Do you use
ipv6 or ipv4 to connect to the server?


Am Mi., 14. Aug. 2019 um 14:21 Uhr schrieb MrGlasspoole <
notifications@github.com>:

**Comment by MrGlasspoole** [comment]
I get 2.2.18 from the PlayStore.
IPv4: `http://10.1.255.45:9981`

**Comment by rsiebert** [comment]
The htsp default port to communicate with the server is 9982 not 9981. please try to reconnect with port 9982.

**Comment by MrGlasspoole** [comment]
dream Player is using 9981 for connection and streaming and works fine.
Also watching on my workstation in MPC-HC it is: `http://10.1.255.45:9981/stream/channel`

Edit:
Ok, setting streaming to 9982 works now.
And I have the Tags now.

THANKS

**Comment by MrGlasspoole** [comment]
Zu früh gefreut :-(

"authentication failed" only goes away if i also set connection to 9982.
But playing in VLC says it cannot be played.

I did save the m3u from the WebUI and in there its 9981:
`http://10.1.255.45:9981/stream/channel/89125cb67b08a344d6f225b60e051e29?ticket=E811D1E7E4864B63962F7BDF8F467B440DB5BC36`

**Comment by rsiebert** [comment]
The dreamplayer app is probably using the web API that the servers webinterface is also using.
My app uses the HTSP (https://tvheadend.org/projects/tvheadend/wiki/Htsp) API. Two totally different things.

Tvheadend listens to the following TCP ports by default:
9981 - HTTP server (web interface, playback url for casting, VLC and other external players)
9982 - HTSP server (TVHClient connection, streaming protocol for the internal player)

So try using http://10.1.255.45:9982 as the server url and  http://10.1.255.45:9981 as the streaming url. I hope it works for you.

**Comment by MrGlasspoole** [comment]
Now it works.
I had it the other way around.

Now i can test your app.
