### ISSUE TITLE
Integrated player keeps playing audio in background after close

### ISSUE THREAD

**Issue by Flole998** [rsiebert/TVHClient#466]
When I run the external player, then use the picture-in-picture feature to have playback continue in a small overlay while doing something else and then exit that player by pressing the x button on that overlay, audio playback continues even though nothing is visible anymore and there is no way to stop playback other than force close.

**Comment by Flole998** [comment]
Now tvhclient opens itself upon stopping, is that wanted? I think in the past it was not opening itself, which I would prefer.

**Comment by rsiebert** [comment]
This seems to be the default behavior when exiting the player. I can check if there is another option.
