### ISSUE TITLE
Not available in Play Store anymore?

### ISSUE THREAD

**Issue by francoism90** [rsiebert/TVHClient#467]
https://play.google.com/store/apps/details?id=org.tvheadend.tvhclient&hl=en

Region: The Netherlands

**Comment by rsiebert** [comment]
Google has temporarily removed my app due to some policy violations. I am working on a fix for this issue.

**Comment by francoism90** [comment]
@rsiebert Thanks, will compile instead.

**Comment by rsiebert** [comment]
App ist available again in the play store.
