### ISSUE TITLE
Changelog cut at top

### ISSUE THREAD

**Issue by Flole998** [rsiebert/TVHClient#469]
When looking at the changelog, the text saying "VERSION 2.2.17" is "hidden" behind the title bar.

**Comment by rsiebert** [comment]
As shown in #468 this is not the case when you call the changelog from the settings. What phone and android version do you use? Anyone else having this issue?

**Comment by Flole998** [comment]
On 2.2.18 that's indeed fixed. Just on the privacy declaration the same issue exists.

**Comment by rsiebert** [comment]
The new version 2.2.20 should fix the issue. I have released it on 14.8.2019 in the afternoon. Somehow its not yet available in the playstore
