### ISSUE TITLE
Connection failed on latest Play Store update

### ISSUE THREAD

**Issue by francoism90** [rsiebert/TVHClient#470]
I'm keep getting Connection failed, even when the credentials are entered correctly.
I've send a debug log that's hopefully helpful.

Thanks.

**Comment by rsiebert** [comment]
Did you enter **http://hostname:9982** for the server url? **9982** is required for the connection to the server. The streaming url is only used for playback with the external player.

**Comment by francoism90** [comment]
@rsiebert No, TVHeadend listen on 9981. This is also shown as Server Url example.
I can access the URL from my phone without any issues.

**Comment by rsiebert** [comment]
Hi,

The required htsp port (not http) is 9982.
See the example in the screenshot. The streaming url is for playback with
an external player.

Best regards
Robert


François M. <notifications@github.com> schrieb am Do., 15. Aug. 2019, 13:35:

**Comment by rsiebert** [comment]
see also the comments in #464

**Comment by francoism90** [comment]
I tried both, port 9981 and 9982, I'm unable to get any connection.

**Comment by francoism90** [comment]
@rsiebert Sorry for the noise, I just found out the TVHeadend (channel) database is corrupted. I'm going to rescan and this will probably fix it.

Also learned something else new, didn't know TVH was also listen on 9982.

Thanks for your help.
