### ISSUE TITLE
External player profile is used for casting (instead of cast profile)

### ISSUE THREAD

**Issue by dkonerma** [rsiebert/TVHClient#471]
Hi Robert,

just noticed with 2.2.18 that the external player profile is used for casting (instead of cast profile). Can you verifiy this? ;-) Hope that's not my fault.

Cheers
Dietmar.

**Comment by rsiebert** [comment]
Thanks for the finding! Its using pass instead of the defined casting profile. It will be fixed in 2.2.21.

**Comment by rsiebert** [comment]
Please check the version [2.2.21-182](https://drive.google.com/open?id=1gbqi6XbnxPrOfAky19RwvVoRldspMyOX).

**Comment by dkonerma** [comment]
Issue ist fixed, thx.
