### ISSUE TITLE
Unable to save files on external SD-card

### ISSUE THREAD

**Issue by vzsze** [rsiebert/TVHClient#472]
When chosing a folder on a SD Card as download directory, the files are stored on the internal memory in /storage/0000-0000/Android/data/org.tvheadend.tvhclient/files instead.

Android version: 9

**Comment by rsiebert** [comment]
Can you provide me with a debug log?

**Comment by vzsze** [comment]
[tvhclient_2.2.21_182_23.09.2019.log](https://github.com/rsiebert/TVHClient/files/3641435/tvhclient_2.2.21_182_23.09.2019.log)

**Comment by vzsze** [comment]
I changed the path to external storage and downloaded a file, which endet up on internal storage.

**Comment by vzsze** [comment]
This is still not working with the 2.3.0 pre-release.  Do you need more information to fix it?

**Comment by rsiebert** [comment]
Any news here? This seems to be related to the used android version on a specific device model? I have also android 9 and I can save the recordings to the sd card.

**Comment by rsiebert** [comment]
Closing because the issue was reported long ago and no feedack.
