### ISSUE TITLE
Download does not honor full Filename of File

### ISSUE THREAD

**Issue by vzsze** [rsiebert/TVHClient#474]
When downloading a File, the Filename is created from the Title only, not honoring the filename configuration in TVH. The files are saved as TITLE(1).mkv, TITLE(2).mkv, ... instead of f.i. TITILE_SUBTITLE_EPISOSE.mpv, as it happens when downloading from the Web-UI. This makes it harder to preserve the order of a series-recordings.

**Comment by rsiebert** [comment]
I have added support for the naming scheme in the newest app version [2.2.22-183](https://drive.google.com/open?id=1SQjGTnmp0_4biSjz-wYOaiZ0BdQCKaQK) Can someone test it?

**Comment by vzsze** [comment]
That does work for me, but when filenames contain a "/", a new folder is created. This happend with the old version, too. See #479.

**Comment by rsiebert** [comment]
Ah good to know, then I need to replace those characters.

Rolf Kutz <notifications@github.com> schrieb am Mo., 7. Okt. 2019, 16:30:

**Comment by vzsze** [comment]
The new version seems to be unstable. The client is terminated when I try to look at the EPG. The buttons are missing from the description area. Download and play is only possible from the left list.

**Comment by rsiebert** [comment]
I noticed the epg issue too. Is something with the used Android and kotlin
libraries.
Thanks for pointing out the description button issues.

Rolf Kutz <notifications@github.com> schrieb am Mo., 7. Okt. 2019, 18:31:

**Comment by rsiebert** [comment]
The epg and missing buttons will be fixed in the next version.

**Comment by rsiebert** [comment]
Updates will be addressed in #479
