### ISSUE TITLE
If title of a recording contains a "/", a folder is created, when downloading the file.

### ISSUE THREAD

**Issue by vzsze** [rsiebert/TVHClient#479]
When the title of a recording contains a "/", the file saved in a subfolder. 

Example: When the title is Episode (1/8) a subfolder "Episode (1" is created. The video file would be named "8).mkv".

Special characters should be escaped when composing the file name.

**Comment by rsiebert** [comment]
Thanks for pointing it out. I'll add a new test version here soon

**Comment by rsiebert** [comment]
Please test the [2.2.22-184](https://drive.google.com/open?id=1Ff3JzX7D9NtlzOhMBXVAKlTCJ3HstEWH) version if its ok.

**Comment by vzsze** [comment]
From first glance: The buttons are there.
EPG is back!
"/" in filenames are still there, so subfolders are still created.

**Comment by vzsze** [comment]
If I understand it correctly, you seem to be replacing <slash><backslash>"/\" instead of just <slash> "/" with "", which seems to let the problematic "/" in place.

I would also suggest, replacing with "_" or "-" instead of just removing the slash, because that makes it easier to read the episode count from titles like (08/10), which would become (08_10) instead of (0810).

**Comment by rsiebert** [comment]
Good point, I will replace spaces, and slashed with a minus now
`title.replace(Regex("""[ /\\]"""), "-")`

**Comment by rsiebert** [comment]
I hope this version is now creating correct filenames [2.2.22-186](https://drive.google.com/open?id=1IO28u6AvIba7474FDaR_J_HKJv8TR-zO)

**Comment by vzsze** [comment]
No, still containing a / and creating a new folder.

**Comment by rsiebert** [comment]
Lets try this again until it works :-) [2.2.22-187](https://drive.google.com/open?id=1dH81gignkIxg4h8TqxhvtmjYkRcDgLyg)

**Comment by vzsze** [comment]
This one works.

**Comment by vzsze** [comment]
We might need to replace other characters from the filename, too. See #481.

**Comment by rsiebert** [comment]
Closing this issue. #481 can be used to track furthe issues
