### ISSUE TITLE
I Title or Subtitle contains a ?, the downloading filename extension is not created

### ISSUE THREAD

**Issue by vzsze** [rsiebert/TVHClient#481]
When the download-filename contains a ? at the end, the filename extension (like mkv) is not appended. This results in an error message when trying to play that file on Android. 

This bug is related to #479

**Comment by rsiebert** [comment]
Are there any other special characters that might occur?

**Comment by vzsze** [comment]
At least /\:*"?<>| should be avoided.

**Comment by rsiebert** [comment]
Here is a new upcoming test version [2.3.0](https://drive.google.com/open?id=1oHT6Tv8UicnsFkvGLAzJHnkWFZ87J7P5). Can you check if the filename stuff works?

**Comment by vzsze** [comment]
The file system stuff works ok. "?" and "/" are replaced, but I noticed, that the "back" button always closes the app, when used after a search operation in finished recordings.

**Comment by rsiebert** [comment]
Hmm, I cant reproduce the back button issue here with 2.3.0 or 2.3.1 using a smartphone. Using the back button shows the list with the finished recordings again. Any other clues?

**Comment by rsiebert** [comment]
2.3.1 was just released, so I'll close this issue.
Please open a new ticket to keep track of the back button issue

**Comment by vzsze** [comment]
You are right. On my phone that doesn't happen either, but it still happens on my tablett. I'll open a bug for that.
