### ISSUE TITLE
No media player found when starting a stream

### ISSUE THREAD

**Issue by Th0maz** [rsiebert/TVHClient#482]
I installed TVHClient on my GalaxyTab A 10.1 (2019) running Android  9.
When I try to start a stream (live or recorded), I get the error message:
"Konnte keinen Mediaplayer finden" (no_media_player)

This is what the log file says:
`[C:BasePlaybackActivity$startExternalPlayer] [M:run] [L:69]  Starting external player
[C:BasePlaybackActivity$startExternalPlayer] [M:run] [L:73]  Can't execute external media player
`
There's no media player selection window, like when I click on any media file in the file explorer.
MX Player Pro and VLC are installed and running fine.
Reinstalling TVHClient and the media player could not solve this.

I'm running the client and the same configuration also on my mobile phone (Android 6.0.1), where everything works as it should. I can also copy the TVHeadend stream link from my mobile phones MX Player to my tablet and start it in MX Player without issues.

I already emailed this issue to Robert Siebert, but we could not find a solution, yet.

**Comment by rsiebert** [comment]
Here is a new upcoming test version [2.3.0](https://drive.google.com/open?id=1oHT6Tv8UicnsFkvGLAzJHnkWFZ87J7P5). I have changed the logic a little in the [related file](https://github.com/rsiebert/TVHClient/blob/develop/app/src/main/java/org/tvheadend/tvhclient/ui/features/playback/external/BasePlaybackActivity.kt#L71). Could you check if this helps?

**Comment by Th0maz** [comment]
I installed version 2.3.0. on my tablet, but I'm afraid this did not solve the issue. I don't see any difference at all. Same error message as before.

Do you by chance know about some android settings or restrictions that could prevent the tvheadend app from opening any external players/apps or something like this? I can not remember changing any settings like these, but can of course double-check any setting.
Could it have something to do with default apps configured for certain files?

Let me know if I can test something.

**Comment by Th0maz** [comment]
After an app update yesterday I recognized that the changelog page on first startup does not load at all, but remains empty and loading...
Any ideas for a possible connection to my issue?

**Comment by rsiebert** [comment]
Hi,
 I am still investigating why the changelog is not shown. But you can check
the changelog from the settings.
Unfortunately there were no real changes regarding the empty list of
players.
I'll add more logging to the relevant parts and send you an intermediate
app version. Maybe the log info helps me to solve your Problem.

Best regards
Robert


Am Fr., 13. Dez. 2019 um 11:16 Uhr schrieb Th0maz <notifications@github.com

**Comment by gladstonekeep** [comment]
Hello, I got the same issue about external player not found.
Dialog to select app don't show up.

Solution: Use lowercase in the Playback URL

http://ip:9981 = works

Http://ip:9981= do not work

**Comment by Th0maz** [comment]
> Solution: Use lowercase in the Playback URL

That's the solution for our problem! 
Solved the issue for me, too. 
Thanks a lot :)
