### ISSUE TITLE
Search shows percentage above 100%

### ISSUE THREAD

**Issue by Flole998** [rsiebert/TVHClient#483]
When I run the EPG search and it finds something in the past it says "2035% of programme over" (or similar) depending on how far in the past it is. It should not say anything above 100% or should not show anything in the past at all.

Found in the latest beta.

**Comment by rsiebert** [comment]
Thanks for pointing it out. It will be fixed.

**Comment by Flole998** [comment]
Thanks, fixed in 2.3.1.
