### ISSUE TITLE
The "back" button always closes the app, when used after a search operation in finished recordings on a tablett

### ISSUE THREAD

**Issue by vzsze** [rsiebert/TVHClient#484]
The "back" button always closes the app, when used after a search operation in finished recordings on a tablett. This does not happen on a phone.

**Comment by vzsze** [comment]
Here's a logfile.

[tvclient_2.3.1_190_06-12-2019.log](https://github.com/rsiebert/TVHClient/files/3932695/tvclient_2.3.1_190_06-12-2019.log)

**Comment by rsiebert** [comment]
Please try the 2.3.4 version. There I can't reproduce the issue.
Closing for now.
