### ISSUE TITLE
Switching to recordings view from EPG search results doesn't clear filter

### ISSUE THREAD

**Issue by Flole998** [rsiebert/TVHClient#485]
When I search in the EPG view and then switch to a recording list the filter from the EPG search filter is still applied, but it is not shown in the textfield at the top, so clearing it is not possible.

Also when I switch back to the EPG view then, tvhclient crashes. You might see some reports from a few minutes ago in the Google Play console.

**Comment by rsiebert** [comment]
This was fixed in 2.3.4.
