### ISSUE TITLE
Stream randomly keeps stopping?

### ISSUE THREAD

**Issue by jaygtc** [rsiebert/TVHClient#486]
Hiya, 

I have an issue where the stream will randomly keep dropping out.

Im sure it is not my connection as i can play video files for hours, but with tv stream it will drop out anywhere from 5 mins to about 30 mins.

I have tried all stream types but issue is always the same?

**Comment by rsiebert** [comment]
Can you send me a debug log where the stream is dropping?

**Comment by jaygtc** [comment]
Sure how do I do that?

Sent from TypeApp<http://www.typeapp.com/r?b=15723>
On 15 Dec 2019, at 8:50 pm, Robert Siebert <notifications@github.com<mailto:notifications@github.com>> wrote:

Can you send me a debug log where the stream is dropping?

**Comment by jaygtc** [comment]
SENT BY EMAIL

**Comment by jaygtc** [comment]
?

Sent from TypeApp<http://www.typeapp.com/r?b=15723>
On 15 Dec 2019, at 8:50 pm, Robert Siebert <notifications@github.com<mailto:notifications@github.com>> wrote:

Can you send me a debug log where the stream is dropping?

**Comment by jaygtc** [comment]
Hi well thanks for getting back. : / Just to let you know there is something weird with your program and Android boxes.

As per the stream drops I mentioned. I have installed VLC player and connected directly to my tvh stream. 6 hours and perfect.

Back to your program. Freeze in 5 mins.

Something is not right...

Sent from TypeApp<http://www.typeapp.com/r?b=15723>
On 15 Dec 2019, at 8:50 pm, Robert Siebert <notifications@github.com<mailto:notifications@github.com>> wrote:

Can you send me a debug log where the stream is dropping?

**Comment by rsiebert** [comment]
This seems to be an exoplayer issue. I currently use the older 2.7. I plan to upgrade to a newer version, but I need to compile it myself due to some licence restrictions. Maybe this helps.

**Comment by jaygtc** [comment]
I'm using VLC. It's driving me nuts though. I'm going to scrap the entire idea. Not worth the hassle.

Sent from TypeApp<http://www.typeapp.com/r?b=15723>
On 23 Dec 2019, at 4:11 pm, Robert Siebert <notifications@github.com<mailto:notifications@github.com>> wrote:

This seems to be an exoplayer issue. I currently use the older 2.7. I plan to upgrade to a newer version, but I need to compile it myself due to some licence restrictions. Maybe this helps.

**Comment by rsiebert** [comment]
The new 2.3.5 app version will have a newer internal player. 
The used google exoplayer library bumped from 2.7 to 2.11.1. Maybe this helps.
I'm closing the issue because you seem to use VLC now.
