### ISSUE TITLE
Search order text incorrect

### ISSUE THREAD

**Issue by Flole998** [rsiebert/TVHClient#487]
In German language when choosing the sort order in the channel or EPG View it says "Aufnahmeprofil wählen" in the pop-up which is incorrect.

**Comment by rsiebert** [comment]
Here is an intermediate version [2.3.5](https://drive.google.com/open?id=16OG8jSp0ncbkUuC5KPeVm6gEsB6qjopP) of the app.
This should fix the issue.

**Comment by Flole998** [comment]
Fixed, thanks!
