### ISSUE TITLE
Internal player audio not available

### ISSUE THREAD

**Issue by Flole998** [rsiebert/TVHClient#490]
I updated to 2.3.5-198 and the internal Player is no longer playing back audio (it's impossible to select the audio tracks manually aswell, they are shown but greyed out). However, subtitles default to on which means that I have to disable them for every channel which is quite annoying.

**Comment by rsiebert** [comment]
Was it possible in the 2.3.4 version or in the 2.3.5-196?

**Comment by Flole998** [comment]
With the one in the play store it was working (no idea which one that is), I haven't tested the 196 one.

**Comment by rsiebert** [comment]
Can you send me a debug log? So I can see which audio format it is using.

**Comment by Flole998** [comment]
Audio format is ac3 that is causing the issues/is marked as unsupported.

**Comment by rsiebert** [comment]
Here is a test version [2.3.5-199](https://drive.google.com/open?id=1jw4Y-Ksa37RVD7JSjriMwcxW0LDt85FO) that contains more audio formats. Is there sound again?

**Comment by Flole998** [comment]
Nope, unfortunately not.

`C:CustomEventLogger] [M:onTracksChanged] [L:42] Track:0, selected=no, id=3, mimeType=audio/ac3, channels=2, sample_rate=48000, language=mis, supported=no, unsupported typeivity] [M:onBackPressed] [L:79] Calling back press of super`

Also the subtitles are still shown per default apparently.

**Comment by rsiebert** [comment]
Here is another test version [2.3.5-200](https://drive.google.com/open?id=16L4cAbGSgLsjDfur7mvKx8phQyI0g4TU) that should make audio work again

**Comment by Flole998** [comment]
Perfect, fixed! Thanks!
