### ISSUE TITLE
List of series recordings not updating

### ISSUE THREAD

**Issue by lloyda** [rsiebert/TVHClient#491]
If I create a series recording, and then delete it, it will always be displayed in the app, even though the series recording no longer exists.

**Comment by rsiebert** [comment]
Which app version are you using and which version is the server?
You can also send me the debug log.

**Comment by lloyda** [comment]
App is 2.3.4 from the store.

Tvheadend Build: 4.2.8-36~g5bdcfd8ac (2019-11-15T18:14:42+0000)

What steps do you want captured when debug is on?

**Comment by rsiebert** [comment]
Please activate the debug log from the advanced settings. Restart the app and then go to the series recording screen. Create one, delete it and then mail the debug log to me also via the advanced settings. Is there also a permission issue on the server? With my setup here I can create a series recording and delete it. It will disappear from the list.

**Comment by lloyda** [comment]
I've tried to reproduce this, and I cannot.  However, the app and the web interface are still showing a mismatch between series recordings, and reconnect does not correct this. Attached are two screenshots.  Note one has 6 series and the other 7.  It is the series at the top of the app screenshot that is the issue. (How are the series ordered?  It seems quite random, bit I'm sure its not.)

I am also having a problem when trying to create series from program guide - it often selects the wrong program.  Do you want me to create another issue, rather than pollute this one?

![series](https://user-images.githubusercontent.com/1671197/72281569-b881cb00-3632-11ea-8ac2-dce405b0a370.png)

![autorec](https://user-images.githubusercontent.com/1671197/72281593-bf104280-3632-11ea-8ead-ab13602977f8.JPG)

**Comment by rsiebert** [comment]
Hi, please create another issue for the other problem.
The series recordings and timer recordings are not sorted by name or start time. Channels and recordings are sorted. I can add this in the next release. 
What happens when you try to delete the first recording? Error, its not possible?
You can also try a clear the database contents from the advanced settings. The app will then refetch all data.

**Comment by lloyda** [comment]
If I try and delete the entry, it says 

>Recording was not removed! Automatic schedule entry not found.

(Sort would be nice for series, and I'll open another issue for the other problem.)

**Comment by rsiebert** [comment]
So it is a stale database entry somehow. Clearing the database should help.

**Comment by lloyda** [comment]
Ok.  I'll clear it now, and keep my eyes peeled for a return of the issue.

Thanks for the great app.

**Comment by rsiebert** [comment]
Here is a test version [2.3.5-199](https://drive.google.com/open?id=1jw4Y-Ksa37RVD7JSjriMwcxW0LDt85FO) that introduces sorting by start time and then by name.

**Comment by lloyda** [comment]
That seems to be working.  Thanks

**Comment by rsiebert** [comment]
Here is another test version [2.3.5-200](https://drive.google.com/open?id=16L4cAbGSgLsjDfur7mvKx8phQyI0g4TU) that should show the "recording was updated" message instead of removing and adding.
