### ISSUE TITLE
Authentication fails when using a reverse proxy

### ISSUE THREAD

**Issue by brimur** [rsiebert/TVHClient#492]
Hi Robert. Long time user of the paid app and has always worked great. Recently I had to put my TVHeadend server in a different subnet to my gateway so I started using a reverse proxy to acces it externally. I verified everything was working ok in the browser but when I was outside my network and tried using TVHClient it would not work. When connecting to my TVHeadend server via a reverse proxy I get an error in the app saying authentication failed. When I connected via a browser I get prompted as usual and I can login and watch channels. Not sure why the method is used by the app but it works fine with a direct connection but not via a reverse proxy.

**Comment by rsiebert** [comment]
The app requires a direct connection to the server and port. Reverse proxy is not supprted. 
I can't implement it because I have no setup here to test it.

**Comment by brimur** [comment]
Ok, thanks. Sorry, I'm not familiar with the internals of the client so I cant help but FYI there is no issue using a browser but there is in the app. As in I can log in with a browser and click play on a channel using TVHeadends built in player or I can click Play Program which downloads the m3u file uses VLC without issue so it appears not to even know there is a reverse proxy in place. I even turned off authentication and removed the username and password from the app but I still get the Auth Failed message in the app. Interestingly, even with debug enabled, the TVHeadend server does not even show a connection attempt. When I connect with a browser I see the connection immediately as coming from the IP of my reverse proxy.

Also, I turned on Debug in the app settings but I cant find where it is saving the file to, can you let me know the location and I will try to debug it a bit? Thanks again

I found your email in another thread about https and reverse proxy so I sent you the link to my tvheadend in case you want to test with it.

**Comment by kcris** [comment]
Hi,

I can confirm, I am behind a reverse proxy as well, and tvhclient does not work for me.

I also use a custom webroot, my tvheadend server is available via
https://myserver.com/tv  (note that /tv at the end)
Not sure if the path is the problem or the reverse proxy.

Thanks
Chris

**Comment by Akruidenberg** [comment]
I would like to have this function also.

**Comment by ManOki** [comment]
duplicate #269

**Comment by kcris** [comment]
I gave (via email) access to @rsiebert to my server for testing purposes

**Comment by rsiebert** [comment]
@kcris I did not get your email with the server details. Can you resend them to me so I can start testing the http connection to the server.

**Comment by kcris** [comment]
hi, 
sure, I just sent it to your mail: xxx80 at gmail
thanks

**Comment by rsiebert** [comment]
Thanks for the information. It worked.
This issue will be followed in the issue #269
