### ISSUE TITLE
Constant "loading of programms finished" at end of event list

### ISSUE THREAD

**Issue by Flole998** [rsiebert/TVHClient#496]
When you select a TV channel and scroll through the EPG events all the way to the bottom there is a constant "Finished loading programms" repeatedly showing up at the bottom making it impossible to select the last entry.

**Comment by rsiebert** [comment]
Here is a test version [2.3.5-199](https://drive.google.com/open?id=1jw4Y-Ksa37RVD7JSjriMwcxW0LDt85FO) that should fix that

**Comment by Flole998** [comment]
Fixed, thanks!
