### ISSUE TITLE
Sort recordings by duration or genre

### ISSUE THREAD

**Issue by lloyda** [rsiebert/TVHClient#497]
It would be nice to be able to have the option to be able to sort completed recordings by either duration or genre.   It will enable me to answer questions such as "do we have anything that is only 30mins long?", or "what films do we have to watch?"  (I only see genre colours in Channels and Program Guide.  Should I see them elsewhere - all genre options are set to on in the settings menu.)

**Comment by rsiebert** [comment]
Here is another test version [2.3.5-200](https://drive.google.com/open?id=16L4cAbGSgLsjDfur7mvKx8phQyI0g4TU) that contains the option to sort the completed recordings and show the genre color.

**Comment by lloyda** [comment]
I can sort by genre, but I'm still not seeing any genre colours (mobile phone).  Is it possible to also sort by duration?

**Comment by rsiebert** [comment]
You need to activate the genre color for recordings in the ui settings. Sorting by duration can be done. I'll add it to a later version.

**Comment by lloyda** [comment]
Apologies, you're right. School boy error on my part. I look forward to sort by duration.

**Comment by rsiebert** [comment]
Added in 2.3.6
