### ISSUE TITLE
Advance program guide by 24hrs

### ISSUE THREAD

**Issue by lloyda** [rsiebert/TVHClient#498]
On the program guide, it would be good to be able to change the timeframe to +24hrs ie, look at the next days programs at the currently selected time, and a second, third press would move forwards two days, three days etc.

**Comment by rsiebert** [comment]
There is already a menu available to jump to a certain time. Its in the top right toolbar menu.

**Comment by lloyda** [comment]
I assume you mean the Timeframe option.  Unfortunately using this menu option I can only move forward by a maximum of 6 hours.  If I want to view tomorrow's programs, the only way I can find to do this is by scrolling.

**Comment by rsiebert** [comment]
Ui, the selection list in the timeframe dialog should show more entries.
You should be able to go to the maximum number of days defined in the ui settings.
So this is a bug.

**Comment by lloyda** [comment]
Yes, there is definitely something odd going on.  If I reduce the number of days in the ui settings to 1, the Timeframe menu only shows one option, 'current time'.

And two days -> current time plus next hour.

**Comment by rsiebert** [comment]
I have found the issue. It will be fixed in 2.3.6.

**Comment by lloyda** [comment]
2.3.6-202 seems to have partially resolved this, but there is still an issue.

When you initially open the app, the extended menu all works fine.  However, if you leave the app open for any length of time (>1hr), the menu entries are relative to the time when you opened the app, not the current time.

For example, open the app at 11:10. Menu entry current time displays data for 11:00-12:00. Menu entry 12:00-13:00 displays  data for 12:00- 13:00, as expected.

Leave app for an hour.  Its now 12:15.  Menu entry current time displays data for 11:00-12:-00.  Menu entry 13:00-14:00 displays data for 12:00 to 13:00.

**Comment by rsiebert** [comment]
I guess closing the dialog after 1 minute should solve the issue?
When the time selection menu is selected again, the times are correct again.

**Comment by rsiebert** [comment]
Version 2.4.0 was released today
