### ISSUE TITLE
Failed recording showing in Completed recording

### ISSUE THREAD

**Issue by lloyda** [rsiebert/TVHClient#500]
Title says it all really. I have one failed recording (too many data errors), and in the app this is being displayed (and counted) under completed recordings, not failed recordings.  Web interface shows it as failed.

**Comment by lloyda** [comment]
This looks a bit more subtle than I first realised.  What I reported above is correct, but if a recording fails for some other reason, then it does appear in the failed list.

What I'm seeing in the app is the same as I see in Kodi, so looks like either a TVH issue or it is by design.  Suggest that this issue could be closed as a non issue.

**Comment by rsiebert** [comment]
As I can see from the tvheadend sources this is intended by design.
