### ISSUE TITLE
Selecting wrong program in program overview

### ISSUE THREAD

**Issue by PastCoder** [rsiebert/TVHClient#503]
If I select a show with long press to record it, it does plan recording the wrong program. In the attached screenshot: If I long press on "heute" and then select "record", it selects "BR extra". 

The issue exists already since some versions. It appears with my mobile and with my table.

Tested with:
- TVHclient V 2.3.6
- Android
- Tvheadend 4.2.8-36
- API version 27

If I can provide any information to support locating the problem, please let me know.

![image](https://user-images.githubusercontent.com/23421026/80407026-3c4f8280-88c5-11ea-9a9d-66da334be731.png)

**Comment by rsiebert** [comment]
I have released a new beta version 2.4.0-211 with some changes regarding the program selection in the epg. Should be available in a few hours.
