### ISSUE TITLE
profiles are displayed several times

### ISSUE THREAD

**Issue by bladem2003** [rsiebert/TVHClient#504]
hello,

I have set up 2 recorder profiles on tvheadend.
they are shown several times in the app.

**Comment by rsiebert** [comment]
Can you send me the debug log please?

**Comment by bladem2003** [comment]
here is the debug log and a screenshot.

[tvhclient_2.3.6_203_05.06.2020.log](https://github.com/rsiebert/TVHClient/files/4736699/tvhclient_2.3.6_203_05.06.2020.log)

![Untitled-1](https://user-images.githubusercontent.com/47271861/83889117-6d886180-a753-11ea-8b38-48551c9c8ed3.jpg)

**Comment by rsiebert** [comment]
Should be fixed in the latest 2.4.0-209 beta version.
Please clear the database before.

**Comment by rsiebert** [comment]
Version 2.4.0 was released today
