### ISSUE TITLE
ADB am start command to open the TVHClient android app

### ISSUE THREAD

**Issue by tiagofreire-pt** [rsiebert/TVHClient#507]
Hi.

I'm trying to integrate all the apps that I have on my android box, such as TVHClient, within Home Assistant.

The apps are executed with a command sent from HA to the ADB shell, like so for Spotify:

```
am start -a android.intent.action.VIEW -d -n com.spotify.music/com.spotify.music.MainActivity
```

How can I open aswell the TVHClient, please?

Thank you.

**Comment by rsiebert** [comment]
Please try:
```
am start -a android.intent.action.VIEW -d -n org.tvheadend.tvhclient/org.tvheadend.tvhclient.ui.features.MainActivity
```

**Comment by tiagofreire-pt** [comment]
Works flawlessly!

Thanks!
