### ISSUE TITLE
Double-click on borders for faster zapping

### ISSUE THREAD

**Issue by matej86** [rsiebert/TVHClient#511]
Dear,

could it be possible to have a new function for speeding the channel zapping on iPhone and iPad? I was thinking about a double-click(touch) on the borders of the screen while watching a channel in order to switch to the next or the previous one.

**Comment by rsiebert** [comment]
This feature exists already. There are two buttons below the video, previous and next channel.

**Comment by matej86** [comment]
Really? Because I don't see it :(

![IMG_3310](https://user-images.githubusercontent.com/26971366/85827215-1855d380-b786-11ea-8924-90832fb890ad.png)

**Comment by rsiebert** [comment]
Here is my screenshot. App version 2.3.6

![Screenshot_20200626-211746](https://user-images.githubusercontent.com/1406960/85893125-89cb6b80-b7f2-11ea-8964-082a331bee34.png)

**Comment by rsiebert** [comment]
Ah I guess you are using an external player, not the internal one.

**Comment by matej86** [comment]
I tried to create a transcoding profile on tvheadend and chose ios player but I only see a back screen

Inviato da iPad

**Comment by rsiebert** [comment]
It seems you are using the iOS (Apple) version of the app? Because there is no iosplayer on android. And your screenshot including the icons do not exist on the Android TVHClient app.

**Comment by rsiebert** [comment]
According to the layout of the status bar on your screenshot it's an iPhone. I have never seen this layout on Android phones. So I close the issue.
