### ISSUE TITLE
Download Butten Crashes the App

### ISSUE THREAD

**Issue by Greandragon** [rsiebert/TVHClient#512]
Dear developer,
I really like your app but since i got my Oneplus 7 with Android 10. The App crashes when i want to download a recorded TV Episode ore Movie.
Thanks for your great work an your support

**Comment by rsiebert** [comment]
Thanks for reporting this. Can you try the latest beta please? Version [2.4.0-215](https://drive.google.com/file/d/15U5IxGxFzWPc1Bu8dBTC0FU47_FPawZC/view?usp=sharing)

**Comment by Greandragon** [comment]
Thanks  for your Help the Beta Software Changes nothing the App crashes also immediatly by Pressung the Download Button.

**Comment by Greandragon** [comment]
Thanks for your Help the Beta Software Changes nothing the App crashes also immediatly by Pressung the Download Button.

**Comment by rsiebert** [comment]
You seem to use the old path "/storage/emulated/0/Download/...". This is not allowed in Android 10. 
Can you go to the settings an update the download directory? 
After that please try downloading a recording again. Then I can pinpoint the problem better.

**Comment by rsiebert** [comment]
I have changed some stuff regarding the download handling. Can you additionally to the comment above try the new beta [2.4.0-216](https://drive.google.com/file/d/1WsLhbygHSTruoE3zXb8we4rm3fdU_nKK/view?usp=sharing)? Thx!

**Comment by Greandragon** [comment]
Thanks you verry much this Beta works perfekt.

**Comment by rsiebert** [comment]
Version 2.4.0 was released today
