### ISSUE TITLE
Series recording not setting the channel

### ISSUE THREAD

**Issue by alanswanson** [rsiebert/TVHClient#517]
When creating a new series recording from a selected program and channel, the channel is not being set in the autorec and hence is **_All channels_**.

For example, when selecting "Record as series recording" from a program on _BBC One HD_ (in UK Freeview DVB-T), no channel is set in the autorec entry and tvheadend will record the whole series with randomly either _BBC One_ or _BBC One HD_ but not both - assume there's some order matching precedent within tvheadend.

We should be setting the channel for a series recording? Only prior issue that referenced similar issue was #150.

TVHClient 2.4.0
Tvheadend 4.3-1857~g221c29b40-dirty

**Comment by rsiebert** [comment]
Here is a beta version [2.4.1-217](https://drive.google.com/file/d/1IXIi5XG569S2KeNUjexbVKJE9iKv8RcD/view?usp=sharing). This should fix the all channels issue.

**Comment by rsiebert** [comment]
Version 2.4.1 was released
