### ISSUE TITLE
Connection to thveadend server fails

### ISSUE THREAD

**Issue by bueeler** [rsiebert/TVHClient#519]
Sporadically I see the issue, that TVHClient cannot connect to the tvheadend server (4.3-1896~gce0907705). The loading indicator in the app is shown permanently. When I delete all DB in TVHClient, it can only load channel list and icons, no programmes, recordings or profiles.
When the issue occurs, it remains for several days/hours, but at one point it is suddenly works again. Other clients still can connect to the server during that time.

I attached the debug log of the client
[tvhclient_2.4.1_219_19.09.2020.log](https://github.com/rsiebert/TVHClient/files/5249262/tvhclient_2.4.1_219_19.09.2020.log)

On server side there is following output:
```
2020-09-19 09:37:12.661 htsp: Got connection from 192.168.1.92
2020-09-19 09:37:12.696 htsp: 192.168.1.92: Identified as user '*' (unverified)
2020-09-19 09:37:12.696 htsp: 192.168.1.92 [ * ]: Welcomed client software: TVHClient (HTSPv32)
2020-09-19 09:37:12.705 htsp: 192.168.1.92 [ * | TVHClient ]: Unauthorized access
2020-09-19 09:37:13.162 htsp: 192.168.1.92 [ * | TVHClient ]: Write error -- Connection reset by peer
2020-09-19 09:37:13.162 htsp: 192.168.1.92 [ * | TVHClient ]: Disconnected
```
It does not matter whether I choose specific user or "no user" on TVHClient.
Also issue is not related to beta version from PlayStore, it occurs also with non beta version.

**Comment by rsiebert** [comment]
This is related to the log entry "java.io.IOException: Buffer position is negative, namelen -39" The exception then closes the connection to the server. So sporadically the buffer length is negative.

I will upload a new beta here where this check does not close the connection to the server. So you can test and check if it works.

**Comment by rsiebert** [comment]
Here is the new beta to test: [2.4.1-222](https://drive.google.com/file/d/1QZhzKwLtAzofJoSbAyFW-Gee75AFcWD6/view?usp=sharing)

**Comment by bueeler** [comment]
Thanks for your efforts! I tested with the beta version 2.4.1-222. Unfortunately the connection is still closed. See attached log:

[tvhclient_2.4.1_222_23.09.2020.log](https://github.com/rsiebert/TVHClient/files/5270399/tvhclient_2.4.1_222_23.09.2020.log)

**Comment by rsiebert** [comment]
This time its a buffer limit error. Somehow your server seems to send huge amount in one message that does not fit in the buffer. I'll add another beta version here soon.

**Comment by rsiebert** [comment]
Here is the new beta to test: [2.4.1-223](https://drive.google.com/file/d/1dxb4GVduhOVEmVM3ewmAPONTIXowzGZt/view?usp=sharing)

**Comment by bueeler** [comment]
Thanks. I tested with 2 clients. While connection failed with previous version, the connection could be established each time with beta 2.4.1-223. So problem seems to be solved for me. Do you need log for verification?

**Comment by rsiebert** [comment]
That is ok for m, but could you initiate a reconnect from the menu? Or clear the database from the advanced settings? Lets see if everything will be reloaded fine.

**Comment by bueeler** [comment]
Everything is reloaded fine after database clear.

**Comment by rsiebert** [comment]
Version 2.4.1 was released.
