### ISSUE TITLE
Error message during connection establishment since early this year

### ISSUE THREAD

**Issue by chriskloe** [rsiebert/TVHClient#524]
Hi!
My TVHClient was already working for a while. 
Since early this year I am getting those messages during connectino establistment in a row (German mobile, sorry):
"Verbunden mit Server" -> Successfully connected with server
"Verbindung fehlgeschlagen" -> Connection fault
I hoped it would be fixed with the latest update due to the update info but unfortunately that did not help.

Something about my setup:
Tvh 4.3, self built on Ubuntu 20.10
Samsung Galaxy S8
Android with updates from Nov/1st. 2020.

Connection is working properly from Kodi running on a Samsung tablet and and a raspi with libreelec with same credentials.

Please contact me in case you need additional information.
BR,
Christoph

**Comment by rsiebert** [comment]
Can you post the connection url that you have used? Is it http://Servername:9982 ?

**Comment by chriskloe** [comment]
Yes, indeed, It's a local host within my local network, no domain. DNS is my FritzBox.

**Comment by rsiebert** [comment]
Can you enable the debug log and send it to me? You can enable it in the advanced settings. Once enabled, please close and reopen the app.
Kodi and raspi are probably using the http api to access the server. My app uses HTS which runs on a different port.

**Comment by chriskloe** [comment]
OK, strange combination of facts:

TVHClient tried to connect using IPV6. As that did not work, it gave up. All others obviously try again with V4 and that works. Unfortunately the default of tvheadend is deactived IPV6. After activating it, all worked again.
Still unsolved question: why did it suddenly stop working around end of last year?

Remainaing recommendation for improvement of TVHClient: try connection again using V4 when V6 does not work.

**Comment by rsiebert** [comment]
The app tries to get the inet address from the hostname. In case an ipv6 address is returned the app will try to get the ipv4 address again. See https://github.com/rsiebert/TVHClient/commit/ac9f1e7636535dc70635dcf613ce6a7e1c475b86
