### ISSUE TITLE
External Player not recognized

### ISSUE THREAD

**Issue by rkorn86** [rsiebert/TVHClient#529]
After updating to version 2.4.5 my external Player "mx Player Pro" is no long er recognized and the app forces me to download another video Player app.
Seems like the check for an existing Media Player is not correctly implemented.
Im using Android 11 on an up2date one plus 8pro.

**Comment by rkorn86** [comment]
You should probably not check for `PackageManager.MATCH_DEFAULT_ONLY` in https://github.com/rsiebert/TVHClient/blob/0af2bdcd5a6f82e3642db4642e74166a6a343b0e/app/src/main/java/org/tvheadend/tvhclient/ui/features/playback/external/BasePlaybackActivity.kt#L68.
So the android Dialog pops up letting the user to choose which app to use playing a video.

**Comment by bueeler** [comment]
I have same problem since this version, instead of launching installed external player, it redirects to Play Store. (Internal player does not work either and claims about not set profile. But profile is actually set.)

**Comment by storrella** [comment]
Same issue here. It was working properly on VLC before the update

**Comment by rsiebert** [comment]
The `packageManager.queryIntentActivities` call has been deprecated. The intent should be called within a try catch block. Setting the video mime type as shown in [e739cebd](https://github.com/rsiebert/TVHClient/commit/e739cebd3b5ceef06e6b4feee1ce9a9e167b2a52) seems to solve the issue for some users. You can download the latest beta [2.4.6-233](https://drive.google.com/file/d/1dOKWmUNzB0JYRCWdnT1Oej7tA1Q4_o4F/view?usp=sharing). Using the google play beta channel takes too long to get fast feedback.

**Comment by bueeler** [comment]
The new beta fixes the issue for me. Thanks!

**Comment by rsiebert** [comment]
Fixed in 2.4.6
