### ISSUE TITLE
TVHClient runs asynchronously to Tvheadend

### ISSUE THREAD

**Issue by K1LLUM1N471** [rsiebert/TVHClient#533]
Hello, 
I had already twice the problem, that the app runs asynchronously to Tvheadend.
1. Channel list: Server: 52 channels, App: 133 channels
2. Series recording: Server: 1, App: 4

Method: 
1. I remove several unneeded channels on the server. 
2. I reconnected the app. 
--> Old channel list is still persistent
Solution: Clear all app data

Now I seem to have the same problem with the series recording (see 2.), but I do not want to clear all app data again.
Finished recordings and scheduled recordings seem to work correctly.

Do you have a solution for this problem?

Kind regards, 
K1LLUM1N471

Android 9.1
TVHClient 2.4.6 (234)

Server API Version
27 (Server: Tvheadend)
4.2.8-36

**Comment by rsiebert** [comment]
Usually the server sends all relevant information to the app when it connects. if its not in sync then only clearing the database form the advanced settings helps.
