### ISSUE TITLE
Slow / lagging search UI

### ISSUE THREAD

**Issue by stephanritscher** [rsiebert/TVHClient#535]
Hi,
I have problems with the program search functionality of the TVHClient Android app. Sometimes (I think, it's the first time after the app was opened) the search takes very long (> 1 minute), and also when the search results are shown, the UI often freezes for up to 30 seconds. Sometimes, Android even tells that the app is not reacting and asks me whether to kill it or wait.
When waiting long enough, the search / UI actions are successful, but these parts of the app are almost unusable for me.

When looking at the app logs via adb, I see the following messages roughly once every 1-2 seconds:
```
12-26 14:56:51.900 23754 23815 W CursorWindow: Window is full: requested allocation 456 bytes, free space 267 bytes, window size 2097152 bytes
12-26 14:56:54.115 23754 23815 W CursorWindow: Window is full: requested allocation 978 bytes, free space 613 bytes, window size 2097152 bytes
12-26 14:56:56.352 23754 23815 W CursorWindow: Window is full: requested allocation 456 bytes, free space 333 bytes, window size 2097152 bytes
12-26 14:56:58.587 23754 23815 W CursorWindow: Window is full: requested allocation 456 bytes, free space 144 bytes, window size 2097152 bytes
12-26 14:57:00.855 23754 23815 W CursorWindow: Window is full: requested allocation 456 bytes, free space 31 bytes, window size 2097152 bytes
```
Debug logs from the app are attached ([tvhclient_2.4.6_234_26.12.2021.log](https://github.com/rsiebert/TVHClient/files/7777078/tvhclient_2.4.6_234_26.12.2021.log)), with app connected to server (wifi on and server in same network). Without wifi (no server connection), the search is also slow.

I'm using tvheadend with an usb sattelite adapter tuned to Astra 19.2 E with currently ~550 channels and ~85.000 programs.
The app is runnning on a Samsung Galaxy S7, now with LineageOS 18.1 (Android 11), but I had the same behaviour up until recently with Samsung stock firmware (Android 8).

**Comment by stephanritscher** [comment]
Bump.

Am I the only one experiencing this problem?!

**Comment by efschu** [comment]
Same problem on OnePlus10Pro

**Comment by rsiebert** [comment]
I have stopped developing the app. Only deprecation warnings or bumping the target api will be done.
