### ISSUE TITLE
Suggestion for improvement

### ISSUE THREAD

**Issue by Marthinius** [rsiebert/TVHClient#541]
Hello,

It would be possible to release a version without pvr functions and without donation and internal player ?
Simply a lite version without all the pvr recording functions / internal player / donation ?
A version that only allows watching tv and epg ?

I tried compiling, but unfortunately it didn't work.

Thank you

**Comment by rsiebert** [comment]
Nope, not going to happen. Others also requested a version without Google stuff inside. It's too much hassle to release versions for the other 1% of users. Sorry.
