### ISSUE TITLE
Subpath not supported

### ISSUE THREAD

**Issue by gdomod** [rsiebert/TVHClient#542]
i used nginx reverse proxy with subpath parameter of tvheadend, but the client doestn support it.
can u add this feature please ?
custom url:
https://EXAMPLE.COM:CUSTOM_PORT/SUBPATH

**Comment by rsiebert** [comment]
I have stopped development and only bump versions when Google deprecates stuff. Linear TV is not my focus anymore and I also have no test setup. 
In the past I used the VPN feature of my phone to connect to my home wlan, then I could just connect using server:port.
