### ISSUE TITLE
Incorrect EPG

### ISSUE THREAD

**Issue by ghost** [rsiebert/TVHClient#543]
Some programs are visible twice in the EPG, one without description and one with description. How can this be corrected?

**Comment by ghost** [comment]
The time difference between those two programs are about 5 minutes.

**Comment by ghost** [comment]
Also the channel numbers are incorrect in my EPG.
It's shown as 1.0 instead of 1, 2.0 instead of 2 etc.

**Comment by rsiebert** [comment]
Double entries are caused by the server when it receives new epg data and the id changes. Then we have the old epg entry and the new one with a different id. In this case clearing the database from the advanced settings helps.
