### ISSUE TITLE
TVHClient  Signal SNR and AGC

### ISSUE THREAD

**Issue by xxj737** [rsiebert/TVHClient#545]
TVHClient 
When working on Android,
How to see signal SNR and AGC?

**Comment by rsiebert** [comment]
What is SNR and AGC? This seems server related. Please ask someone from tvheadend.org.

**Comment by xxj737** [comment]
The  ios app   tvhclient     
for example

![微信截图_20240506173340](https://github.com/rsiebert/TVHClient/assets/50125219/74062084-d9a2-4130-8c4c-1b1cf658ebe9)
