### ISSUE TITLE
Reconnect to Tvheadend

### ISSUE THREAD

**Issue by dstolpmann** [rsiebert/TVHClient#55]
Hi,
I have probably found a bug in TVHClient.

The app doesn't reconnect to the server.

This can be reproduced by cutting the connection or restarting the server while the app is open or in the background. It doesn't load new entries in the schedule of a TV channel or in the EPG, even after pressing the refresh button there. When you press the refresh button in the channel list, everything is fine.

The server acknowledges the touch of all refresh buttons with the message: "Welcomed client software: org.tvheadend.tvhclient (HTSPv8)" in the log but only the button in the channel list works correctly.

The app should properly reconnect whenever the refresh button is pressed or when you scroll in the channel schedule or in the EPG and no data is available.

Tested with Tvheadend 3.9.1567~gde634dd and TVHClient 1.5.4.

**Comment by rsiebert** [comment]
The wireless and mobile connectivity will be checked in the upcoming version 1.8.0

**Comment by Andulien** [comment]
I just tested this. When I open the app while no Wi-Fi connection, it will automatically show the status page. When I reconnect while the app is open, I have to refresh the status page and it connects just fine to the TVH Server. The only thing it doesn't do, is recognize if Wi-Fi was disconnected while using the app. However I don't think this should be a problem considering the app would become a battery hog if there was a task to constantly check Wi-Fi connectivity.

**Comment by rsiebert** [comment]
Thanks for reporting. I close the issue then.
