### ISSUE TITLE
Show optional TVH channel #

### ISSUE THREAD

**Issue by dkonerma** [rsiebert/TVHClient#6]
Hi again,

an option to have the channel # shown in "Channels" and "Program Guide" would be appreciated. ;-)

In the grid also the channel name should be shown somehow, siince the logo alone is sometime not quite easy to identify on smaller devices.

Thanks
DIetmar.

**Comment by rsiebert** [comment]
I'm closing this. The icons or the name (if no icons are shown) should be sufficient. Adding channel numbers would requires more work in adapting the layouts in the EPG
