### ISSUE TITLE
Should add option SUBTITLE

### ISSUE THREAD

**Issue by PiterEL** [rsiebert/TVHClient#60]
I should add option subtitle when i click on the program. I should set up this option below blue TITLE.

**Comment by Andulien** [comment]
I think what he means is this here. See attached.
This can support in fixing the issue of https://github.com/rsiebert/TVHClient/issues/136
Also I think this field can be usefull considering some Series having as a title all the same name and only distinguish by Subtitle the Episode (Current, Finished & Failed Recordings). Also in Series Recording the Name field is used by me for grouping the different Series Recordings.

![subtitle1](https://cloud.githubusercontent.com/assets/12703546/7979287/3ca115be-0a9e-11e5-9dee-d65666e9b8c0.JPG)
![subtitle2](https://cloud.githubusercontent.com/assets/12703546/7979288/3ca6a380-0a9e-11e5-8e66-867f64047241.JPG)
![subtitle3](https://cloud.githubusercontent.com/assets/12703546/7979290/3ca8a2c0-0a9e-11e5-876a-acdb8240639b.JPG)
![subtitle4](https://cloud.githubusercontent.com/assets/12703546/7979291/3caab8bc-0a9e-11e5-93cc-3faed5d05861.JPG)
![subtitle5](https://cloud.githubusercontent.com/assets/12703546/7979289/3ca7f46a-0a9e-11e5-8176-df993bc7a5ff.JPG)

**Comment by rsiebert** [comment]
Added in the latest 1.8.0 beta. It will only be shown in the recording
lists when it actually contains something.

Andulien notifications@github.com schrieb am Do., 4. Juni 2015 um
09:51 Uhr:

**Comment by Andulien** [comment]
Yup works fine. Ticket can be closed from my perspective.
