### ISSUE TITLE
EPG grid with undesired gaps

### ISSUE THREAD

**Issue by dkonerma** [rsiebert/TVHClient#81]
Hi Robert,

looking at my EPG grid I see quite often gaps without info... when scrolling horizontally I notice that these gaps are always at the the egdes of a page, in the middle of a programme.  I configirmed in TVH that the enties in the EPG are fine w/o gap. 

Thanks in advance for looking into this
Dietmar.

**Comment by bigbig6** [comment]
The same here.

The last space of a line are often Empty...
That not the case in TVHeadEnd...

Thank's

**Comment by rsiebert** [comment]
I've noticed this too a while ago. Its related to the logic how the grid is displayed. I hope to find a better and faster way to display the program guide grid.

**Comment by dkonerma** [comment]
Hi,

just to show the issue I'm seeing:

![screenshot_2015-02-21-12-19-56](https://cloud.githubusercontent.com/assets/6400553/6315033/8780ea46-b9f4-11e4-8a09-faee4632a93a.png)

The shot was taken while swiping horizontally. 
E.g. in TVH "Das Urteil von Nürnberg" is ONE programme without any interrupt. Same for "Hammett". The red marked gaps are exactly at the edge when not swiping (red line).

Thx
Dietmar.

**Comment by rsiebert** [comment]
Hi Dietmar,

I have also noticed these issues. I'll look into these.

Best regards
Robert

2015-02-21 18:09 GMT+01:00 dkonerma notifications@github.com:

**Comment by rsiebert** [comment]
Is this still an issue with 1.7.6?

**Comment by dkonerma** [comment]
Seems to be fixed now. Thanks, Robert!
