### ISSUE TITLE
Amazon FireTV usage

### ISSUE THREAD

**Issue by Chefkoch81** [rsiebert/TVHClient#88]
Hi,

I try to use your app on an amazon fire tv. For usage there it would be great to have the possibility to start streaming only after pressing the channel. In that case the channel details should only be available as context menu option.

Would this be possible?

BR,
Andreas

**Comment by rsiebert** [comment]
Right now selecting a channel is done via a click. I don't know if its possible via cursor selection. There are none on a smartphone. What could be done is to press enter to select a channel and press enter again on the same channel to start playing.

**Comment by rsiebert** [comment]
The new version allows to directly select the channel icon to start playing. Does this resolve the issue?

**Comment by rsiebert** [comment]
Closing the issue for now.
