### ISSUE TITLE
TVHClient via VPN tunnel: no EPG data

### ISSUE THREAD

**Issue by dkonerma** [rsiebert/TVHClient#91]
Hi Robert,

just faced a weird issue wihen using your fantastic TVHClient via VPN tunnel... all seems to work, except EPG data. 

So I see the status, the channels, recordings, etc. But no programme information.

Do you have any idea how to trouble-shoot this? In the TVH log I only see TVHClient successfully connecting, no errors.

I use the defaiult Android 4.4.4 VPN client with IPSec XAuth RSA to connect to my Ubuntu 14.10 server running StrongSwan. 

All other traffic seems to work, wondering why the EPG stuff should be special? Maybe you have an idea... ;-)

Thanks in advance and Frohe Weihnachten.

Diietmar

**Comment by rsiebert** [comment]
Is this still an issue? Might be related to #92 comment "Right now I'm having to SSH tunnel to the box which is a little less forgiving of poor data signal."

**Comment by rsiebert** [comment]
Closing due to no feedback.
