### ISSUE TITLE
HTTPS Support

### ISSUE THREAD

**Issue by ShadowXVII** [rsiebert/TVHClient#92]
Hi there,

I run my tvheadend over a https reverse proxy. This gives the final API address a https://server/api/ address. The app currently assumes http.

It should be configurable (along with the address, port, etc) to enable https.

This would allow it to work securely over WAN scenarios.

**Comment by spicypixelxx** [comment]
Nginx reverse proxy support with SSL would be ideal (also support for "invalid" self signed certs). Right now I'm having to SSH tunnel to the box which is a little less forgiving of poor data signal.

**Comment by ShadowXVII** [comment]
Yeah that's what I'm using -- invalid certs need to be ignored.

**Comment by lwis** [comment]
Any news on this issue? Would be nice to get HTTPS support!

**Comment by rsiebert** [comment]
I have no such configuration to test any of this stuff here. Additionally the app opens a socket on port 9982 to the server. There is no url like connection. So I don't really know how to start/test here. Just opening a socket to the proxy on port 8080 for example can't be the solution. And changing the communication stuff of the app seems a bit to much for the request.

**Comment by rsiebert** [comment]
Closing the issue. This would be only applicable when the webapi would be used instead of htsp api.

**Comment by jclsn** [comment]
Really?? No https support? I can't believe it

**Comment by jclsn** [comment]
@rsiebert This is definitely not too much. I mean this is a must for secure playback. How else would you remotely use this app?

**Comment by rsiebert** [comment]
My app only tells the Videoplayer app to use the URL that points to the tvheadend server. The rest is between the tvheadend server and the videoplayer app. 
If the server does not provide Https playback, not my issue. I don't have the time and resources to update my app to act as a relay.
So if you want https or any other stuff then please contact the server guys.

**Comment by jclsn** [comment]
Nevermind, I am using Dreamplayer now which supports SSL connections. I still can’t believe that you did not implement this feature though.
