### ISSUE TITLE
Feature request: Show next show in channel listing.

### ISSUE THREAD

**Issue by sainf** [rsiebert/TVHClient#95]
One of the most useful feature on the old "TVHGuide by John Törnblom " is showing the current show and the next show on the channel list.

One suggestion. The current show title display in bold or higher font size than the next show title. It is very useful to zapping.

Thanks for this great app.

**Comment by rsiebert** [comment]
This was added in the upcoming version 1.7.0

**Comment by rsiebert** [comment]
Due to the rollback in version 1.7.3 to the codebase of 1.6.1 this bug will be fixed later.

**Comment by sainf** [comment]
I had only one small moment to see this feature in action.
But can you make it bold in the current show ?

**Comment by rsiebert** [comment]
Hi,
you mean making the text "next program: foo bar" below the progress bar
bold? Or only a particular part of it?

2015-02-18 20:20 GMT+01:00 Carlos Nogueira notifications@github.com:

**Comment by sainf** [comment]
Hi.
I think if the "Current Show" was in bold it make more visible.
Resuming highlighting the "Current Show".

![sample](https://cloud.githubusercontent.com/assets/1210947/6255526/7894baf6-b7a8-11e4-96da-61e21f9c75f7.png)

**Comment by rsiebert** [comment]
I think about going this way and making the font of the current show a bit
larger. Making it bold makes it look heavier. What do you think?
.
[image: Inline-Bild 2]

2015-02-18 21:00 GMT+01:00 Carlos Nogueira notifications@github.com:

**Comment by sainf** [comment]
I think is perfect.
Thanks!

**Comment by rsiebert** [comment]
Available in >= 1.7.4
