### ISSUE TITLE
Off-topc feature request: HTSP client implementing a custom TV input for Android TV

### ISSUE THREAD

**Issue by dkonerma** [rsiebert/TVHClient#96]
Hi Robert,

of course this is off-topic concerning the current TVHClient implementation... just a suggestion in general.

Wouldn't it be great to have an HTSP client implementing a custom TV input for Android TV?

https://source.android.com/devices/tv/index.html

I'm bothering you, since I'm sure you would have the required knowledge in both, Android and HTSP to make this happen. And I'm sure you could earn some bucks with it... ;-). 

Best regards
Dietmar.

**Comment by rsiebert** [comment]
I didn't read the entire article, but would TVHClient act as some kind of htsp player running on the android TV or delivering data to it?

**Comment by dkonerma** [comment]
Hi Robert,

yes, if I understand the article correctly then you can add your own "tv inputs" to Android TV. Those get integrated seamlessly including EPG, etc. The tvh client app would act as a virtual tuner used by the TV set.

Dietmar.

**Comment by rsiebert** [comment]
Implementing and testing this would be too much effort currently. I just don't have the time to do this. And I also don't own any Android TV devices to test this. If somebody starts the work and/or creates a PR I will gladly integrate this feature. Until then I'll close this issue.

**Comment by dkonerma** [comment]
Just for the records... if someone hits this request. There is a new project implementing a tvh client for AndroidTV. https://github.com/kiall/android-tvheadend
