### ISSUE TITLE
Support for timer based recording

### ISSUE THREAD

**Issue by gion86** [rsiebert/TVHClient#97]
Hello,
my Tvheadend server doesn't provide EPG info, so I was thinking of a timer based (scheduled) recording. I started to work on this on my PC (didn't have a Github account yet), now I wanted to fork the master branch, merge my changes to my branch, and ask for a pull request **BUT**:
* the updated master that I have cloned doesn't even compile in Eclipse and the project/folder structure is "not normal" (the res folder is recognized as a Java package). Did you move to Android Studio?? Or am I doing something wrong?? 
* I have seen from commit a7b0311a06e2ae863e652e0557d4ef2006e7b1c1 (Add initial support for timer recordings) that you are already working on this feature!! 

_I made a new fragment with layout and logic, new menu item in the navigation drawer and many other changes, Italian localization, and I have tested with my server that the logic is working!_
I don't have much experience with Git, so I kindly ask here for help to proceed: can some of you at least take a look at my changes? How should we do here in GitHub??

Sorry for the long post, thank you very much for the app!

**Comment by rsiebert** [comment]
I'm still working on this feature so the commits in github are incomplete so far.

**Comment by gion86** [comment]
Ok so do you think you can check my code to see if something is useful?
Do you know way  the project is not recognized as an Eclispe project any more?
Thanks

**Comment by rsiebert** [comment]
You can fork my project and create a pull request as you intended to do. That's how others do it with the language files. For the current state of the project you need the newest android support library that supports API 5.0.2.

**Comment by gion86** [comment]
OK, but my changes are really similar to yours....Almost the same line in some cases! 
Of course your modification are better integrated with the app and I actually have nothing to add right now...
I'll keep the repo in sync for the future. 
Thanks and sorry to have bothered you.

**Comment by rsiebert** [comment]
This will be included in the next version. Stay tuned.

**Comment by rsiebert** [comment]
Added in 1.7.7 in the search view. Requires the unlocked version of the app.
