### ISSUE TITLE
AutoRec don't appear in the grid.

### ISSUE THREAD

**Issue by bigbig6** [rsiebert/TVHClient#98]
For a rec program, an icon apear next the name of the show.

But for an Autorec program, nothing appear, so we can not know what is already scheduled.

Thank's

**Comment by rsiebert** [comment]
This should be fixed in the upcoming version 1.7.0

**Comment by rsiebert** [comment]
Due to the rollback in version 1.7.3 to the codebase of 1.6.1 this bug will be fixed later.

**Comment by rsiebert** [comment]
This should be fine in 1.7.4 onwards. So I'll close the issue.
